### ISSUE TITLE
WindowsSecureMimeContext with more certificate identificators

### ISSUE THREAD

**Issue by xtomas** [jstedfast/MimeKit#100]
Hello,

I started to use MimeKit this week with Windows certificate store so WindowsSecureMimeContext was logical choose. But there is only one identifier to identify certificate - mail address. What do I need is identification using Thumbprint. For testing purposes, I've easily created ThumbprintWindowsSecureMimeContext based on your code from git, but may be it can be useful for others to.

Also MultipartSigned Create method will be useful with Thumbprint parameter to use ThumbprintWindowsSecureMimeContext.

MultipartSigned Create(MyWindowsSecureMimeContext ctx, string certificateThumbprint, DigestAlgorithm digestAlgo, MimeEntity entity)

Well, I'm not sure, if this is the Issue but I'm also new on github...

Tomas

**Comment by jstedfast** [comment]
Hi xtomas,

It looks like WindowsSecureMimeContext was not updated to take advantage of the SecureMailboxAddress class which already has a Fingerprint (aka Thumbprint in Microsoft lingo) property for this purpose.

What you want to do is create SecureMailboxAddresses instead of normal MailboxAddresses if you'd prefer the Thumbprint to be used for lookups instead of the email address.
