### ISSUE TITLE
A special format email will trigger a verification bug.

### ISSUE THREAD

**Issue by byhnj** [jstedfast/MimeKit#1007]
The receiving email account having a special format (e.g. xxxx. xx. @ gmail. com) will trigger a bug prompt "Invalid local part at offset 0" when  add to 'MimeMessage To'.

**Comment by jstedfast** [comment]
The `local-part` of the email address is not allowed to end with a `.` character. That's why the parser throws a ParseException (which is the correct thing to do).

That said, you can make the parser more lenient by creating your own [ParserOptions](https://mimekit.net/docs/html/T_MimeKit_ParserOptions.htm) and setting the [AddressParserComplianceMode](https://mimekit.net/docs/html/P_MimeKit_ParserOptions_AddressParserComplianceMode.htm) to [RfcComplianceMode.Looser](https://mimekit.net/docs/html/T_MimeKit_RfcComplianceMode.htm):

```csharp
var options = ParserOptions.Default.Clone ();
options.AddressParserComplianceMode = RfcCompliance.Looser;

var mailbox = MailboxAddress.Parse (options, "xxxx.xx.@gmail.com");
```
