### ISSUE TITLE
Include CmsSigner or other SignedAttributes in Signed Message

### ISSUE THREAD

**Issue by xtomas** [jstedfast/MimeKit#101]
Hello again.

I'm facing problem with missing required SignedAttributes in signed/non-encrypted/non-compressed mime message. Is there any way, how to include for example SigningTime attribute for CmsSigner? I have solved this only by creating own derived classes for WindowsSecureMimeContext and MultipartSigned but it's a lot of duplicate code from MimeKit...

public MimePart Sign(string certificateThumbprint, DigestAlgorithm digestAlgo, Stream content)
        {
            if (string.IsNullOrEmpty(certificateThumbprint))
                throw new ArgumentNullException("certificateThumbprint");

            if (content == null)
                throw new ArgumentNullException("content");

            var contentInfo = new ContentInfo(ReadAllBytes(content));
            var cmsSigner   = GetRealCmsSigner(certificateThumbprint, digestAlgo);

            // add signingTime attribute
            cmsSigner.SignedAttributes.Add(new Pkcs9SigningTime());

            var signed      = new SignedCms(contentInfo, true);

            signed.ComputeSignature(cmsSigner);
            var signedData = signed.Encode();

            return new ApplicationPkcs7Signature(new MemoryStream(signedData, false));
        }

Regards,

Tomas

**Comment by jstedfast** [comment]
What you can do instead is this:

```csharp
var mailbox = new SecureMailboxAddress ("Joe Sixpack", "joe@sixpack.org", fingerprint);
var signed = ctx.Sign (mailbox, digestAlgo, content);
```

I've added the Pkcs9SigningTime as a standard attribute.

I haven't really spent a lot of time on the `WindowsSecureMimeContext` as almost all of my effort has been on the other implementation because my interest has been on making it work cross-platform using Bouncy Castle, so there may be other issues you'll encounter. I do appreciate the bug reports tho, as the WindowsSecureMimeContext should get polished to the same level as the Bouncy Castle backend.

In the other backend, the reason you can override `GetCmsSigner(MailboxAddress, DigestAlgorithm)` is so that you can add custom attributes. However, with the Windows backend, it uses `GetRealCmsSigner()` instead which isn't virtual.

**Comment by xtomas** [comment]
I've tried your fixed code and it works for my case as well. (Btw, I'm implementing As2 Protocol communication)

When will be this fix available on MimeKit Nuget Package?

Tomas

**Comment by jstedfast** [comment]
I've just released a 1.0.7 NuGet with this fix.

**Comment by xtomas** [comment]
Thank you. It works now for me :+1:

**Comment by jstedfast** [comment]
Awesome :-)
