### ISSUE TITLE
SQLite is not available. Install the System.Data.SQLite nuget package.

### ISSUE THREAD

**Issue by PrzemyslawKlys** [jstedfast/MimeKit#1035]
I've been following S/MIME example https://mimekit.net/docs/html/Working-With-SMime.htm and while it makes sense in shown case that I get `SQLite is not available. Install the System.Data.SQLite nuget package.` I am not sure why is it needed when I am using DefaultSecureMimeContext? I don't have any calls to SQLLite or anything, yet it complains about if I remove SqlLite? Is this some internal requirement?

```cs
using (var ctx = new DefaultSecureMimeContext()) {
    try {
        var signer = new CmsSigner(certificate) {
            DigestAlgorithm = DigestAlgorithm.Sha1
        };
        message.Body = MultipartSigned.Create(ctx, signer, message.Body);

    } catch (Exception ex) {
        // Settings.Logger.WriteWarning($"Send-EmailMessage - Error: {ex.Message}");
        // Settings.Logger.WriteWarning($"Send-EmailMessage - Possible issue: Certificate? ({certificate.Thumbprint} was used).");
        if (ErrorAction == ActionPreference.Stop) {
            throw;
        }
        return new SmtpResult(false, EmailAction.SMimeSignature, SentTo, SentFrom, Server, Port, stopwatch.Elapsed, ex.Message);
    }
}
```

**Comment by PrzemyslawKlys** [comment]
never mind, I see it's internally using it:
- https://github.com/jstedfast/MimeKit/blob/8e0b3729d849382ede303680e788b57af4aacbed/MimeKit/Cryptography/DefaultSecureMimeContext.cs#L101

**Comment by SergeBerwert** [comment]
I am just wondering if there is a way to use MimeKit without adding the SQLite package? Without knowing why this package is relevant, I can't see why it should be necessary?

**Comment by jstedfast** [comment]
If you aren't trying to encrypt/decrypt/sign/verify S/MIME messages using the DefaultSecureMimeContext, you don't need SQLite.

If you use the WindowsSecureMimeContext or the TemporarySecureMimeContext, they do not need SQLite.

**Comment by SergeBerwert** [comment]
Thanks, that solved my problem. I used the TemporarySecureMimeContext not WindowsSecureMimeContext in anticipation that this would also work on a Linux host. Did not try that yet. However, it seems to me the temporary context should be the default.

I publish my code below; someone may find that helpful.

```
    public async Task SendSignedMessageAsync(string userId, string subject, string content)
    {
        var signingCert = new X509Certificate2(
            "[filename]",
            "[password]",
            X509KeyStorageFlags.Exportable);

        // 2. Create a MIME email and sign it with the certificate
        var mimeMessage = new MimeMessage();
        mimeMessage.From.Add(new MailboxAddress("[name]", "[e-mail]"));
        mimeMessage.To.Add(new MailboxAddress("[name]", "[e-mail]"));

        mimeMessage.Subject = subject;

        // Create the email body (can be plain text or HTML)
        var bodyBuilder = new BodyBuilder
        {
            TextBody = content
        };

        // (Optional) Add attachments if needed: bodyBuilder.Attachments.Add("file.txt");

        // Sign the message body using the certificate (create a multipart/signed MIME part)
        var signer = new MimeKit.Cryptography.CmsSigner(signingCert)
        {
            DigestAlgorithm = DigestAlgorithm.Sha256 // choose SHA256 or as required
        };

        var context = new TemporarySecureMimeContext();

        // By default, the signer will include the full certificate chain in the signature.
        mimeMessage.Body = MultipartSigned.Create(context, signer, bodyBuilder.ToMessageBody());

        await SendMimeMessageAsync(userId, mimeMessage.ToString());
    }
```

**Comment by jstedfast** [comment]
> However, it seems to me the temporary context should be the default.

The problem with the TemporarySecureMimeContext is that it is all in memory and does not persist between sessions, which is what most applications would actually want.

For your specific use-case, this does not matter because you are loading and using the signing certificate directly, but the idea of the CryptographyContext is that it can store/load/select certificates and certificate chains *for you*.

Let's say you modify your use-case just a little bit and decide you want to encrypt to the recipients of the message. Now you'll need to manually locate and load all of the appropriate certificates for all of the recipients yourself rather than allowing MimeKit's SecureMimeContext to do it for you by looking up certificates based on mailbox address (or fingerprint).

FWIW, ideally when you sign an S/MIME message, you also want to include the entire X509 certificate chain (other than the root) and not *just* the signer's certificate like you are doing in your case.

As to the question about *why* the use of SQLite... well, that comes mostly from the fact that it provides a convenient storage format that can easily be searched. Arguably, I could have designed a custom format that MimeKit could have used instead of SQLite so that it didn't have to pull in another dependency, but that would have been a lot of extra work for me.

I debate this decision with myself all the time because I get a lot of complaints about it as well as the fact that it is now an issue with the AOT-ability of the library, but no one has yet offered a better solution.

I typically recommend the WindowsSecureMimeContext for projects that *know* their app will only run on a Windows platform because it's probably the best option on Windows, but that leaves out projects that are expected to run on Linux or MacOS (or mobile or embedded platforms).

Trust me, there's nothing I would love more than to not have to deal with trying to find a solution for storing certificates and CRLs in a way that makes everyone happy.

**Comment by SergeBerwert** [comment]
Thanks for the great explanation. I did understand that there is some kind of caching involved in the context, or that caching is the purpose.  In my opinion, I should not be included in the main library itself. To my understanding, the idea of the library is to provide wicked fast support to create Mime Messages or parse them. Integrating some caching solution deep in the inerts for certificates is not what I expected or wanted from the library. In My case, in production, I am going to retrieve the certificate from an external secure source like Azure Key Vault. The application will run in a container. I Would properly remove it from the main project and put it in a separate NuGet package that can be used if this kind of caching is required.
I did notice some issues with my signed emails, probably because I did not include the howl certification path. When I opened up in outlook, it did not look trusted first. But after a while, it downloaded it automatic. I guess I have to figure out how I can include the howl path.
