### ISSUE TITLE
MailKit crashes from headers in Korean

### ISSUE THREAD

**Issue by SviatoslavRazmyslov** [jstedfast/MimeKit#1064]
**Describe the bug**

I received an email from Korean student and saw a MailKit exception in my service.

**Platform:**
 - OS: Linux
 - .NET Runtime: .NET 8
 - MailKit Version:  4.7.1.1
 - MimeKit Version: 4.7.1

**Exception**

```
System.FormatException: Failed to parse headers.
   at MimeKit.MimeParser.ParseHeaders(Byte* inbuf, CancellationToken cancellationToken)
   at MimeKit.MimeParser.ParseHeaders(CancellationToken cancellationToken)
   at MimeKit.HeaderList.Load(ParserOptions options, Stream stream, CancellationToken cancellationToken)
   at MimeKit.HeaderList.Load(Stream stream, CancellationToken cancellationToken)
   at MimeKit.MessageDispositionNotification.get_Fields()
```

**To Reproduce**

I guess the reason is this:

```
From: "=?UTF-8?B?7ZmN7KeE6re8?=" <jkhong@bu.ac.kr>
```

or that:

```
Reporting-UA: mail.bu.ac.kr; 백석대학교
```

**Expected behavior**

A mail is loaded without exceptions.

**Comment by SviatoslavRazmyslov** [comment]
Hi @jstedfast,

I've attached the original .eml file of the Korean email.

[Read- PVS-Studio for educational purposes.txt](https://github.com/user-attachments/files/16643733/Read-.PVS-Studio.for.educational.purposes.txt)

**Comment by jstedfast** [comment]
Okay, so, looking at this email, the reason that it failed wasn't because it was in Korean but was because the `Content-Transfer-Encoding` is set to `base64`, therefore, when it goes to parse the content (another set of "headers", it fails because the parser is dealing with the result of whatever the base64 decoder gives back (which will be garbage because it's not really base64 encoded).

I'm not sure what can really be done by MimeKit, here. This is really a bug in the sending client.

**Comment by SviatoslavRazmyslov** [comment]
@jstedfast , thank you for the feedback!
