### ISSUE TITLE
Mboxo / mboxrd parsing

### ISSUE THREAD

**Issue by guywyers** [jstedfast/MimeKit#108]
Hi all,

I have been using mimekit to parse large mbox files and I have been very impressed with the performance of it.
Recently I discovered an issue with the treatment of the infamous "From lines". When an email contains a line that starts with the text "From " (ie the word From followed by a space), in mboxo and mboxrd format this line is escaped with a '>' character. Normally mbox creators add these escape characters and mbox readers should strip them.

I have used mimekit about a year ago and was under the impression that the library supported this, but yesterday I started another project and saw that the '>' are not processed correctly, so I'm a bit puzzled here: has anything changed recently? Can this be turned on or off some way? Maybe it never was there and I'm just having delusions. In that case I'm going to have to handle this in my own code, which would be a bit of a bummer, because it means going through the whole file one more time.

Any help would be appreciated.

Guy Wyers

**Comment by jstedfast** [comment]
Thanks for the compliment on MimeKit's performance!

Unfortunately, the historical mbox format uses From-mangling (not to be confused with *quoting*) and is irreversible w/o breaking existing software that has been around for decades.

For example, if I send you a message with a line starting with `">From "` and you treat it as a form of quoting and reverse it, then you will not be following the same de-facto mbox standards that other mail clients have been following for decades and risk corrupting the message.

This is an especially bad practice when said message body is cryptographically signed using S/MIME, PGP/MIME or even "inline" PGP. The S/MIME and PGP/MIME standards suggest the use of the quoted-printable Content-Transfer-Encoding for message bodies that include lines beginning with `"From "`, taking special care to encode the `"From "` as `"=46rom "` to prevent the receiving MDA from munging it with a '>'. In practice, however, many mail clients will pre-mangle these lines into `">From "` before cryptographically signing the message so that the message will still be verifiable on the other end even if said client uses the mbox format for storage. When sending "inline" PGP signatures, the PGP program (or the PGP plugin) itself is responsible for munging and since it cannot change the Content-Transfer-Encoding itself (it's only allowed to modify the text content, not the headers), it's only option is to mangle.

If you are confident that all of your messages that have a line beginning with `">From "` were originally meant to be `"From "`, then an easy fix for you to do is something like the following:

```csharp
foreach (var part in message.BodyParts.OfType<TextPart> ())
    part.Text = part.Text.Replace ("\n>From ", "\nFrom ");
```

Note: MimeKit has never demangled these.

Hope that helps.

**Comment by guywyers** [comment]
Thanks for the quick reply.
The source of the problem is that we have been using test data that we created by using Gmail dumps, ie the things you get when you backup a Gmail mailbox through Google Takeout. The resulting *.mbox files definitely use the historical >From mangling. So yes, I will have to do something like you suggested.

The reason I was hoping that it was part of Mimekit was performance of course. Once you've seen Mimekit gobbling up 1 gig of emails in less than a minute, the idea of putting some post-processing on that, feels like driving a Ferrari but not going beyond third gear.

Anyway, I understand the explanation, so thanks for the feedback and these excellent tools.

**Comment by jstedfast** [comment]
No problem :-)

And hopefully MimeKit is gobbling up more than 1 gig of emails in less than a minute, it should be gobbling up 1 gig every ~2-3 seconds :-)
