### ISSUE TITLE
MimeMessage Sender is null, but From has an item?

### ISSUE THREAD

**Issue by catmanjan** [jstedfast/MimeKit#1080]
I'm not sure who implements the logic described in Sender, but I have a gmail email which has a null Sender but a From with a list of one.

![image](https://github.com/user-attachments/assets/53138fa7-24d2-4ee9-840d-f40858e5a5e2)

The docs for Sender say:

![image](https://github.com/user-attachments/assets/f1d7b2be-27cc-476c-9f8d-ba1e1c820b70)

But as far as I know nothing special happening in regards to the sender. Is this a MailKit issue or an Exchange Online one?

**Comment by jstedfast** [comment]
Would this wording be more clear?

The "Sender" field specifies the mailbox of the agent responsible for
the actual transmission of the message. For example, if a secretary were to send a
message for another person, the mailbox of the secretary would appear in the
"Sender" field and the mailbox of the actual author would appear in the "From"
field. If the originator of the message can be indicated by a single mailbox and
the author and transmitter are identical, the "Sender" field SHOULD NOT be used.
Otherwise, both fields SHOULD appear.
