### ISSUE TITLE
How to not display attachment

### ISSUE THREAD

**Issue by MilesFan** [jstedfast/MimeKit#1109]
With the code below, I managed to embed an image (a logo) in the message body, however, the image is also shown in the attachment list. What I expect is that the image shall not be shown as attachment, so that the recipient will not be distracted to download and view it.

```
var message = new MimeMessage();
//...
var mimeentity = bodyBuilder.LinkedResources.Add("image.png");
var contentId = MimeUtils.GenerateMessageId();
mimeentity.ContentId = contentId;
bodyBuilder.HtmlBody = "<img width=101 height=34 style='width:1.05in;height:.3583in' src=\"cid:${contentId}\" />";
message.Body = bodyBuilder.ToMessageBody();
```

I tried another way around by setting ``ContentDisposition`` to ``inline`` and also ``IsAttachment`` to ``false``, but it makes no difference.
```
var message = new MimeMessage();
//...
var contentId = MimeUtils.GenerateMessageId();
var bodyBuilder = new BodyBuilder();
using var stream = new FileStream(path: "image.png", mode: FileMode.Open);
var attachment = new MimePart("image", "png")
{
    Content = new MimeContent(stream, ContentEncoding.Default),
    ContentDisposition = new ContentDisposition(ContentDisposition.Inline),
    ContentTransferEncoding = ContentEncoding.Base64,
    ContentId = contentId,
    IsAttachment = false
};
var multipart = new Multipart("mixed");
var textPart = new TextPart ("html")
{
    Text = "<img width=101 height=34 style='width:1.05in;height:.3583in' src=\"cid:${contentId}\" />"
};
multipart.Add(textPart);
multipart.Add(attachment);
message.Body = multipart;
```

Email client is MS Office Outlook 365.

Can you please help? @jstedfast

**Comment by jstedfast** [comment]
The best advice I can offer you is to create a message in Outlook that has an inline image and send it to an account that can look at the raw MIME message and then try to mimic that MIME structure using MimeKit.

If it sets Content-ID, set a Content-ID. If it doesn't, don't.
If it sets Content-Disposition: inline, then do that. If it doesn't, don't.
If it uses an `<img>` tag that references the image using a `cid:...` URI, then do that too - otherwise, don't.

If you are old enough to remember the Wild West of designing websites to render correctly in every web browser that your customers might use, this is the exact same thing.
