### ISSUE TITLE
boundaries and MimePart question

### ISSUE THREAD

**Issue by polterguy** [jstedfast/MimeKit#111]
Howdy, when I create a MimePart which is for instance a text type, then what TransferEncoding do you suggest I use to make sure that I don't "accidentally" end up having the Boundary being a part of the content of my transferred text ...?

Let's say I have some javascript file for instance I wish to transfer, and for some reasons the boundary exists within my javascript file ...?

For binary types transferred this is taken care of, since they're transferred encoded as base64, but in theory one might imagine the boundary as a piece of string inside my text parts ...?

Is this taken care of automatically by MimeKit, or do I have to make sure I transfer my text parts with some special encoding ...?

Sorry if this is a dumb question, but I'm using MimeKit in "weird places" one might say, since I'm combining it with REST webservices, instead of using it traditionally with email ...

**Comment by jstedfast** [comment]
The multipart boundary is a fairly long random string, so it's unlikely you'd randomly have it in your text by accident. You can also use the Multipart.Boundary getter to get the boundary string that MimeKit will use to be sure.

If you encounter your javascript scenario, the only real solutions to that are to use base64 encoding and/or to change the boundary string. I'd probably recommend changing the boundary string, honestly. The problem with base64 is that it increases the size by 33%, that might be a significant amount.

MimeKit doesn't make sure that the content of mime parts doesn't contain the boundary string, so if you are concerned about that, then you'll need to do it yourself, but as I said, it's a fairly long random string that is very unlikely to just randomly be there.

I wouldn't worry about it.

My previous MIME library, GMime, has been around since 2001 and no one has ever reported this type of thing happening and it's very widely used.

**Comment by polterguy** [comment]
Thx :)
