### ISSUE TITLE
Suggestion for Content-Length extension header, to avoid base64 encoding

### ISSUE THREAD

**Issue by polterguy** [jstedfast/MimeKit#113]
Howdy, I was thinking about your answer to my previous question, where you said that text/xxx parts didn't need to be base64 encoded, due to that the boundary was "statistically globally unique", due to its underlying randomness, and it made me start thinking ...

Would it be totally out of the question to create support for an "extension header" named e.g. "Content-Length", which would completely eliminate the needs to base64 encoding, also of binary data, I think, since then MimeKit could just read a "fixed length", if that header exists, instead of looking for a boundary, meaning the boundary becomes meaningless for such cases, making it possible to avoid base64 encoding of also binary types of data ...?

I know this might sound like EEE, and "destroying of standards", but I don't really think so, since _only_ if that header exists, MimeKit would go into "read a fixed length bytes", instead of reading until boundary. Besides, the boundary could still be created as usual, making clients that don't support it, probably just simply ignore it, and read until boundary. While MimeKit, which supports that header, would then instead of reading until "boundary", would read a fixed length bytes.

First of all, I think this might improve the load-speed of MimeParts, since reading a fixed length, obviously must be faster than to always having to check for the boundary during read operations. Beside, and more importantly, not having to base64 encode stuff, while still having a _guarantee_ of that the boundary does not exists within binary data, would save apprx. 33% of space, for every binary data ...

Maybe it's a stupid suggestion, and maybe it wouldn't work for other reasons, which I cannot see, but think about it ...

I realize this would be an "edge-case", but I think that MIME in general serves greater purposes than "only email stuff", which is why I am creating a WebService API on top of it, by combining REST Web Services with MIME for instance ...

I know this sounds "weird" probably, but let's say you query a REST Web Service for "contacts", at e.g. someurl.com/contacts. By returning multipart messages, instead of for instance pure JSON or XML, one can easily allow returning "associated objects", such as "Contact Images" in the same request, reducing the number of HTTP requests a Web Service client needs to do to request all "contacts".

I think the above use-case is kind of in the spirit of HTTP2.0 ...?

**Comment by jstedfast** [comment]
MIME actually already supports `Content-Transfer-Encoding: binary` and MimeKit already supports it :-)

A `Content-Length` header is not actually needed for that since even binary data is not likely to contain the random set of characters that make up the boundary string. There is actually already a `Content-Length` header in use where the purpose is more-or-less exactly what you have envisioned, but it was never accepted as a standard because of the need to maintain compatibility with existing software that followed specifications that did not have that requirement.

For example, say MimeKit sends a multipart containing an unencoded binary attachment that contains within it the exact boundary sequence that would signal to a parser that it has reached the end of the content. BUT! MimeKit adds a Content-Length header to specify the binary content length... well, that's all great and wonderful for receiving clients that implement support for Content-Length, but if they don't, then they'll blow up.

It also has problems when data passes through a system that uses a different end-of-line sequence, since the Content-Length header value relies on byte counts which change if the end-of-line sequence is CRLF vs LF. For the transport phase, it doesn't matter since the convention is to canonicalize to CRLF to send over the wire, but mail software tends to store the message in the system format.

Since the boundary is of the form `"\r\n--{boundary}\r\n"` or `"\r\n--{boundary}--\r\n"`, it's still incredibly rare for even binary data to contain the boundary string sequence, so it's still not necessary to base64 encode or anything simply based on binary data vs text. Arguably, text is more likely to contain the sequence than binary data is.

**Comment by polterguy** [comment]
Thank you for a very detailed and thorough explanation as usual :)
I guess lesson learned from all of this, is to not try to be a "wise guy" when it comes to choosing encoding for my objects and data, and leave that up to the consumer of the library, such that instead of choosing one over the other, allowing the consumer of the library explicitly choose the Content-Transfer-Encoding of his data ...

Do you have any thoughts in general terms, about the other idea, which is to use MIME as the transport format for REST Web Services ...?

Does it make sense ...?

**Comment by jstedfast** [comment]
For what it's worth, check out MimePart.GetBestEncoding() - it's a nice little helper method that helps you pick the most efficient Content-Transfer-Encoding for your data given a set of constraints.

I don't really know enough about REST to give an opinion. MIME has it's uses, but with modern computing, there are probably more efficient ways of serializing compound documents.

**Comment by polterguy** [comment]
Thx :)
BTW, I am not sure if I agree with you on your last sentence, since MIME supports all these other beautiful constructs, such as encryption and signatures out of the box. Since it's an open standard too, I don't think it'll fall to the problems posed by other suggestions, such as SOAP and similar constructs. I'll anyway give it a try ... ;)

But then again, I'm considered to be "the guy with the weird ideas". I've invented a programming language, with no syntax, based upon modifying the execution tree directly, called Hyperlisp, built on an alternative to method and function invocations, replacing OO's polymorphism mechanisms with the ability to override on function level, without any classes or objects, with an expression engine facilitating for that there are no variables in the language, still everything is mutable ...

And so on ... ;)

So I think I'll go with MIME and MimeKit for this job :D

**Comment by jstedfast** [comment]
Well, there are certainly *worse* ways of serializing compound documents than using MIME :-)
