### ISSUE TITLE
CreateFromMailMessage generates duplicated From and To addresses

### ISSUE THREAD

**Issue by jacargentina** [jstedfast/MimeKit#115]
When using *MimeKit.MimeMessage.CreateFromMailMessage* static method to convert my .NET -*MailMessage* to a *MimeMessage*, i get a mail which has duplicates on the message.From and message.To collections.

# Example

# Original MailMessage
* From: person@server.com
* To: other@host.com

# Result MimeMessage
* From: person@server.com, person@server.com
* To: other@host.com, other@host.com

**Comment by jstedfast** [comment]
I have a theory. Are you doing the conversion of your MailMessage into a MimeMessage after sending it via System.Net.Mail.SmtpClient?

Looking at Microsoft's reference source for MailMessage, it looks like the MailMessage.From, To, etc are not pushed to the MailMessage.Headers until the message is sent, but I'm not 100% sure about that (I've really just given their source code a quick glance).

Since `CreateFromMailMessage()` clones the headers and then adds the MailMessage.From, To, Cc, etc properties to the equivalent properties on MimeMessage, it would seem that the duplicating is coming from that.

**Comment by jacargentina** [comment]
Exactly, i've sent it already!
Anyway, doen't it seems like a bug? Or at least, API documentation should warn about that assumption on "the message was not sent!"

**Comment by jstedfast** [comment]
Oh, yes, it is still a bug. I just wanted to figure out why my tests hadn't discovered the problem and to make sure I was understanding what the issue was.

I have a patch I'm about to commit...

**Comment by jstedfast** [comment]
Okay, should be fixed now. I'll make a new MimeKit release this weekend and push new packages to NuGet when I do.
