### ISSUE TITLE
Support for .NET 3.5

### ISSUE THREAD

**Issue by nlvraghavendra** [jstedfast/MimeKit#131]
Is there a version of the tool which works with .NET framework 3.5?

**Comment by jstedfast** [comment]
Unfortunately .NET 3.5 does not support CancellationTokens :-(

**Comment by nlvraghavendra** [comment]
This is unfortunate. Now I can't use the best MIME parser in the business :(

**Comment by jstedfast** [comment]
You could probably just modify MimeKit to remove all of the uses of CancellationToken

**Comment by nlvraghavendra** [comment]
Probably. Will look into it.

**Comment by jstedfast** [comment]
I've ported MimeKit to .NET 2.0

**Comment by nlvraghavendra** [comment]
That's great. Let me try it.

**Comment by jstedfast** [comment]
Just released MimeKit 1.0.14 with .NET 3.5 support to nuget.org

**Comment by veverkap** [comment]
@jstedfast what is the current framework support level?

**Comment by jstedfast** [comment]
MimeKit supports .NET 3.5, .NET 4.0, .NET 4.5, Xamarin.iOS, Xamarin.Android, WindowsPhone81 and some PCL platforms that I can't recall at the moment.

.NET 2.0 is not supported, it compiled under Mono but not under Microsoft .NET due to the fact that Mono just aliases .NET 2.0 to .NET 4.0 or 4.5 or something.

**Comment by veverkap** [comment]
Thanks!
