### ISSUE TITLE
Attachment without ContentDisposition not showing in the Attachment list

### ISSUE THREAD

**Issue by LeeBear35** [jstedfast/MimeKit#141]
I have some emails the Body Part properties are something like:

------=_NextPart_1299172005-298625070-1858814026
Content-Type: 
 application/vnd.openxmlformats-officedocument.spreadsheetml.sheet; 
 name="PS8154 Claim.xlsx"
Content-Transfer-Encoding: base64
Content-ID: <5C6ED72F8A5DD549B1633A944894142E@woodsint.com>

Currently those items are defaulting to inline, which normally would mean that they would be part of a display body, but if the content-id is not referenced then they are not part of the display body either. Outlook treats these as attachments.
I had to drop back and process against the body parts instead of using the attachments collection because of this type of issue. Not sure if you would want to change this or not.

**Comment by mike-nelson** [comment]
When using outlook it is possible to drag files (like excel files for example) into the content area of the email. This may be how you can reproduce this weird behaviour. It's actually a nice idea - instead of just attaching ten excel sheets as attachments you can write an introduction text in between each one. So ideally you would want to reconstruct this when displaying email to user. Not sure if cids would be referred to in this case or some other method to position them - could be just multiple html parts in between the excel files in this case. (Sorry not testing this, just thought it might give you some ideas in case you didn't already think of this)

But if you want to make it simple, if it's not an inline image (check mime type) that's referenced by cid then treat it as an attachment. 

Mike Nelson // CEO // beweb
p. 09 3077042 // m. 027 4403757

**Comment by jstedfast** [comment]
I re-checked the various MIME RFCs and they unfortunately did not provide any definitive answer as to how to treat MIME parts w/o a Content-Disposition header and so I believe that the only assumption that MimeKit can make is that it is meant to be displayed "inline" or, at the very least, leave it up to the client to decide (which is what it effectively does now).

@mike-nelson You might be correct. I certainly wouldn't be surprised if Outlook supported that.

In the 90's, I think Eudora used to create messages with multiple text parts and image parts that the receiving client was meant to display inline to the recipient.

This was all pre-MHTML. Once HTML mail became popular, that quickly became the way clients would embed inline images because it provided a way to get even closer to WYSIWYG than alternating text and image parts ever could.

I'm pretty sure I've got samples of these types of messages in my archives.

**Comment by mike-nelson** [comment]
Mmm Eudora 

Mike Nelson // CEO // beweb
p. 09 3077042 // m. 027 4403757

**Comment by LeeBear35** [comment]
For a different reason I need to hit all the body parts to build the displayed attachment list, the auditors expect the attachment list to match Outlook, so it works for me.
