### ISSUE TITLE
Attachment modification

### ISSUE THREAD

**Issue by demidov71** [jstedfast/MimeKit#163]
When modifying or adding an attachment, developers are supposed to use the code like this:
MimePart.ContentObject = new ContentObject(Stream).
The problem here is, that ContentObject does not read the stream right away, stores it internally, but doesn't own it and is not disposable itself. Since the stream can't be disposed till the message is saved, the caller has to keep track of all such streams and then dispose of them en masse. Compare it to .NET stream wrappers, such as StreamReader, which always own the underlying stream and are disposable.
The same must go for ContentObject, MimePart and MimeMessage, or ContentObject constructor must read the stream into memory (as Microsoft often does).

**Comment by jstedfast** [comment]
The GC will still collect and dispose the stream.

It was really designed like this on purpose so that you have full control over when those streams are disposed which is needed because you could get creative and re-use the same stream and/or MimePart in multiple MimeMessages, at which point - how can MimeKit really ever know when to dispose your stream?

You can either read the file stream into a MemoryStream before setting it, or you can track the stream and dispose it when you are done with the message.

This gives you the most amount of flexibility.

You'll also notice that the MimeParser has a `persistent` option allowing you to parse messages while keeping the message stream open and having the MimeParts all refer back to the file stream rather than duplicating the message into memory, thus saving you quite a lot of memory usage (and it also has the benefit of improving parsing performance).

**Comment by jstedfast** [comment]
I wrote up a patch to make MimeMessage, MimeEntity and ContentObject disposable.

**Comment by demidov71** [comment]
Thank you. How do I get it?

**Comment by jstedfast** [comment]
I haven't committed it yet. I'll commit it soon.

**Comment by jstedfast** [comment]
I've committed the patch.

**Comment by jstedfast** [comment]
I reverted the patch because this breaks API contracts.

You are welcome to apply the patch to your own local copy, though: https://github.com/jstedfast/MimeKit/blob/master/disposable.patch

**Comment by demidov71** [comment]
Please, don’t rush it. Currently, I make a MemoryStream on top of a byte array and use the fact, that its disposal is a no operation.

But in a distant future, you might reconsider the API contract, or better, introduce a flag, controlling the underlying stream ownership, as Microsoft did in .NET 4.5.

Anyway, thank you for fast response.

**Comment by jstedfast** [comment]
The problem with Dispose() is it makes the following types of things very non-intuitive:

1. multipart[i] = CreateNewMimePart ();
2. multipart.RemoveAt (i);

Should those dispose the MimePart that was at index `i`? I don't know and it's not at all clear what one should even expect it to do, which is a problem.

Then there's the BodyBuilder class which has a `ToMessageBody()` method which returns all of the `Attachments` and `LinkedResources` in a nested MIME structure. But what if I call `ToMessageBody()` twice? That will return 2 different MIME structures, but the `Attachments` and `LinkedResources` will be shared and so disposing one message will dispose parts of the other message.

This also begs the question: should AttachmentCollection and BodyBuilder, then, also be disposable? Because if I end up adding attachments and/or linked resources and then don't call `ToMessageBody()`, then all of the `MimeParts` I've added will not be disposed.

This quickly becomes a nightmare to deal with.

**Comment by demidov71** [comment]
You are right, “disposable” is not a correct solution here.

Think of it from another angle. When we load MimeMessage from file, it is loaded into memory, so the file is released (and we can delete it right away).

Your case is like Microsoft’s burning API – IMAPI. There you create a disk image in memory and add IStream(s) to it. Then Microsoft adds the stream content to the image and doesn’t need the COM stream any more, so you can release it immediately. Maybe this is the correct strategy here - CreateNewMimePart must read the stream entirely, so user can dispose it right after.

**Comment by red-cap** [comment]
Just for reference for anyone looking for an alternative to dispose the streams after sending the email with no need to track them, simply by accessing the stream of the MimeMessage

`	    public static void DisposeStreamsInMimeMessage(MimeMessage msg)
	    {
	        foreach (var part in msg.BodyParts)
	            (part as MimePart)?.Content.Stream.Dispose();
	    }
`

Thank you for all the great work in this great library

**Comment by jstedfast** [comment]
Thanks for the tip, that's a nice little way of doing it ;-)
