### ISSUE TITLE
Display Name in 'From' header is broken in gmail

### ISSUE THREAD

**Issue by MadRabbitKiller** [jstedfast/MimeKit#170]
Hello, I need your advice

When I send email with 'from' address `Fotololo.ru - Интернет магазин <fotololo@retailrocket.net>`
Gmail displays  just `Fotololo.ru -` as display name. 

After encoding this header looks like

```
From: "Fotololo.ru -" =?utf-8?b?0JjQvdGC0LXRgNC90LXRgi3QvNCw0LPQsNC30LjQvQ==?=
	<fotololo@retailrocket.net>
```

After some investigation, I've found that GMail works fine if this header is encoded using `Rfc2047.EncodeText` method and looks like this

```
"Fotololo.ru - =?utf-8?b?0JjQvdGC0LXRgNC90LXRgiDQvNCw0LPQsNC30LjQvSI=?= <fotololo@retailrocket.net>
```

Honestly, I don't understand why in the first case token is taken in quotes.

What do you think about this? Is that means that gmail doesn't fully support RFC? 
Is it possible to configure encoding to force gmail support?

**Comment by jstedfast** [comment]
`Rfc2047.EncodeText()` is meant to be used for unstructured header fields (e.g. `Subject`) while the `Rfc2047.EncodePhrase()` method is meant to be used with structured headers such as `To`, `Cc`, `From`, etc.

The `"Fotololo.ru - =?utf-8?b?0JjQvdGC0LXRgNC90LXRgiDQvNCw0LPQsNC30LjQvSI=?= <fotololo@retailrocket.net>` string is actually completely broken when used with an address header because when an address header parser encounters a quote, it is supposed to consume text until it finds a matching end-quote. There is no matching end-quote in that string, so the fact that GMail displays this correctly might suggest that GMail is decoding the header and *then* parsing it rather than parsing it and *then* decoding it (which is what the RFC's specify is the correct way to do it).

Going back to the first string (produced by `Rfc2047.EncodePhrase()`):

"Fotololo.ru -" =?utf-8?b?0JjQvdGC0LXRgNC90LXRgi3QvNCw0LPQsNC30LjQvQ==?=
    <fotololo@retailrocket.net>

The way that this is supposed to be parsed is that the address header parser consumes the `"Fotololo.ru -"` segment of the string as a `qstring` token and unquotes it, putting it into "name" buffer to later be combined with any following text. Next, it consumes the `SPACE` token and appends that to the aforementioned buffer. Then it consumes the `=?utf-8?b?0JjQvdGC0LXRgNC90LXRgi3QvNCw0LPQsNC30LjQvQ==?=`, notices that it is an rfc2047 `encoded-word` token, decodes it, and then appends it to the name buffer. And then, of course, it finds the address and parses that.

So the value produced by MimeKit is correct and GMail is broken.

The reason that "Fotololo.ru -" is quoted is because the `.` is not allowed to exist outside of a `qstring` token if it is part of the name (and it is).

There's no way for me to work around this GMail bug that I can think of that will not break other mail software.

**Comment by MadRabbitKiller** [comment]
Ok, thank you for clarification, I see your point,

As far as I know display name does not require quotes. Encoding address without quotes can be working solution for me. Unfortunately there is no way to encode address without quotes.

**Comment by MadRabbitKiller** [comment]
Thank you for clarification
