### ISSUE TITLE
Date parsing fails on localized timezone

### ISSUE THREAD

**Issue by quentez** [jstedfast/MimeKit#179]
We've received some emails that were sent by [Incredimail](http://www.incredimail.com/en) and that have their dates in the following format:

`Date: Thu, 1 Oct 2015 14:40:57 +0200 (Mitteleurop�ische Sommerzeit)`

That last part is `Mitteleuropäische Sommerzeit`, the german name for one of the European timezones. 

After being parsed with MimeKit, the email has a date of `12/31/69 4:00 PM`. I'm not sure if this is because of the timezone, but it's the only part that looks unusual to me.

**Comment by jstedfast** [comment]
The unit test that I just added seems to return the correct DateTimeOffset value.

MimeKit will only use the comment if it matches one of the known timezone abbreviations.

I'm not sure why the parser is failing for you but passing for me.

**Comment by quentez** [comment]
Oh ok. Thanks for taking the time to check. 
I'll let you know if I can find other clues as to why the date parsing failed.

**Comment by jstedfast** [comment]
One thing to pay attention to is what property you are getting this invalid DateTimeOffset value from. Is it the Date property of a MimeMessage? Or is it the InternalDate property of a MessageSummary as gotten via IMAP? Or is it the Date property on the MessageSummary's Envelope?

The InternalDate string does not come from the Date header, but is rather a date string provided by the IMAP server to denote when the message arrived.

The Date property on the Envelope *is* supposed to be identical to the Date header of a message, but it is parsed (and re-serialized) by the IMAP server, so it's possible that the IMAP server's date parser got confused.

Of course, these all depend on where you got the incorrect DateTimeOffset value.

**Comment by jstedfast** [comment]
If it is the Date property of a MimeMessage, check to see if the `message.Headers` contains a Date header. If not, then the problem is because the Date header is not being parsed, probably for 1 of the following reasons:

1. There is a blank line somewhere before the Date header, thus making the parser think that the Date header is actually just part of the message body and not part of the headers
2. The Date header is appended to the end of the previous header - i.e. no newline sequence between the end of the previous header and the Date header

It could also be a bug - perhaps some sort of Read() boundary issue... I'll probably need a sample message if that's the case, though. Tracking down Read() boundary issues is incredibly painful to do without a test case.
