### ISSUE TITLE
MimeMessage.ToString() cannot change encoding?

### ISSUE THREAD

**Issue by tausi0661** [jstedfast/MimeKit#189]
hello jstedfast,

I should say thank you for your excellent project first.

Recently I meet an encoding problem when invoking MimeMessage.ToString(). By looking into the source it seems it always uses CharsetUtils.Latin1.GetString()...

Is there anyway that I can change the encoding to use utf8 instead? Or any work around I can do?

**Comment by jstedfast** [comment]
Why aren't you using MimeMessage.WriteTo(Stream)?

ToString() is just for debugging purposes.

The reason that ToString() uses latin1 is because no other charset can be used reliably to convert data of mixed charsets into a string.

Keep in mind that:
1. each header might be a different charset (e.g. contain raw 8-bit text).
2. each mime part might be a different charset
3. there might be binary attachments w/o base64 encoding

UTF-8 won't be able to convert the raw message data into a string unless everything is either ASCII or UTF-8.

**Comment by tausi0661** [comment]
Thank you for your reply and it really helps.

Actually I found MimeKit from below link -- it described sample codes to using Gmail API and it used MimeKit instead of AE.Net.Mail because it supported HTML body better. So I guess there may be lot's of people using the method MimeMessage.ToString()  :P

http://jason.pettys.name/2014/10/27/sending-email-with-the-gmail-api-in-net-c/
