### ISSUE TITLE
Question; Is DeleteMessageAsync safe to use?

### ISSUE THREAD

**Issue by polterguy** [jstedfast/MimeKit#200]
Howdy,

I see you have marked "DeleteMessage" as obsolete, and the only alternative I can find is "DeleteMessageAsync". This raises the question of whether or not it is actually safe to use, since normally you'd use it inside of a "using (var client = new Pop3Client ())" type of statement ...?

Meaning, isn't it possible that my "client.Disconnect (true);" at the end of my using statement, or my using statement as a whole, would potentially finish what it is using, before "DeleteMessageAsync" is finished executing?

As in, potentially having the QUIT signal sent, client disposed, BEFORE the "DeleteMessageAsync" invocation is able to execute?

What would happen then? Wouldn't the "DeleteMessageAsync" invocation then try to delete over a released transport socket ...?
Raising (obviously) an exception I presume ...?

If so, how should I go ahead with making sure my "DeleteMessageAsync" is safely executed before end of "using" is reached, and client is disposed ...?

As a side note/question, if I fetch an indexed message, using "client.GetMessage (idxMsg)", would "client.DeleteMessageAsync (idxMsg)" delete the same message, or is the number incremented on the POP3 server, since I have fetched the "idxMsg" (integer) message already ...?

**Comment by polterguy** [comment]
BTW, sorry, this is actually a MailKit question I presume. Should I move it to MailKit's issue page ...?

**Comment by jstedfast** [comment]
The reason that DeleteMessage(string, ...) is obsolete is because I didn't want MailKit to have to track the mapping of UID to index. What you are meant to use instead is the DeleteMessage(int, ...) variant.

I'm assuming you want to make use of the UIDs, so what you'll want to do is something like this:

```csharp
var uids = client.GetMessageUids ();
for (int i = 0; i < client.Count; i++) {
    if (!MessageHasBeenDownloaded (uids[i])) {
        var message = client.GetMessage (i);
        // save it somewhere
        client.DeleteMessage (i);
    }
}
```

To answer your last question, yes, you would pass the same index value to both GetMessage() and DeleteMessage().

DeleteMessage() doesn't immediately delete the message on a POP3 server. What happens is that the protocol marks the message as deleted, but it's still actually there until you close the connection with a proper QUIT command (hence why the Disconnect method takes a bool 'quit' argument).

**Comment by polterguy** [comment]
Actually, my question was more of a "thread question".
Meaning, isn't it possible that client.Close() is executing before message deletion is complete, since there is only Async version of DeleteMessage ...?

Shouldn't there be a "DeleteMessage" which is NOT Async ...?

Thx though :)

**Comment by jstedfast** [comment]
Oh, yes, probably. I'm not an expert on async programming in .NET, but I suspect you'd have to `await` the DeleteAsync if you are doing it in a using block.

**Comment by polterguy** [comment]
Thx, done! :)
