### ISSUE TITLE
ReadNextMessage() - Out of memory exception

### ISSUE THREAD

**Issue by cashcache** [jstedfast/MimeKit#210]
This is a great library and I've had a lot of success using it.  However, one area that has caused an issue is when enumerating very large Mbox files.  It appears that your ReadNextMessage call tries to read all the contents of the file into memory instead of using the FileStream it was handed.  I suspect you are doing this for speed, but it would be nice to have another option for times like these.

Thanks!

**Comment by jstedfast** [comment]
The MimeParser never has more than a little over 4K in memory (4228 bytes).

I've parsed multi-gigabyte mbox files on my laptop with only 4GB of memory and it was fine. I've never gotten a OutOfMemoryException.

Once a MimePart is parsed, the MimePart.ContentObject will contain a MemoryBlockStream (a more efficient MemoryStream) that has the raw content of the MimePart in memory.

You can bypass this by using one of the MimeParser .ctors that take a `persistent` argument and passing the value `true`. This will make the MimePart.ContentObject's reference a substream of the FileStream instead of duplicating it into memory.

**Comment by jstedfast** [comment]
I should note that since the parsed MimeMessage structure references the FileStream, you should not dispose the FileStream until you are done with using the parsed message.

**Comment by jstedfast** [comment]
Oh, and by using `persistent:true`, the parser will actually be another ~10% faster or so... it depends on how large the content of your MimeParts are.
