### ISSUE TITLE
AuthenticationException on connecting to Outlook.com via POP3

### ISSUE THREAD

**Issue by dannyrosales** [jstedfast/MimeKit#217]
Tyring to connect to outlook.office365.com via POP3, go here for code details https://goo.gl/RQq9NV
Getting an exception on line 62. Can someone help me figure this out?

![pic_downloadmessageserror](https://cloud.githubusercontent.com/assets/426780/12195485/23cd0cd0-b5bd-11e5-9587-167c95fc92dc.png)

**Comment by jstedfast** [comment]
What you'll need to do is get a protocol log so that it's possible to diagnose what the problem is.

To do that, follow these instructions:

https://github.com/jstedfast/MailKit/blob/master/FAQ.md#ProtocolLog

FWIW, it would also help if, in the future, you submit SMTP, POP3, and IMAP issues to [MailKit](https://github.com/jstedfast/MailKit) so that I can more easily reference the issue #'s in my commit messages :)

(it seems most people submit bugs to the wrong issue tracker - mime bugs to mailkit and smtp/pop3/imap bugs to mimekit, I'm not sure why this is...)

**Comment by jstedfast** [comment]
I just took a look at my own logs connecting to Office365 and it first tries `AUTH PLAIN`, and, if that fails, it then tries the standard `USER` and `PASS` commands.

The only ways these would fail is if your user name or password is wrong.

(or, I suppose, if there is perhaps some configuration option on Office365 that you need to enable in order to connect via POP3).

I'm pretty sure you'll agree once you look at your own logs that this isn't a MailKit issue.

**Comment by jstedfast** [comment]
btw, you can disable `AUTH PLAIN` by doing:

```csharp
client.AuthenticationMechanisms.Remove ("PLAIN");
```

Maybe that will make a difference.
