### ISSUE TITLE
InternetAddressList.Parse

### ISSUE THREAD

**Issue by RFlipper** [jstedfast/MimeKit#233]
Hello, 

Firstly, let me say big thank you for the excellent library, I use it in my project and I'm very happy with it. 

Recently I noticed one little thing that InternetAddressList.Parse function can't parse email if it contains semicolon delimiter ';'. If I use comma or whitespace separator it works flawlessly. 
```
            var emailsStr = "user@domain.com;user2@domain2.com";
            var addresses = InternetAddressList.Parse(emailsStr);
```

I don't know exactly possible this is a not a bug, just a "feature", could you please clarify this.

**Comment by jstedfast** [comment]
The use of a ';' to separate addresses is invalid syntax, only a comma is allowed according to the specifications.

People get confused and think that a ';' is valid because the UI in Outlook allows you to use a ';' when entering addresses, but Outlook converts these into commas before serializing them to the actual message header.

Hope that helps clarify.
