### ISSUE TITLE
Maximum header length: misuse or bug?

### ISSUE THREAD

**Issue by kokosda** [jstedfast/MimeKit#236]
Hello,

Thank you for MimeKit lib! I chose it and MailKit because the last one supports immediate SSL connection and can be used with MailEnable server.

But I ran into issue yesterday. In short, if "List-Unsubscribe" header value length is greater than ~60 chars MimeKit (v. 1.2.22) appends CR LF (line break) right after header name which causes fail of DKIM check at GMail side. 

How I expect that string would look like:
`List-Unsubscribe: <mailto:customerservice@beta.flyerme.com?subject=unsubscribe>CRLF`.
How it looks like: `List-Unsubscribe: CRLF <mailto:customerservice@beta.flyerme.com?subject=unsubscribe>CRLF`.

I attached a sample of DKIM failed check to this post.
[dkim_fail.txt](https://github.com/jstedfast/MimeKit/files/223834/dkim_fail.txt)

DKIM signing is performed on the server side (by MailEnable). DKIM check is performed by GMail.
DKIM RFC4871 stated: The following header fields SHOULD be included in the signature, if they are present in the message being signed: List-Id, List-Help, List-Unsubscribe, List-Subscribe, List-Post, List-Owner, List-Archive.

Then 2nd issue. If the header value is longer than ~70-80 chars MimeKit transforms value completely. And the result is something like this: 
` =?us-ascii?q?=3Cmailto=3Acustomerservice=40beta=2Eflyerme=2Ecom=3Fsubject=3Dunsubscribe3?=
 =?us-ascii?q?46436346hrthrhr=3E?=`

instead of just heaving
`<mailto:customerservice@beta.flyerme.com?subject=unsubscribeblabla>`.

Note: `List-Unsubscribe` header can be longer than 70-80 chars (http://www.list-unsubscribe.com/) and can include not only `mailto` but `http`.

I use explicit cast from .NET MailMessage to MimeMessage. I suppose that issues can be a misuse of MimeKit lib. Sample of `BuildMessage` method shown below. Don't be confused with `HeadersWithEncoding`. The issues happen for both cases whether I use encoding for `List-Unsubscribe` or not.

	private static MimeKit.MimeMessage BuildMessage(EmailSettings settings)
	{
		var senderAddress = settings.SenderAddress.HasText() ? settings.SenderAddress : GetDefaultSmtpServer().SenderAddress;
		var senderName = settings.SenderName.HasText() ? settings.SenderName : ConfigurationHelper.DeliveryServiceFromName;
		var senderMailAddress = new MailAddress(senderAddress, senderName);
		var recipientMailAddress = new MailAddress(settings.RecipientAddress, settings.RecipientName);

		var message = new MailMessage(senderMailAddress, recipientMailAddress);

		if (settings.DeliveryNotificationOptions.HasValue)
		{
			message.DeliveryNotificationOptions = settings.DeliveryNotificationOptions.Value;
		}

		if (settings.Headers != null)
		{
			foreach (var kvp in settings.Headers)
			{
				message.Headers.Add(kvp.Key, kvp.Value);
			}
		}

		if (settings.ReplyToAddress.HasText())
		{
			message.ReplyToList.Add(new MailAddress(settings.ReplyToAddress));
		}

		if (settings.FilePathes != null)
		{
			foreach (var fp in settings.FilePathes)
			{
				message.Attachments.Add(new Attachment(fp));
			}
		}

		message.IsBodyHtml = settings.IsBodyHtml.HasValue ? settings.IsBodyHtml.Value : true;
		message.Subject = settings.SubjectLine;
		message.Body = settings.Body;

		var result = (MimeKit.MimeMessage)message;

		foreach (var a in message.Attachments)
		{
			a.Dispose();
		}

		foreach (var h in settings.HeadersWithEncoding)
		{
			var mimeHeader = result.Headers.FirstOrDefault(h2 => String.Compare(h2.Field, h.Item1, true) == 0);

			if (mimeHeader != null)
			{
				mimeHeader.SetValue(h.Item3, h.Item2);
			}
			else
			{
				result.Headers.Add(h.Item1, h.Item3, h.Item2);
			}
		}

		result.Body.ContentType.Charset = "UTF-8";
		
		return result;
	}

**Comment by jstedfast** [comment]
The MIME specifications state that long headers need to be wrapped. That's what MimeKit is doing. It is perfectly valid.

If GMail's DKIM implementation is not able to handle that, then that is a bug with GMail.

FWIW, the following header is 78 characters long:

`List-Unsubscribe: <mailto:customerservice@beta.flyerme.com?subject=unsubscribe>`

As you've discovered, when the header is really long and there is no white space at which to break the long line, MimeKit will use rfc2047 encoded-word tokens so that mail clients that properly decode the header will be able to get the original text exactly as it was before being encoded.

If, instead, MimeKit folded a long header by putting a CR LF in the middle of the text like so:

```
List-Unsubscribe: <mailto:customerservice@beta.fly
 erme.com?subject=unsubscribe>
```

Then it would be impossible to know if the original text was:

`List-Unsubscribe: <mailto:customerservice@beta.flyerme.com?subject=unsubscribe>`

or 

`List-Unsubscribe: <mailto:customerservice@beta.fly erme.com?subject=unsubscribe>`

because unfortunately the Message specification only says that to unfold a header, simply remove the CR LF. But without the extra space on the next line of a folded header, there'd be no way for the parser to determine that the next line is a continuation of the previous line.

**Comment by kokosda** [comment]
Hello, Jeffrey.

Thank you for your reply.

Now it is clear for me.

I ended up with such header value: 
`List-Unsubscribe: <mailto:abuse@beta.flyerme.com?subject=Unsubscribe>, <http://beta.flyerme.com/unsubscribe.aspx?s=1111&k=Aaaaa`

Each value is less than 78 chars and devided by ", ". It works and passed GMail DKIM check.

But I also investigated Github generated email when you closed this issue.
[github_close_email.txt](https://github.com/jstedfast/MimeKit/files/226083/github_close_email.txt)

Github uses following value:
`List-Unsubscribe <mailto:unsub+000e8cd9e75cc10035f7016e74adc28ad29e7436ec38501a92cf00000001132d0bc792a169ce08e3e472@reply.github.com>,CRLF
 <https://github.com/notifications/unsubscribe/AA6M2QpBo4DjzpOLQhYLPhZ7RlFGEi4Hks5p4-_HgaJpZM4IJuI8>CRLF`

And it is completely valid for GMail DKIM checker and no tokens are used.

**Comment by jstedfast** [comment]
So GMail doesn't follow the specifications :)

MimeKit is a lot stricter in what it sends.

**Comment by tordtons** [comment]
Hi,
I have a question related to this issue (although it has been closed). We use MimeKit to send EDI-messages over SMTP. The EDI-systems receiving our messages may or may not handle these RFC2047-encoded tokens correctly. Would it be an option to allow the maximum line length of headers to be configurable? Today it is locked to 78, but the RFC2822 spec states that:

> Each line of characters MUST be no more than 998 characters, and SHOULD be no more than 78 characters

So I guess it would make sense to have a default value of 78, but allow it to be increased up to 998. As far as I can see, this is already supported for the message body (through MimeMessage.Prepare()).

**Comment by jstedfast** [comment]
You can clone MimeKit and modify FormatOptions.MaxLineLength to be settable. Once you do that, it should mostly work.

I just don't want to make it publicly settable in released versions because I do not want people changing that value unless they absolutely know what they are doing. Also, I'm not sure that it is really a hard upper-limit (there may be a few corner cases where it is treated as a soft limit rather than a hard limit).
