### ISSUE TITLE
MimeParser won't parse UUEncode inline attachments (embedded in the body)

### ISSUE THREAD

**Issue by haykpetros** [jstedfast/MimeKit#242]
It seems that old systems (probably Unix of some sort) are using body to send attachments. From what I understand file content is encoded using UUEncode and then added at the end of Body with following structure:

```
begin 644 [Filename]
[Here comes encoded file content]
 
end

```
In such case parser won't parse attachments and Attachments collection will be empty.

I've verified that if content of above mentioned section is parsed manually, actual file content will be properly decoded (`attachment.ContentObject.DecodeTo(content);`). But I think regardless it is better if `MimeKit / MimeKit / MimeParser.cs ` is updated to properly handle this situation.

**Comment by jstedfast** [comment]
UU is not MIME and I have no desire to add this functionality. It also wouldn't make sense to treat it like MIME because it would just add awkward confusion.

e.g. Is this a real MIME part or is this some sort of frankenstein part that is not really a MIME part but just treated as a MIME part in MimeKit when in fact it's actually a UUEncoded blob in a text part?

These things matter to me and likely to other developers who want a MIME parser to give them a MIME tree structure and not some convoluted monstrosity that doesn't map to MIME on a 1:1 basis.

You are, of course, free to fork MimeKit and add this functionality yourself. I just have no interest in adding this to MimeKit myself.

**Comment by LeeBear35** [comment]
Back in the day, I worked with a system that would not take regular Mime attachments, but you could UU encode them and pass them through in the text body of the email. It seems that the recipients of the emails with the uuencoding attachment would receive it as a valid attachment at their end, which would have required their mail client to parse the text, but I would agree that it is not the norm and it is not part of the Mime standard. So this might be a hack just like it was for me back then.

**Comment by jstedfast** [comment]
I tried to provide the tools necessary for developers to decode UUEncoded attachments embedded in other MIME parts in MimeKIt, but the amount of processing that would be required for the MimeParser to detect and handle them would be enormous because they can appear literally anywhere (I've seen them in text/plain parts, in application/octet-stream parts, etc).

Then there's the problem of what if you have a text body like this:

```
This is some message body text...

blah blah blah...

begin 0644 attachment.dat
....
end

and some more message body text here...
```

How do you present that as a structure of MimePart objects?

Do you rip out the "attachment" and then pretend it never existed within the text/plain body part? Or do you split the text/plain body part into 2+ part? (e.g. the text *before* the attachment and the text *after* the attachment).

No matter which decision you make, I guarantee you'll make someone unhappy.

UU is just a mess.

**Comment by haykpetros** [comment]
I guess it is UUEncoded blob in a text part as it appears right after all the content. Basically it is part of MimeMessage.TextBody and that is how I parse it right now, though thought it will be better to have a hack inside the parser itself. It is true that this is probably very old system we are receiving Emails from, but still internet research shows that this is valid Email and all Email clients (Gmail etc. for example) are parsing it properly and showing attachments.

**Comment by haykpetros** [comment]
Well, if you ask me, then I would say parser should rip out "attachments" and then pretend it never existed within the text/plain body as that is how Gmail acts.

**Comment by jstedfast** [comment]
Okay, but the original message has the following MIME structure:

```
text/plain
```

And the munged MIME structure would be:

```
multipart/mixed
   text/plain
   application/octet-stream
```

Which of course does not map at all to the original message structure.

This becomes a nightmare to try and re-serialize and it confuses developers who expect the MIME structure.

There's no reason that MimeKit has to parse the uuencoded blobs. The client can do that all on its own after-the-fact.

In fact, every mail client I've ever looked over the source code for does exactly what MimeKit does.

They parse the MIME and then as they are rendering the message, they scan for UU-encoded blobs as a second pass.

**Comment by jstedfast** [comment]
To test my theory, you can simply connect to any IMAP server and see how its MIME parser deals with uuencoded blobs by requesting the BODYSTRUCTURE of the message :)

**Comment by haykpetros** [comment]
Well, I am not arguing that it is part of the MIME structure, as I am not a pro in this area. All I wanted to do is to bring this to your attention. ;)

I am currently parsing TextBody and creating `new MimePart("application", "octet-streams")` that is later added to Attachments, but thought it will be cleaner if the parse already does that one way or another.

But again, it is up to you. If I find a proper way to implement it myself, I will submit a Pull request, maybe.

**Comment by jstedfast** [comment]
I would argue that what you are doing is the right way to do it :)

**Comment by haykpetros** [comment]
Ok, then what you think will be the right way to parse out attachments? :)

**Comment by jstedfast** [comment]
The way you seem to be doing it already :)

**Comment by haykpetros** [comment]
Alright then. )
