### ISSUE TITLE
Invalid Characters In Base64 Encoded Attachment Of Composed Message

### ISSUE THREAD

**Issue by aluitink** [jstedfast/MimeKit#244]
I'm composing a MimeMessage that has an embedded message with inline attachments. The attachment is becoming corrupted and it appears to be due to this invalid character sequence in the base64 encoded data.

![image](https://cloud.githubusercontent.com/assets/3255752/15269740/3ad4bcd0-19c6-11e6-9b8d-17707511d108.png)

From what I can tell, everything before the sequence is valid, everything after that sequence is garbage.

If I ToString the message containing the attachment without attaching to another message it comes out clean.

**Comment by aluitink** [comment]
Seems to only happen when using .ToString() of a MimeMessage, looks good if I WriteTo

**Comment by jstedfast** [comment]
Is MimeKit what is doing the base64 encoding? Or is something else doing the base64 encoding? I ask because MimeKit should never produce something like that.

That said, the `ToString()` method is discouraged since it forces the entire message content into a single charset (which is probably what is causing this error if there are any control characters in base64 blob). It's mostly meant for debugging purposes so you can see what the raw message looks like in the debugger, but what I should probably do is use a DebuggerDisplayAttribute or something because a lot of people seem to assume that `ToString()` is the right way to write out a message.
