### ISSUE TITLE
Replace InternetAddressList.Mailboxes with IEnumerable<InternetAddress>.EnumerateMailboxes

### ISSUE THREAD

**Issue by rtlayzell** [jstedfast/MimeKit#273]
Hi, I wanted to make a small change but it breaks the public API and wondered how you felt about such changes.

The change is to replace the public property `InternetAddressList.Mailboxes` with an extension method `EnumerateMailboxes(this IEnumerable<InternetAddress> addressList)`. 

There are a few reasons why this is preferable, but I'm not sure the change is worth breaking existing code.

Thoughts?

(Could always deprecate `Mailboxes`)

**Comment by jstedfast** [comment]
What reasons do you have? Without knowing the reasons, I'd prefer the existing way over an extension method.

**Comment by rtlayzell** [comment]
- Applicability to _all_ collections of `InternetAddress`'s thus still usable when `InternetAddressList` is inevitably reduced to `IEnumerable<InternetAddress>`, say, via a LINQ expression.
- The intention is made clearer via a method and the name `EnumerateMailboxes` as opposed to a property `Mailboxes` which to me feels a little dishonest/misleading, when the property is in actual fact an iterator of sorts.  With this one it really depends on where you draw the line, properties should be inexpensive to get/set IMO.

**Comment by jstedfast** [comment]
1. meh... you could just use `list.Mailboxes` instead of `list` in your LINQ statement and accomplish the same thing.

2. I get what you're saying, but it's pretty convenient and not at all expensive.

If you had proposed this *before* I had added the Mailboxes property, I'd probably go with the extension method, but this late in the game, the reasons for changing aren't compelling enough for me to break existing code.

There's honestly a lot of changes I'd like to make that I think are more compelling but I'm not doing because of the real possibility of breaking code.

**Comment by rtlayzell** [comment]
That is what I thought.. oh well.
