### ISSUE TITLE
How to get message identifier by unique identifier?

### ISSUE THREAD

**Issue by AlexGeller** [jstedfast/MimeKit#275]
Hi,

I get all message id by pop3client's method GetMessageUids(), and get all messege identifier in a list. then I want to known get the unique identifier by the message identifiter in the list.

Secondly, if one program delete one email, is the unique identifier that other program's got before deleted will be changed?

Alex.

**Comment by jstedfast** [comment]
I don't really know what you mean by 'message identifier'. Do you mean the message *index*?

Here's how you are meant to use the uids returned by `GetMessageUids()`:

```csharp
IList<string> uids = client.GetMessageUids ();
for (int i = 0; i < client.Count; i++) {
    string uid = uids[i];

    // Check if you've already downloaded the message by looking up the uid in your database...
    if (YouHaveAlreadyDownloadedThisMessage (uid))
        continue;

    // Download the message...
    MimeMessage message = client.GetMessage (i);
}
```

If another client deletes a message, the uids will not change for either client. The *list* of uids returned will be different the next time you `Connect()` and `Authenticate()`, because the uid belonging to the message that got deleted will no longer be in the list, but that is the only change you can expect to be there.

Hope that helps.
