### ISSUE TITLE
Sample usage of MimeKit (and MailKit)

### ISSUE THREAD

**Issue by polterguy** [jstedfast/MimeKit#293]
Howdy Jeff, long time :)

Sorry if this is a shameless plug, but I thought you'd enjoy seeing your baby fly ;)

https://www.youtube.com/watch?v=_hRZnQCCKyY

Here how it works

https://www.youtube.com/watch?v=lzRJGU2UrT0

PS, I made it in 5 days (thx to your brilliant libraries, and P5's marvelous Hyperlambda)

It's 3800 lines of code, but after stripping away the comments and spacing, I guess you're left with about 700 lines.

I think it uses most "edge cases" in MimeKit, and takes advantage of the "full shebang", more or less ...

PS!
How's it working for Microsoft ...?
You guys were purchased a couple of months ago, right ...?
What's the future plan for your project under Microsoft ...?

Yet again, thx for a freakin' **brilliant** library, there's simply no competition out there, believe me, I have looked ... ;)

You definitely the *mailman* :D

**Comment by polterguy** [comment]
Here's the project, if you'd like to check out its code ...

https://github.com/polterguy/sephia-five

**Comment by jstedfast** [comment]
Wow, pretty cool!

Yea, Microsoft announced the acquisition about a year ago actually - but we officially became part of Microsoft back in July. Working for Microsoft has been pretty good so far, no complaints here. Pay is better :)

No problem, glad to provide a good quality mail library with crypto support especially as cryptography becomes more desirable.

One of the things I'm doing now is working to bring my [gmime](https://github.com/jstedfast/gmime] C library up to par with MimeKit. One of the main focuses has been PGP (gmime has always had PGP support, technically, but I've switched to libgpgme) and S/MIME support.

I want to help the Notmuch and Balsa developers make their clients even better. The Notmuch guys, in particular, have been asking me about S/MIME support and were providing patches to improve PGP support.

**Comment by polterguy** [comment]
Re; "One of the things I'm doing now is working to bring my gmime C library up to par with MimeKit"

Hehe, such a funny quote that is, once you realise gmime is actually C and MimeKit is C# ... ;)

Out of curiosity, isn't really PGP the superior cryptography standard here ...? (compared to S/MIME)

Glad to hear about your salary, you deserve every penny :)

**Comment by jstedfast** [comment]
MimeKit was originally going to be a C# "port" of GMime... but some things weren't easy to port directly to C#, so I had to redesign some stuff which at first was annoying, but I actually improved the design and now I'm porting a lot of those design changes back to GMime :)

PGP and S/MIME are both good crypto standards and both have pros & cons.

The advantage (and disadvantage?) of S/MIME is that you have a central authority for trust. S/MIME relies on CA's being ultimately trustworthy (and fortified against hackers) and that is not really a guarantee in this world. The safeguard (in the case of hackers) is that the CA is supposed to revoke certificates if they discover they've been hacked... but what if they don't spot this?

PGP has a distributed "web of trust" that can work well, but you have to have users who understand how that works which is a bit more complicated. Signing other user's keys is also one of those things where you might need to meet (and know!) someone personally to verify their PGP fingerprint before signing it with your key (as we know, emails and other things can be spoofed if you don't know someone's PGP keys before-hand).

Another advantage that PGP has is that you can create your own PGP keys and upload them to pgp.mit.edu or whatever key server you prefer to use which is arguably simpler than having a commercial Certificate Authority create a certificate/private key for you (and safer? since if a CA creates them for you, then they technically have access to your private key).

However, a PGP key by itself is not nearly as valuable as a PGP key that has been signed by people you trust (and by trust, it means that you trust they don't go signing other people's keys that they haven't verified really belong to said person).


I'm personally undecided in which I prefer. In many ways I like PGP more because of its "openness" but I find that S/MIME is more practical to use as long as you trust that your CA (or hackers that may have compromised said CA) didn't keep a copy of your private key when they generated it for you.

I suspect that if I ever switch to using encrypted email, it will be between me and people I know personally and so signing their keys won't be an issue, thus making PGP perfectly reasonable to use.

I think that corporations prefer S/MIME because it's simpler for their employees to use and they can serve as the company-wide central CA if they want.

**Comment by polterguy** [comment]
Interesting thoughts, I am fundamentally sceptic to trusting companies, who charge money for "selling their trust" though, which I guess explains my bias towards PGP :)

I've seen several people in security conferences lately, arguing against CA, at a general level. These were in regards to SSL though, but I think the same arguments applies to S/MIME. Though I see your point about having your employer being the CA, significantly easing the process, while still retaining the trust level necessary. You wouldn't happen to have data in regards to what companies out there actually chooses ...?

I was wanting to go with "pure PGP", but you kind of made me change my mind, wanting to deliver "both" ... :)

**Comment by jstedfast** [comment]
Yea, I'm kinda biased in favor of PGP as well, but still fairly "center" (PGP-of-center?).

Security experts at conferences probably know way better than me, so I'd take their opinions more seriously than mine :) And yea, it affect S/MIME as much as SSL.

I do not have any real data, unfortunately :(

It's good to support both.

**Comment by polterguy** [comment]
Thx :)
