### ISSUE TITLE
Release of MimeKitLite Nuget package targetting NetStandard

### ISSUE THREAD

**Issue by ctolkien** [jstedfast/MimeKit#295]
As per title - currently we can't use the MimeKitLite package in NetStandard apps (without doing target fallbacks, etc), whereas we can for the "full" MimeKit lib as it targets as it targets NetStandard1.3

**Comment by jstedfast** [comment]
I've actually been considering dropping MimeKitLite altogether due to what appears to be fairly low interest.

Is there a reason you don't want to use the full package?

Originally MimeKit depended on SQLite which is what everyone seemed to want to avoid, but it no longer depends on it and hasn't in over a year.

**Comment by ctolkien** [comment]
>Is there a reason you don't want to use the full package?

Well, basically I only needed the `MimeMessage` and `MailboxAddress` types, so I figured the 'lite' version would be the way to go, but there's no real issue with using the "full" package.

**Comment by jstedfast** [comment]
I actually just migrated the netstandard1.3 MimeKit project to VS2017's project format which is a heck of a lot simpler than the hoops I had to jump thru for VS2015, so I can look into adding netstandard1.3 support for MimeKitLite for the next release.

**Comment by jstedfast** [comment]
Just added a MimeKitLite.NetStandard.csproj and updated the MimeKitLite.nuspec to include the netstandard1.3 assemblies.

**Comment by jstedfast** [comment]
I'm hoping to make a 1.14 release of MimeKit and MailKit next weekend or so. I want to finish up a few other things first.

**Comment by StefanBertels** [comment]
Just a note: Just stumbled upon (namespace) conflict between MimeKit and MimeKitLite because my main project uses MimeKit and a referenced (own) package uses MimeKitLite.

I found this issue and after reading that you might drop MimeKitLite, I will just change to MimeKit.
Maybe another reason to drop it (or is there a workaround)?
