### ISSUE TITLE
x.400 Addresses

### ISSUE THREAD

**Issue by LeeBear35** [jstedfast/MimeKit#299]
Jeffery,
Congratulations on the MS deal...I have a number of client emails from systems where the addresses are in x.400 format, and I can get at the headers, but was wondering if you had anything in place to deal with those types of addresses. I have included an example header:

From: "Dewey Howe"  </O=HOWE/OU=EXCHANGE ADMINISTRATIVE GROUP 
 (FYDIBOHF23SPDLT)/CN=RECIPIENTS/CN=DHOWE1234>
Subject: Hiya
Date: Mon, 30 Mar 2015 13:19:15 +1100
Content-Type: multipart/mixed; 
 boundary="----=_NextPart_1442853594-565636025-48136249"
MIME-Version: 1.0
To: "Ben.Dover@DrInn.com"  <Ben.Dover@DrInn.com>

**Comment by LeeBear35** [comment]
Some further information, it seems if the address is x.400 format with spaces then it will not be returned in the parsed From collection, but if it does not contain spaces then it is returned, like this example:

HDR From: "Jackie Healing"  </O=COLON/OU=CENTRAL/CN=RECIPIENTS/CN=JHEALING>
	From_0: "Jackie Healing" </O=COLON/OU=CENTRAL/CN=RECIPIENTS/CN=JHEALING>

**Comment by jstedfast** [comment]
Yea, it's because that address format is invalid for email as defined by internet standards.

I'm not sure what to do about X.400 address syntax because it's invalid and you can't really do anything with it per se. You certainly can't try using that address with SMTP, for example.

I'm thinking I'd rather just not do anything and say "not supported".
