### ISSUE TITLE
"From now on you can access your personal space...." text causes "Failed to parse message headers." exception

### ISSUE THREAD

**Issue by betrakiss** [jstedfast/MimeKit#345]
I have been crawling my mail, generated from Thunderbird INBOX file and in one of my accounts I got FormatException: "Failed to parse message headers.", which makes it impossible to keep crawling, because of "Failed to find mbox From marker." exception after it.

When the exception occurs the MboxMarker is at "From now on you can access your personal space in any web browser by".
I don't know the details of the mbox parsing, so please excuse me if it's something I'm not doing right.

I have cut a portion of the mbox file that causes the error.
[mbox.txt](https://github.com/jstedfast/MimeKit/files/1358770/mbox.txt)

Also, I am using the following code:
```
           using (FileStream stream = new FileStream(@"mbox.txt", FileMode.Open))
           {
                MimeParser parser = new MimeParser(stream, MimeFormat.Mbox);
                MimeMessage current = null;
                while (!parser.IsEndOfStream)
                {
                    try
                    {
                        current = parser.ParseMessage();
                        
                    }
                    catch (Exception e)
                    {
                        
                        continue;
                    }
                }
            }
```

Is there some setting that I'm missing or a way around this exception, so I can keep crawling the rest of the mail?
Thank you

**Comment by jstedfast** [comment]
The mbox format uses lines beginning with "From " (From + space) to delineate messages. All messages that have text bodies that include lines beginning with "From " are supposed to be munged by placing a '>' character at the start of said line(s).

This suggests that your mbox file is corrupt which is why MimeKit cannot parse it.

You might be able to work around it by doing something like this:

```csharp
using (FileStream stream = new FileStream (@"mbox.txt", FileMode.Open)) {
    MimeParser parser = new MimeParser (stream, MimeFormat.Mbox);
    MimeMessage current = null;

    while (!parser.IsEndOfStream) {
        try {
            current = parser.ParseMessage ();
        } catch (FormatException e) {
            // Reset parser state and continue parsing from the current stream position
            parser.SetStream (stream, MimeFormat.Mbox);
            continue;
        }
    }
}
```

**Comment by betrakiss** [comment]
Thank you for the quick response. Setting the stream again does the trick and now I'm back to full power!

Also, I have deleted the mbox file and redownloaded all the mail. The error still persists with the new mbox file. Maybe it's an issue with how thunderbird formats the mail?

Have a nice day.

**Comment by LeeBear35** [comment]
There are no strict RFC standards for MBOX, there are three common ways to handle the From inside the email when it starts at a line break. One of the best checks for improper munged lines is to check the following:

- Line starts with From
- Followed By a space
- Followed by a proper address containing an ampersand

Right now because of the FormatException that email is not processed when it could be processed.

**Comment by jstedfast** [comment]
This blog post by Jamie Zawinski (of Netscape Mail fame) is pretty enlightening: https://www.jwz.org/doc/content-length.html

Note that, because mbox is not standardized, you cannot rely on the second token being formatted as an address. You simply can't.

That said, if Thunderbird really is using Content-Length, then you can use a custom `ParserOptions` with the `RespectContentLength` property set to true: http://www.mimekit.net/docs/html/P_MimeKit_ParserOptions_RespectContentLength.htm

**Comment by jstedfast** [comment]
> This From only has 1 newline before it, but was treated as a marker anyway. Is this intentional?

Yes, because unfortunately sometimes there really is no extra blank line before the mbox marker of the next message.

Have you tried using the RespectContentLength option in ParserOptions?

**Comment by yoraaf** [comment]
Thank you for the response!
Unfortunately the data I'm dealing with doesn't have a Content-Length header. But it does seem to consistently use `\n\nFrom ` so I might just regex replace it with `\n\n>From ` before putting it through the parser. Any other suggestions would also be appreciated
