### ISSUE TITLE
Image in multipart/related parsed as TextPart

### ISSUE THREAD

**Issue by chickenpotpie** [jstedfast/MimeKit#349]
When a message is parsed, if the child of a multipart/related does not have a Content-Type header it gets a default ContentType of "text/plain" and is parsed as a TextPart. In a message that I'm parsing the child is actually a base64 encoded jpeg image. Why the default to "text/plain"?

`--d0f6df7175fc40748e1ae25880ff4cf2
Content-Type: multipart/related; boundary="3b109f4194464f0ead3a0236b0b07ffc"

--3b109f4194464f0ead3a0236b0b07ffc
Content-Type: text/html; charset=UTF-8
Content-Transfer-Encoding: quoted-printable

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"><html><head>=
body here

--3b109f4194464f0ead3a0236b0b07ffc
Content-Id: 0.28873821780.7456941219435012098.15ee7cb3e40__inline__img__src
Content-Disposition: inline; filename="1.jpg"
Content-Transfer-Encoding: base64
`

**Comment by jstedfast** [comment]
It defaults to text/plain because that's what the specs say to do when a Content-Type header is absent.

https://github.com/jstedfast/MimeKit/blob/master/rfc/rfc2045.txt#L735

This definition is further expanded in the following specification, here:

https://github.com/jstedfast/MimeKit/blob/master/rfc/rfc2046.txt#L1079

```
   If no Content-Type
   field is present it is assumed to be "message/rfc822" in a
   "multipart/digest" and "text/plain" otherwise.
```

In other words, if the parent type of the MIME part without a Content-Type header is "multipart/digest", then the Content-Type for the MIME part without a Content-Type header should be assumed to be "message/rfc822". For every other parent type, it is assumed to be "text/plain".

**Comment by chickenpotpie** [comment]
Perfect. Thanks.
