### ISSUE TITLE
multipart message with plain text prefix before mutltipart/alternative body part

### ISSUE THREAD

**Issue by stylefish** [jstedfast/MimeKit#353]
Hi,
i'm facing an issue with a mail sent from a novell groupwise server wich prefixes the "multipart/alternative" message with a "text/plain" part which contains "this is a multipart message" like this:

```
[...other headers...]
Content-Type: text/plain;
	charset="iso-8859-1"
Content-Transfer-Encoding: 7bit
X-Mailer: Novell GroupWise Internet Agent 14.2.1=20

This is a MIME message. If you are reading this text, you may want to=20
consider changing to a mail reader or gateway that understands how to=20
properly handle MIME multipart messages.

--=3D__PartF0C85851.0__=3D
Content-Type: multipart/alternative; boundary=3D"=3D__PartF0C85851.1__=
=3D"

[...text/plain and text/html contents...]
```

i've attached a sample project (which only loads a _cleaned version_ no real email addresses and content of the original eml file and iterates the body parts):
[ConsoleApp14.zip](https://github.com/jstedfast/MimeKit/files/1446590/ConsoleApp14.zip)

```csharp
var message = MimeMessage.Load("groupwise.eml");
foreach (var bodyPart in message.BodyParts)
{
	Console.WriteLine(bodyPart.ContentType);
}
```

in this case i would expect that the BodyParts property of MimeMessage contains all message parts but it only prints out "text/plain". in the text/plain body part contains the complete "unparsed" email.
my mail client (thunderbird) displays the mail in html. 

my question is: how to get the html body part from such a message, so any help is much appreciated. :)
thanks

**Comment by jstedfast** [comment]
You can't. Groupwise is telling you that this message is text/plain and has no other MIME parts at all. You might look at the content and think "well, yea, but it has a multipart/alternative in there... so that's not true!" but you'd be wrong. Inside a text/plain part, the content is free-form text and could contain anything, even stuff that looks like headers or multipart boundaries. It doesn't matter, you can't parse that and expect to get anything out of it.

From looking at it, it didn't even specify the Content-Transfer-Encoding correctly (it claims 7bit, but it's actually quoted-printable... hence all of the =3D's in the text).

If you want to write some custom code to specifically handle this particular message, you could try... but you won't find a general solution if Groupwise does this often.

The first thing you would need to do is decode the quoted-printable content. Then you would need to seek past the line containing `--=__PartF0C85851.0__=`. Then you could pass the stream off to MimeKit's parser and hope you get something useful out of it.

(you might also want to chop off the `--=__PartF0C85851.0__=--` at the end of the text as well).

**Comment by stylefish** [comment]
yeah, thats what i'd expected... 
i'll request some more messages from this strange server and see if i can work out a pattern (e.g. X-Mailer is Groupwise and XYZ etc) and will then decide if its somewhat realistic to implement kind-of reliable custom logic to support this mess. would you be interested in the code if i'll go that way?
anyway, thanks for your quick answer and the information how to implement this :)

**Comment by jstedfast** [comment]
Probably not. I doubt any solution you find will be generically useful and not a hot mess (that's not a knock on your ability as a programmer at all, it's just the nature of this type of thing - even "simple" workarounds get messy quickly from my own experiences writing work-arounds for broken mail software).

That said, if you do come up with a solution, you are free to post a link to it here in case anyone else stumbles upon this discussion and finds your solution useful. I will also point people to your solution if anyone else comes to me with a similar problem and doesn't see this discussion.

As an aside, the `--=__PartF0C85851.0__=` value is randomly generated and so is likely to be different each time which makes this a royal PITA to deal with in any sort of generic robust way.

Maybe you could use a regex of `"\n--=__Part.*__="` (my regex fu is pretty weak, so don't quote me on it!) then capture whatever the `.*` captures and from there you could construct the end boundary (same as the begin boundary but with `--` appended to the boundary string).
