### ISSUE TITLE
Verifying SMIME Message Without CA Root Info

### ISSUE THREAD

**Issue by PranavSah** [jstedfast/MimeKit#356]
I am new to MimeKit and SMIME. I have been given a SMIME  signed file to verify. Every time i try to verify the same it gives me a Chain Exception as "non-empty set required Parameter name: value." 
Stack Trace leading to  at Org.BouncyCastle.Pkix.PkixParameters.SetTrustAnchors(ISet tas).

On debugging it does shows me details of the Issuer but the Chain object is "null".

The Signer of the file have told me that they use OPENSSL and use NoVerify option to stop verifying the root certificates. 

Earlier, on checking the certificate in windows it was telling me that "Windows dose not have enough information to verify the certificate".
After installing there Issuer certificate in my trusted store now the message has changed to  
This certificate is intended for the following purposes :
"Proves your identity to a remote computer"

My questions being. a) Is there some thing wrong with the signer's certificate.
                                 b) Do we have any option in MimeKit where in we can stop verification of Chain Certificates.
                                 c) Or is it something totally different.

**Comment by jstedfast** [comment]
The relevant code that you will want to play with is [BuildCertPath()](https://github.com/jstedfast/MimeKit/blob/master/MimeKit/Cryptography/SecureMimeContext.cs#L738) in SecureMimeContext.cs:738

To answer your questions:

a) not necessarily
b) not currently, but I would be willing to accept patches to allow it
c) not verifying the chain seems rather pointless to me since the whole point is to verify that the certificate isn't a forgery and not just verify that the signature was made with the (potentially forged) certificate

**Comment by jstedfast** [comment]
BTW, you can use the `WindowsSecureMimeContext` if you have imported the intermediate/root certificates into the Windows certificate store.

I'm guessing that you are using the `DefaultSecureMimeContext` instead?
