### ISSUE TITLE
Exception when parsing email

### ISSUE THREAD

**Issue by riyadparvez** [jstedfast/MimeKit#363]
MimeKit can't parse email when the To field is empty and BCC field is populated. I believe exception occurs when parsing this line `To: undisclosed-recipients:;`. This happens with Gmail.

> Exception: MimeKit.ParseException: Group address token at offset 0
>    at MimeKit.InternetAddress.TryParse(ParserOptions options, Byte[] text, Int32& index, Int32 endIndex, Int32 groupDepth, AddressParserFlags flags, InternetAddress& address)
>    at MimeKit.MailboxAddress.Parse(ParserOptions options, String text)

The file is attached.

[original_msg.txt](https://github.com/jstedfast/MimeKit/files/1568682/original_msg.txt)

**Comment by jstedfast** [comment]
I don't get any exceptions parsing the message. What version are you using?

**Comment by riyadparvez** [comment]
Okay, I think the issue is not with the MimeKit, rather with the dot-net core framework.

**Comment by jstedfast** [comment]
Never mind, the problem is that you are trying to do `MailboxAddress.Parse ("undisclosed-recipients:;")` which, of course, will not work.

I thought you were trying to parse a message and getting that exception.

For that string, you need to use `GroupAddress.Parse ("undisclosed-recipients:;");` or the generic `InternetAddress.Parse ("undisclosed-recipients:;");`

`MailboxAddress.Parse()` can only parse *mailbox* addresses, not *group* addresses.

**Comment by jstedfast** [comment]
Why are you doing that anyway? The parsed `MimeMessage` will give you the list of `InternetAddress` objects in the `To`, `Cc`, and `Bcc` properties.

**Comment by riyadparvez** [comment]
Thanks a lot! Yes, that fixed the issue.
