### ISSUE TITLE
dotnet 3.5 build?

### ISSUE THREAD

**Issue by coderb** [jstedfast/MimeKit#375]
any chance i can convince you to add a dotnet 3.5 build?

i need it because i am trying to deploy some code on exchange 2010.

i'm hacking around now and it seems like the approach would be to move the async code into seperate files (partial classes) and exclude them from the build.

if you want, i could work on a patch, but i haven't work on this codebase and the build setup looks like it supports a ton of configurations, most of which i'm not equipped to test.

thoughts?

**Comment by jstedfast** [comment]
You could use the MimeKit 1.22 release which supports .NET 3.5, but I've dropped support for it in 2.0 because 3.5 is so ancient I figured no one used it anymore.

The main difference between 1.22 and 2.0 is that 2.0 revamped the S/MIME support (as well as adding some additional async APIs, mostly to the crypto stuff).

1.22 had some async APIs, they were just #if'd out.

If they were to be added back, that's how I'd want it done again but I don't think it's really worth the effort since I can just point those developers to 1.22.

**Comment by coderb** [comment]
hey, that works for me!

believe me, if i could be off .net 3.5 i would but it will probably be at least 2 more years (exchange 2010 is slated for end of life 1/2020). :-(.

**Comment by coderb** [comment]
should i be able to install MimeKitLite 1.22 under dotnet 3.5 via nuget?

MimeKit 1.22 does work, but includes BouncyCastle dependency which may or may not cause me an issue but I'd rather exclude if possible.

thanks.

**Comment by jstedfast** [comment]
yea, MimeKitLite 1.22 should also work and doesn't need BouncyCastle.
