### ISSUE TITLE
ContentTransferEncoding / MimeMessage.Prepare

### ISSUE THREAD

**Issue by 304NotModified** [jstedfast/MimeKit#392]
@jstedfast

Could you please elaborate on your comment? (https://github.com/jstedfast/MimeKit/pull/390#issuecomment-381343974)

I think is useful outside my PR, so therefor a new issue

> The way I advocate for setting the Content-Transfer-Encoding is via the use of message.Prepare (EncodingConstraint.Value).
> 
> Granted, it seems that the BodyBuilder.Attachments.Add() logic sets a Content-Transfer-Encoding, but this is an artifact of a time before I had written `MimeMessage.Prepare()`.

The `MimePart.ContentTransferEncoding`  supports the following formats: 

-    Default,
-    SevenBit,
-    EightBit,
-    Binary,
-    Base64,
-    QuotedPrintable,
-    UUEncode,

while the  `MimeMessage.Prepare()` only supports the following modes:

-   None,
-   EightBit,
-   SevenBit,

With the  `MimeMessage.Prepare()` , I don't have control if e.g. Base64 or QuotedPrintable is used? It that recommend? How do I know which transfer encoding is used? 

Other related questions:

- could I combine `MimePart.ContentTransferEncoding`  and  `MimeMessage.Prepare()` , or should I use one of them. (FYI, http://www.mimekit.net/docs/html/Frequently-Asked-Questions.htm#CreateAttachments shows using ContentTransferEncoding)
- If I set the  `MimePart.ContentTransferEncoding`, should I encode it by myself or does mailkit handle that? 
- Is it required to call `MimeMessage.Prepare()` just before send, or could i call it earlier? (cannot find that in the docs)

Thanks in advance! Maybe we could add these things to the docs, are some (xml) docs are a bit unclear

**Comment by jstedfast** [comment]
The `Prepare` method only needs an encoding constraint of 7bit, 8bit, or none because the constraint refers to the limitations of the transport mechanism. If the SMTP server, for example, only supports 7bit, then you would use `EncodingConstraint.SevenBit`. If it supports the `8BITMIME` extension (signifying that it supports 8bit text), then the constraint would be `EncodingConstraint.EightBit`. In the rare case where the SMTP server supports the `BINARYMIME` extension, there is no constraint, so you'd use `None`.

The `Prepare` method will traverse the entire MIME structure and set an encoding on each part (if it is appropriate to do so).

You can't specify base64 vs quoted-printable, but then again, why would you care about doing that? Don't you trust MimeKit to do the right thing?

Let me ask you this: when was the last time any mail client you used asked you how to encode your attachments and/or message body? Never? 20+ years ago, at best? I'll let you ponder this question a moment after which I'm sure you'll reach the conclusion that I'm right :)

As for your other questions:

- You can use either method. If you explicitly set an encoding and then call `Prepare()`, the `Prepare()` logic will not override the encoding that you previously set. Since 90% of attachments should realistically be encoded as base64 anyway, it really saves time by just setting them to base64 from the start.
- Setting the `MimePart.ContentTransferEncoding` property changes the encoding of the content when the `MimePart` gets written to a stream. No need to encode the content yourself.
- There's a half-second timer on the `Prepare()` method's changes, if you don't send it within that window of time, all is lost. *Humanity* will be lost. This is why you must call it immediately before sending, but absolutely no earlier. I figure a half a second should be plenty of time.

**Comment by jstedfast** [comment]
In all seriousness, though, it's not even necessary to call `Prepare()` yourself if you are using MailKit to send the message via SMTP since the `SmtpClient` will call `Prepare()` for you with the appropriate arguments.

There are only a few situations in which you need to concern yourself with calling `Prepare()`:

1. You are going to DKIM-sign the message before sending it via SMTP.
2. You are going to append it to an IMAP folder (and you might not even need to concern yourself here, but it may still be a good idea to do so).
3. You want to save the message to some location before sending it and expect that the saved content will exactly match what was sent via SMTP.

You can also call Prepare() each time you add another MimePart to the MIME message structure (altho this would probably be inefficient).

If you are asking if you need to call Prepare() again after changing the To/From/Cc/Subject/Etc headers, the answer is no. Message headers are not affected by the Prepare() method nor are any MimePart headers (other than the value of the Content-Transfer-Encoding header, obviously).

**Comment by 304NotModified** [comment]
Thanks for the replies!


> You can't specify base64 vs quoted-printable, but then again, why would you care about doing that? Don't you trust MimeKit to do the right thing?

That's not the case, MailKit/MimeKit looks very solid. I'm replacing a current implementation with MailKit/MineKit and end-users could configure base64/QuotedPrintable etc.

**Comment by jstedfast** [comment]
In general, there are a few rules which make deciding between quoted-printable and base64 trivial:

1. if the content contains the 0-byte, then you need to use base64 (i.e. images and other binary data all contain 0-bytes).
2. for textual data, use quoted-printable unless > 17% of the characters need to be hex-encoded at which point it not only becomes unreadable anyway, it also becomes more efficient (space wise) to use base64.

Having users decide which encoding to use is almost guaranteed to cause problems unless your users are MIME experts (and I would expect that to be rare).

Since your original question about this started with the BodyBuilder class, I should note that the BodyBuilder class is more of a convenience thing for building message bodies with the most common structures. If you already understand how to property construct message bodies with the appropriate uses of multipart/related, multipart/alternative and multipart/mixed, then there's no reason to use it. You can simply combine parts in any way you want to and have full access to setting the ContentTransferEncoding values.

Even when using the BodyBuilder class, what you could do is this:

```csharp
var bodyBuilder -= new BodyBuilder ();
// construct the body...
message.Body = bodyBuilder.ToMessageBody ();
message.TextBody?.ContentTransferEncoding = ContentEncoding.Base64;
message.HtmlBody?.ContentTransferEncoding = ContentEncoding.Base64; 
```

Hope that helps.
