### ISSUE TITLE
Question about PGP signatures

### ISSUE THREAD

**Issue by polterguy** [jstedfast/MimeKit#405]
Sorry if you have given me an answer about this previously, but if a PGP part is cryptographically signed with a private PGP key, and the key is expired. What would `Verify` return?

Would it still verify the signature, assuming the signature is valid, although signed with an expired key ...?

And, I assume your new KeyServer feature will be automatically invoked, downloading the public PGP key from the configured server, if I invoke `Verify` for a signature where I don't have the public PGP key, right ...?

**Comment by jstedfast** [comment]
I assume you mean the Verify() method on the `IDigitalSignature` (implemented by the `OpenPgpDigitalSignature` class)?

I think that will still return true as long as the signature was made during the period in which the key was valid. I'm not 100% sure though since this is something that is handled within BouncyCastle and their documentation is very spotty. It's not something I have personally tested. If you find out, let me know, and I'll add it to the docs.

For the key server thing, yea, it will automatically download them in `OpenPgpContext.Verify()`.

**Comment by polterguy** [comment]
Thx :)

Psst, do you use some sort of `ServerCertificateValidationCallback` in MimeKit? The reasons I am asking is because I am fiddling with my own HTTP REST request parts today, and these parts are tricky to get right, while also not opening up for (unconsciously) accepting _"Man In The Middle"_ fake SSL certificates ...

Such callbacks would be invoked if the URL to the KeyServer is an HTTPS/SSL address for instance.

In fact, if you don't, I would prefer that, since it allows me to implement my own global callback, which I already have some code I could use.

**Comment by jstedfast** [comment]
I do not implement that callback anywhere in MimeKit for precisely that reason :)

**Comment by polterguy** [comment]
Awesome, at which point I'm free to implement anyways I see fit as a global callback :)

Thx, just checking ... ;)

I'm going through security things in P5 now as a regular fascist ... ;)
