### ISSUE TITLE
Сonflict between MimeKit and MimeKit.Light

### ISSUE THREAD

**Issue by v-ermolaev** [jstedfast/MimeKit#423]
I tried to use two nuget packages in my project.  First    WireMock package (https://www.nuget.org/packages/WireMock.Net/) used MimeKit.Light.  Second MailKit 
 package (https://www.nuget.org/packages/MailKit/) used  MimeKit. All namespaces and class names are the same. As a result, I could not use these two packages in one assembly

The type 'MimeMessage' exists in both 'MimeKit, Version=2.0.0.0, Culture=neutral, PublicKeyToken=bede1c8a46c66814' and 'MimeKitLite, Version=2.0.0.0, Culture=neutral, PublicKeyToken=bede1c8a46c66814'

I think that with the growing popularity of these packages, such conflicts will be more and more. Is it really impossible to change  namespace for MimeKit.Light?

**Comment by jstedfast** [comment]
I would suggest making a custom build of WireMock to use MimeKit.

if I change the namespace of MimeKitLite, it'll break everyone.

**Comment by springy76** [comment]
"wontfix"???

What speaks against a MimeKitCore lib which both MimeKit and MimeKitLite depend upon?

I made a small netstandard lib which only needs very basic functionality, so I decided to use MimekitLite since the footprint should be kept small for all consumers of this lib since it might be used inside a Blazor app (Monoruntime running on WASM in browser).
Now I can't use this lib in a mailer app which additionally needs MailKit.

Your libs are officially recommended by Microsoft and the .NET Foundation stands behind these projects. Just telling "wontfix" IMHO is definitely not the way to go for such projects.
