### ISSUE TITLE
HTML body is treated as an attachment when converted from TNEF

### ISSUE THREAD

**Issue by ymassad** [jstedfast/MimeKit#435]
I am using TnefPart.ConvertToMessage to convert a TNEF message to Mime.

The html body content type looks like this (this is the result of conversion):

Content-Type: text/html; name=body.html; charset=windows-1252

When the message is opened in outlook, the message contains no body, but there is a body.html attachment that contains the body.

If I remove 'name=body.html' from the content-type manually, the html body shows in outlook correctly.

Should outlook know to display the html body correctly even if it has 'name=body.html'? Or should MimeKit not put 'name=body.html' into the content-type?

**Comment by jstedfast** [comment]
Outlook should know better.

The name parameter has no bearing on whether something is supposed to be treated as an attachment or not according to the email specifications. The only thing that *does* have a bearing on that is the `Content-Disposition` header and whether it has a value of `attachment` or not (the default is to assume "not an attachment").

What you can do is to locate the HTML body and modify the MimeEntity.ContentType property to remove the name parameter.

That said, I'll change the code to not set the name parameter in a future release since it's not really needed.
