### ISSUE TITLE
Maybe a Bug - Text Content and Html Content

### ISSUE THREAD

**Issue by schmitch** [jstedfast/MimeKit#456]
**Describe the bug**
Currently depending on the Email sender an email can have two "text/plain" parts.
This mostly happens with Apple Mail when forwarding a Mail, it will create one part with text/plain and another one with text/plain or when using some virus scanners, the structure of the Email will then be as following:

```
--_003_D8AA2C0FA8DE4418AF377264C5FC7456examplecom_
Content-Type: text/plain; charset="us-ascii"
Content-ID: <5CD05ADCC6F3164982DE9BE0EDB2D22B@example.com>




--_003_D8AA2C0FA8DE4418AF377264C5FC7456examplecom_
Content-Type: application/pdf; name="1052047.pdf"
Content-Description: 1052047.pdf
Content-Disposition: attachment; filename="1052047.pdf"; size=75822;
	creation-date="Fri, 23 Nov 2018 07:08:02 GMT";
	modification-date="Fri, 23 Nov 2018 07:08:02 GMT"
Content-ID: <E4125BF581433A4D90A73922CA0CF8A8@example.com>
Content-Transfer-Encoding: base64

--_003_D8AA2C0FA8DE4418AF377264C5FC7456examplecom_
Content-Type: text/plain; name="ATT00001.txt"
Content-Description: ATT00001.txt
Content-Disposition: attachment; filename="ATT00001.txt"; size=311;
	creation-date="Fri, 23 Nov 2018 07:08:02 GMT";
	modification-date="Fri, 23 Nov 2018 07:08:02 GMT"
Content-ID: <15ACD470FDD56446AB41866649E61F30@example.com>
Content-Transfer-Encoding: base64

DQoNCkJlc3RlIEdyw7zDn2UNCg0KTWF4aW1pbGxpYW4gS2x1bmR0

--_003_D8AA2C0FA8DE4418AF377264C5FC7456examplecom_--
```

Actually when now trying to get the Body of the Email via `HtmlText` or `HtmlBody` the Content will be empty.

**To Reproduce**
1. Use Apple Mail and Forward an Email
2. Use MimeKit to analyze it and Get the Content of the Mail via HtmlText or HtmlBody

**Expected behavior**
HtmlText or HtmlBody should actually always have the first non empty Body and not just return the first text/plain content

**Additional context**
Not sure if that should be fixable since only some Email Programs can "correctly" read that Mails (Apple Mail)

**Comment by jstedfast** [comment]
I don't have Apple Mail so you're going to have to give me some real examples.

The example you have doesn't have any HTML so I don't understand why you would expect MimeKit to find any.

**Comment by schmitch** [comment]
Well my example was more about TextBody.

**Comment by jstedfast** [comment]
Oh, I misunderstood because you said `HtmlText or HtmlBody` which didn't make any sense to me.

I'm going to call this not a bug. Your solution might work for these specific messages, but what if I design a message that is explicitly meant to have blank text and also a text file attachment? What then?

My recommendation is to not use the convenience TextBody and HtmlBody properties but to instead use the MimeVisitor API to "render" your message body.

Read the [FAQ](https://github.com/jstedfast/MimeKit/blob/master/FAQ.md#q-how-do-i-tell-if-a-message-has-attachments) on rendering messages using an example `HtmlPreviewVisitor`.
