### ISSUE TITLE
Build error after upgrading MimeKit to .NET 4.7.2: Your project does not reference “.NETFramework,Version=v4.7.2” framework

### ISSUE THREAD

**Issue by HerrimanCoder** [jstedfast/MimeKit#494]
I downloaded MimeKit and opened it in VS2019. I attempted to update the project from .NET 4.5 to .NET 4.7.2. After doing this, it won't compile. I get the following error:

> Your project does not reference ".NETFramework,Version=v4.7.2" framework.

I carefully read this article and tried what it suggested, but it didn't work:
https://stackoverflow.com/questions/51541371/build-error-while-transitioning-between-branches-your-project-is-not-referencin/51542544

I have tried the following:

 1. I deleted the bin/obj folders from the project root down.
 2. I cleaned the project. (multiple times)
 3. I rebuilt the project. (multiple times)
 4. I attempted a nuget restore - had no effect.
 5. I opened the .csproj file and looked for references to .json files but found none.

I don't know what else to try. Thanks in advance for any advice.

**Comment by jstedfast** [comment]
Any reason you can't use the .NET 4.5 assembly or the .NETStandard 2.0 assembly?

All I can guess is that you didn't update the nuget package references to the .NET 4.7.2 versions, but I don't know for sure because I don't currently have access to VS2019 to test things.

Anyway, I'm going to close this because it's not really a bug in MimeKit.
