### ISSUE TITLE
SearchQuery.DeliveredOn

### ISSUE THREAD

**Issue by jamestreacy** [jstedfast/MimeKit#502]
Hi Jeffrey,
First I have previously donated to Mimekit and use it regularly this is one of my favourite products.  Thank you for a brilliant product, so much better than the alternatives and really well documented.

I have a small issue with SearchQuery.DeliveredOn.
I want to find messages not read delivered today with the following query:
query = SearchQuery.NotSeen.And(SearchQuery.DeliveredOn(DateTime.Today));
We are in Sydney and are receiving emails from a different timezone (Singapore) and although a message is reported by Office365 as being delivered today and is in fact delivered today, it is not picked up in this query.  I see in the debugger, the Date.UtcDateTime attribute is yesterday possibly because of the timezone difference.

I can work around this issue with 
query = SearchQuery..NotSeen.And(SearchQuery.DeliveredAfter(DateTime.Today.AddDays(-1)));

but this is a bit of a kludge.
I attach a screen shot from the VS debugger that shows the date properties of the message in question.  Office365 says the message date is today at 7:21,14am which is the same as Date.DateTime in the message Date field.  I note the Date.UtcDateTime field is yesterday, this may be relevant.  Perhaps SearchQuery.DeliveredOn refers to Date.UtcDateTime but Office365 shows the date as Date.DateTime?  This message was delivered to me today not yesterday!  I don't want to modify your source because I am keeping up with your releases and have 2.3.0 installed.
Can you help explain how I can avoid my kludge so I can use
 query = SearchQuery.NotSeen.And(SearchQuery.DeliveredOn(DateTime.Today));

I only have this issue with emails from a different timezone and I have read that time is ignored in SearchQuery.DeliveredOn.  Maybe I need to do some extra work around timezone or localtime?  Any ideas?

Many thanks again for a first class product.

James Treacy, Sydney
Email jamestreacy@optusnet.com.au or james.treacy@dataline.com.au
![Message-Date](https://user-images.githubusercontent.com/20943793/63897738-95ff6480-ca39-11e9-8797-b4e71e7c05d2.png)

**Comment by jstedfast** [comment]
You are running into one of the unfortunate limitations of the IMAP protocol which is that many of the date-based SEARCH criteria are day-month-year based and have no way to specify a time or a timezone, so queries like this are less useful than they could be.

What the IMAP server generally does is to assume the date provided is in whatever timezone the server is configured in.

Does your server support the `ImapCapabilities.Within` capability? This IMAP extension is meant to address exactly this sort of issue.

```csharp
client.Capabilities.HasFlag (ImapCapabilities.Within)
```

If so, you can use the `SearchQuery.YoungerThan (int seconds)` API which will be more flexible (then you could, for example, search for messages delivered in the past 24 hours or since the last query).

If not, then what you are doing is probably the best way to go (as much of a hack as it is, it's actually not that bad).

Thanks for the donation and the compliments, they are both appreciated!

**Comment by jamestreacy** [comment]
Hey thanks for the very quick response we use Office365 so it probably does support Within.  I'll give that a try and if it works, great otherwise I'll stick with my current solution.

Many thanks
James Treacy
