### ISSUE TITLE
Base64 encoded From and Reply-To headers not being parsed as such (unlike Subject)

### ISSUE THREAD

**Issue by wartab** [jstedfast/MimeKit#503]
**Describe the bug**
I have recently been getting spam email where the From header as well as the Reply-To header contained base64 encoded data. But this is not parsed, therefore leading to the sender being still base64 encoded when showig the data.

**To Reproduce**
The headers look as such:
Reply-To: =?utf-8?B?IndhcnRhYiIgPHdhckB0YWIuY29tPg==?=
From: =?utf-8?B?IndhcnRhYiIgPHdhckB0YWIuY29tPg==?=

**Expected behavior**
OVH's web mail client and Thunderbird show this:
`"wartab" <war@tab.com>`

I'm assuming that is what is desired.

Subjects encoded in this way are already changed accordingly.

**Comment by jstedfast** [comment]
MimeKit's address parser isn't parsing those addresses because they are syntactically invalid.

You are only supposed to encode the name component, not the entire thing.

Read [Rfc2047, Section 5](https://tools.ietf.org/html/rfc2047#section-5) for details.

Specifically, part (3) is relevant here.


This is how Thunderbird and OVH must be displaying these headers:

```csharp
var message = MimeMessage.Load (stream);

foreach (var header in message.Headers) {
    Console.WriteLine ("{0}: {1}", header.Field, header.Value);
}
```

**Comment by wartab** [comment]
Okay thanks, if this is not RFC compliant, I'm not gonna bother with it. So far I've only seen it with one type of spam messages, so I'm not too worried. Thanks for the heads up.

**Comment by jstedfast** [comment]
I figured it had to be spam because no legitimate email client would encode addresses like that ;-)
