### ISSUE TITLE
Chain not properly set when signing a S/MIME mail with a PKCS#12 file

### ISSUE THREAD

**Issue by mtausig** [jstedfast/MimeKit#515]
**Describe the bug**

I tried to sign a S/MIME mail with a key stored in a PKCS#12 file:

```
var smimeCtx = new TemporarySecureMimeContext();
smimeCtx.Import("/tmp/my.p12", "1234");


var message = new MimeMessage();
message.From.Add(new MailboxAddress("", "me@my.com"));
message.To.Add(new MailboxAddress("", "you@you.com"));
message.Subject = "Foo";

message.Body = new TextPart(MimeKit.Text.TextFormat.Html) { Text = "Test"}
var signature = MultipartSigned.Create(smimeCtx, message.From.Mailboxes.First(), DigestAlgorithm.Sha256, message.Body);
message.Body = signature;
```

The problem is, that the certificate's chain is not included in the signature (even after issue #500 was fixed).

I tried to trace the problem down and found that the *GetTrustedAnchors* function (which is used in the *BuildCertificateChain* method) simply returns all certificates imported from the P12 file as trust anchors, resulting in a chain which only contains the signing certificate.

https://github.com/jstedfast/MimeKit/blob/5c0578bf8d166f8604658cded45ad0d08ffb58df/MimeKit/Cryptography/TemporarySecureMimeContext.cs#L167-L174

https://github.com/jstedfast/MimeKit/blob/cc0efb8216d04cd450ab0dd0a100b0bc4fbd0fd8/MimeKit/Cryptography/BouncyCastleSecureMimeContext.cs#L438

**Platform (please complete the following information):**
 - OS: Linux
 - .NET Runtime: Mono
 - .NET Framework: 4.7
 - MimeKit Version: 2.3.2 (from NuGet)

**To Reproduce**

Run the code above and parse the message produced

**Expected behavior**

The full certificate chain should be included in the signature

**Comment by jstedfast** [comment]
MimeKit 2.4.0 has just been released with this feature.

**Comment by mtausig** [comment]
I haven't tested it, but if I read the patch correctly, this does not properly work for chains with >=  3 certificates, since all certificates with the *KeyCertSign* keyUsage (and thus also intermediates) are used as trust anchors.

https://github.com/jstedfast/MimeKit/blob/cfe65b7795e3e09858c63a5fb849bbaf5776105c/MimeKit/Cryptography/TemporarySecureMimeContext.cs#L173-L174

**Comment by jstedfast** [comment]
Fair enough. Got any suggestions on what restrictions to use?

**Comment by mtausig** [comment]
> Fair enough. Got any suggestions on what restrictions to use?

I'd just take all self signed certificates.

**Comment by jstedfast** [comment]
Unfortunately doing that makes quite a few of my S/MIME unit tests fail because Bouncy Castle cannot handle Version 1 certificates as CA certificates.

From what I can tell, that's not *actually* a bug in my code so much as it's a "bug" in my generated certificates that I use for testing.

I would appreciate it if you took the time to read over this script: https://github.com/jstedfast/MimeKit/blob/master/UnitTests/TestData/smime/gencerts.sh

Assuming that my understanding about Version 1 X.509 certificates is correct and that my generated certificates should be using Version 3, it would be a HUGE help if you could fix my gencerts.sh script to generate them.

If not, it'll probably take me a week or more to get to this because I'm not going to make a release where my unit tests fail and I probably won't have time to work on this again until next weekend at the earliest.

**Comment by jstedfast** [comment]
Reopening this for now.

**Comment by jstedfast** [comment]
Please test this fix by installing a nuget from https://www.myget.org/feed/mimekit/package/nuget/MimeKit

You'll need >= v2.4.0.4

**Comment by mtausig** [comment]
I can confirm that it works with 2.4.0.8.
Thanks a lot for the fix.

**Comment by jstedfast** [comment]
Awesome, thanks for confirming!
