### ISSUE TITLE
Missing ":" seperating header field and empty field body

### ISSUE THREAD

**Issue by domadden** [jstedfast/MimeKit#525]
I am wondering if a message containing this structure should cause an error within mimekit

```
Header1: field body 1\r\n
Header2\r\n
Header3: field body 3\r\n
```

Currently, when parsing a message containing similar headers with mimekit, there are no errors. Is the ":" required?

I am using version 2.4.0.1 from nuget.

**Comment by jstedfast** [comment]
According to the specs, yes, it is invalid.

If MimeKit ignores it, it's probably because I was getting bug reports saying it failed to parse messages that had headers like that in the wild.

I *try* to work around issues that people run into in the wild, but it's a balancing act of what I can do easily and what would take massive amounts of work to try to handle in any sort of sane way.

I'm not sure off the top of my head how MimeKit deals with the particular test case that you posted above (I'd have to dig thru the code to figure it out).

Is there a reason you're asking? Is it not working for you? Is it working and you expect it not to? I'm not entirely sure based on your question.

**Comment by domadden** [comment]
I attempted to parse a message containing this header, then save the message to disk again in hopes that it would correct the invalid header, however the message that was written out still had the invalid header. I would either expect an error, for the message to be written out with the invalid header corrected, or written out with the invalid header ignored.

I'm not 100% sure the message is being saved by mimekit or if it is just copying the filestream where the message was loaded from as this is a fairly large codebase. I will have to look into that. But the message is being parsed by mimekit and i was wondering why there was no error being thrown.

**Comment by jstedfast** [comment]
When saving messages back out (even broken ones), MimeKit *tries* to save back out byte-for-byte exactly what the parser read from the stream.

MimeKit used to try and correct some of this stuff when writing out, but that breaks DKIM-Signatures and ARC Signatures as well, so I can't really do that anymore.

**Comment by domadden** [comment]
It's a great library nonetheless.

It would be nice if you could provide validation options for what types of invalid content should be detected and cause an exception, or detected and corrected. But i can see how that would be difficult. Maybe there should be a separate library for detection and/or correction of invalid content. Since, ideally, you don't want to have to validate every message, only the messages that fail to be consumed downstream.

**Comment by jstedfast** [comment]
What's the use-case that you're dealing with? Maybe if I understood what you were trying to do better, I could think of a way to get what you need.
