### ISSUE TITLE
Expose the detected text Encoding in TextPart/MimeContent or make CharsetUtils public

### ISSUE THREAD

**Issue by creativbox** [jstedfast/MimeKit#526]
We need to store the original raw content of the TextPart externally. But when using the TextPart.Content to get the raw content stream directly, we lose the possibility to get the right encoding/code page from the charset (or fallback). We then need to parse the charset our self, which is already fully implemented by MimeKit.

It would be great to either get the detected encoding from the TextPart or to use the CharsetUtils.GetEncoding() method directly.

**Comment by jstedfast** [comment]
What you want is already available:

```csharp
string charset = textPart.ContentType.Charset;
```

**Comment by creativbox** [comment]
Yes, but how do you get the code page or System.Text.Encoding from that? You would have to reimplement the same functionality that is available in CharsetUtils.GetCodePage() yourself again.

**Comment by jstedfast** [comment]
Why do you need the code page?

**Comment by creativbox** [comment]
I need to parse MIME messages and put the contents into an external system. Rendering is done by that system, but it expects the code page for the text parts. 
Of cause I can store the text in unicode or some other encoding and use that, but in case of HTML it might get confused with meta tags etc. I would therefore rather forward the original content in its native encoding format. 

Btw thanks for your great work, I really appreciate your effort.

**Comment by jstedfast** [comment]
It seems like your design is a bit awkward. I would recommend saving the raw TextPart MIME headers and all, because realistically you'll eventually need that if you want to also deal with format=flowed and other stuff where you may need various other Content-Type parameters beyond just the charset.

```csharp
textPart.WriteTo (rawStream);
```

and then you can load it again later (from the subsystem that does the rendering) via:

```csharp
var textPart = (TextPart) MimeEntity.Load (rawStream);
```

Also, don't forget tools like `MimeKit.Text.FlowedToText` and `MimeKit.Text.FlowedToHtml` (and the various other text converters).

format=flowed is rare, but I've seen them in the wild.

**Comment by creativbox** [comment]
Yeah, it is awkward, but unfortunately we don't have control over the external requirements. We need to deconstruct the original MIME message completely and store it in the expected format. As you said, this includes a lot of other stuff...

Thanks for your ideas and hints.

**Comment by jstedfast** [comment]
Can you explain the issue with storing the decoded unicode text again? I didn't understand why the  external system might get confused by metadata tags?

That sounds like the external system is parsing the text to try and get a charset?

If that's the case, why doesn't it try and do that with the raw TextPart content? Is it because the test cases you have so far are all base64 encoded?

**Comment by jstedfast** [comment]
What if I provide the following API?

```csharp
public string GetText (out Encoding encoding)
```

**Comment by creativbox** [comment]
> Can you explain the issue with storing the decoded unicode text again? I didn't understand why the external system might get confused by metadata tags?
> 
> That sounds like the external system is parsing the text to try and get a charset (from the HTML)?

That was just an educated guess, I think I can convert the text to UTF-8 or similar without a problem. But why should I decode to unicode at all if it's not actually used at this point and the target system is already doing all on its own. All I want is just write the raw content and leave decoding the charset to the target system.

> If that's the case, why doesn't it try and do that with the raw TextPart content? Is it because the test cases you have so far are all base64 encoded?

Rendering is not using MimeKit at all, it's an unmanaged system. 

> What if I provide the following API?
> 
> ```cs
> public string GetText (out Encoding encoding)
> ```

That would work, but I would prefer to get the encoding separately to avoid processing the text multiple times. I really don't need the decoded text. Something like:
```cs
public Encoding GetEncoding();
public bool TryGetEncoding(out Encoding encoding);
```
Many thanks for having a look at this.

**Comment by jstedfast** [comment]
The problem with the GetEncoding/TryGetEncoding API is that MimeKit actually does need to process the text in order to get the Encoding because it does fallback based on exceptions it gets in the conversion process.

If all you want is the `Content-Type` header's charset parameter value as an Encoding, I could probably add that, but it wouldn't necessarily be all that valuable.

**Comment by creativbox** [comment]
You are actually right, for my case it would make more sense on the `Content-Type` header.

**Comment by creativbox** [comment]
You're awesome, thanks!
