### ISSUE TITLE
ä being changed to Ã¤ on MimeMessage.Load

### ISSUE THREAD

**Issue by caradrye** [jstedfast/MimeKit#535]
Steps to reproduce:

1. Load plain text message, Content-type: text/plain; charset= iso-8859-1
that contains umlaud

[test.txt](https://github.com/jstedfast/MimeKit/files/4140128/test.txt)

`var message = MimeMessage.Load(File.Open(@"c:\test.msg", FileMode.Open));`

Expected Result: Message is unaffected like most other emails containing foreign characters
Actual Result: Message is obfuscated

PS. Thanks for the AWESOME mime parser. I have only ever had good things to say about this product!

**Comment by jstedfast** [comment]
The problem is that the `Content-Type` header specifies that the message body is in iso-8859-1 but the message body is actually in UTF-8.

UTF-8 represents the `ä` character as 2 bytes and so when MimeKit converts text that it is told is in iso-8859-1 (which uses 1 byte per character), it sees `Ã¤` and so converts those 2 bytes into 2 unicode characters which is what you are seeing.

What you can do, in this case, is to do:

```csharp
TextPart body = GetMessageBody (message);
string text;

try {
    text = body.GetText (Encoding.UTF8);
} catch {
    text = body.Text;
}
```

My guess is that you are probably using the `message.TextBody` property. The problem with this property is that it assumes that the information given in the MIME document is correct (and it isn't always correct, unfortunately, as you've discovered).

A lot of mail clients, because of problems like this one, will offer a menu option to override the charset used for rendering the message body text (and sometimes even for the message headers).

For example, Outlook on Mac has the following menu:

<img width="462" alt="outlook-charset-menu" src="https://user-images.githubusercontent.com/338984/73557637-91dbd680-441f-11ea-9c69-76b052e9dcf0.png">

The way to support this in your application is to start with the `HtmlPreviewVisitor` class in the [FAQ](https://github.com/jstedfast/MimeKit/blob/master/FAQ.md#HasAttachments) and then modify the `VisitTextPart` method, replacing:

```csharp
body = converter.Convert (entity.Text);
```

with:

```csharp
try {
    body = entity.GetText (UserSpecifiedEncoding);
} catch {
    body = entity.Text;
}
```

Hope that helps!
