### ISSUE TITLE
Wrong encoding

### ISSUE THREAD

**Issue by martinrotter** [jstedfast/MimeKit#554]
https://github.com/jstedfast/MimeKit/blob/master/MimeKit/MimeMessage.cs#L988

This method returns wrong string data, when any of textual body parts in fact uses some non-ascii characters.

For example when using MimeKit.MimeMessage.CreateFromMailMessage(mail); with original mail set with some non-ascii text, for example mail.Body = "pepíček".
When using MimeMessage.ToString(), this text gets corrupted.

I workaround issue by directly using WriteTo() method and doing byte[] -> string conversion myself.

**Comment by jstedfast** [comment]
You did exactly as I always recommend people do.

I NEVER recommend using ToString() because ToString() can never work properly.

Think about it:

What if I create a MimeMessage with multiple `text/*` parts, each with a different charset encoding? How do I convert that into a string using only 1 System.Text.Encoding? Impossible.

That's why MimeMessage.ToString() has the following documentation comment:

```
/// <summary>
/// Returns a <see cref="System.String"/> that represents the current <see cref="MimeKit.MimeMessage"/>.
/// </summary>
/// <remarks>
/// <para>Returns a <see cref="System.String"/> that represents the current <see cref="MimeKit.MimeMessage"/>.</para>
/// <note type="warning">In general, the string returned from this method SHOULD NOT be used for serializing
/// the message to disk. It is recommended that you use <see cref="WriteTo(Stream,CancellationToken)"/> instead.</note>
/// </remarks>
/// <returns>A <see cref="System.String"/> that represents the current <see cref="MimeKit.MimeMessage"/>.</returns>
```

**Comment by jstedfast** [comment]
When I originally released MimeKit, I had the ToString() for debugging purposes and never imagined people would assume that was the right way to serialize messages.

Unfortunately, by the time I realized that people were doing this, I can't take it out because if I do, their software will start writing "MimeKit.MimeMessage" to disk instead of what it is writing now and the result will be that they lose data.

So I'm stuck.

**Comment by martinrotter** [comment]
Good, maybe just add ToString(Encoding) overload?

**Comment by jstedfast** [comment]
You're not understanding the issue. The problem is that won't solve it because that assumes that the entire message is in 1 encoding.

**Comment by martinrotter** [comment]
I understand, but ToString(Encoding) would be enough for 90% of people who just need single encoding. Anyway, thanks for any assistance.

**Comment by jstedfast** [comment]
No, it wouldn't - and here's why:

Now that you have a `string` which is in unicode, when you save it to disk - how does charset conversion happen? Well, it most likely converts it to UTF-8 when saving to disk.

But that's not the original charset specified in the `text/*` part(s) of your message. So it will, once again, be corrupt.

**Comment by jstedfast** [comment]
Let me ask you something important to this discussion:

Why do you want the message in `string` form?

Why do you *not* want it as a `Stream` instead (or even `byte[]`) instead?

Presumably the goal is to write it to disk or to a network socket, right? For that, you want a stream or bytes anyway. Not a string.

My guess is you are using a string because it seems convenient, not because it's what you actually *want* or *need*.

**Comment by ahmed-abdelrazek** [comment]
i wanted it to send via gmail 
and i came up with this based on your comments and mimemessage tostring method

```
using (var memory = new MemoryStream())
{
    mailMessage.WriteTo(FormatOptions.Default, memory);

    var buffer = memory.GetBuffer();
    int count = (int)memory.Length;

    var base64Raw = WebEncoders.Base64UrlEncode(buffer, 0, count);
    var newMsg = new Google.Apis.Gmail.v1.Data.Message
    {
        Raw = base64Raw
    };

    await service.Users.Messages.Send(newMsg, "me").ExecuteAsync();
}
```
