### ISSUE TITLE
[Question] Export msg attachment from eml

### ISSUE THREAD

**Issue by Zoidster** [jstedfast/MimeKit#556]
I am trying to export an attached .msg file from an .eml email.
I got hold of the `MessagePart` attachment but now I am stuck.
`MessagePart::WriteTo` is only usable for eml files, right?
The conversion to eml seems to be a bit lossy, because the original body of the msg is in rtf format and not every font seems to be correctly displaying in the exported eml file.

If possible I would like to export attached eml files as eml and msg files as msg.
Current implementation of attached message exporting:

```
private (string FilePath, string OriginalFileName) ExportAttachment(MessagePart attachment, string attachmentDir)
{
	string file = fileSystem.Path.Combine(attachmentDir, $"{Guid.NewGuid()}.eml");

	using (var stream = fileSystem.FileStream.Create(file, FileMode.CreateNew))
	{
		attachment.Message.WriteTo(stream);
	}

	return (file, attachment.Message.Subject);
}
```

**Comment by jstedfast** [comment]
I'm glad you updated your question with your current code, because I misunderstood your question and thought you were doing `attachment.WriteTo (stream)` and was going to suggest using `attachment.Message.WriteTo (stream)`.

That said, I don't know what you mean when you say that the original message is in rtf format because that's not possible. Do you mean the message body of the original message is in rtf format?

There's no conversion that MimeKit does for attached messages. It just saves out raw.

**Comment by Zoidster** [comment]
The body is rtf, yes.
Okay then maybe I missed something in the way I handle the exported eml files.

But wither way, would there be a way to save it as an msg?

**Comment by jstedfast** [comment]
If by "msg" you mean the proprietary binary format that Outlook uses, then no. MimeKit only supports the MIME format specification.

Just one last question from me as this thought popped into my head that *may* be related, but are you parsing a winmail.dat TNEF file to get this attached message?

**Comment by Zoidster** [comment]
Ok thank you 👍 
I am not that familiar with mail formats and thought the original attachment might just be attached as a binary and then parsed by MimeKit.

No, just a normal eml file as it comes from my mail server.

Thank you for your time!

**Comment by jstedfast** [comment]
Good luck, hopefully you figure out what the issue is. I was actually about to recommend taking a look at https://github.com/Sicos1977 since he has a MSGReader library for reading Outlook MSG files and a MsgKit library for writing them, but it looks like you've already been using it ;-)

I'm not very familiar with the RTF format myself, but I think that format can refer to embedded -or- system fonts and according to https://en.wikipedia.org/wiki/Rich_Text_Format#Fonts - embedded fonts are not widely supported, so *perhaps* the issue is that whatever renderer you are using doesn't support embedded fonts?

**Comment by Zoidster** [comment]
Yes MsgReader is really good 😁

Good point, but I checked the rtf file and it doesnt seem to have any embedded font info.
