### ISSUE TITLE
Does MimeContent dispose streams?

### ISSUE THREAD

**Issue by polterguy** [jstedfast/MimeKit#570]
When you associate a `Stream` object with a `MimeContent` instance, for instance a file stream, I assume the objective is to avoid having to read the while file into memory before transferring it to (for instance) the `SmtpClient`, to such being able to do a simple `Stream.CopyTo` with the file stream being the source, and the socket stream to the SMTP server the destination stream.

This of course, have many advantages, saving a lot of memory on the application that actually consumes MimeKit. However, it also raises the question of who **owns** the stream after it has been associated with the `MimeContent` object.

Purely practically it's actually quite difficult to correctly `Dispose` such streams, since often this is done deep inside of some method, that is recursively traversed, due to that the MIME format actually is a graph object (tree structure).

For .Net Core, if you return a `FileResult` to a `Controller` endpoint, I know that the runtime will _"take ownership over the stream object"_, and correctly dispose it once it's done with it. Does MimeKit give similar guarantees ...?

I have another question too, but to make sure I keep your issues as tidy as possible, I'll open up another issue for that. Thx for a great lib Jeffrey :)

**Comment by jstedfast** [comment]
MimeKit currently does not dispose the Streams given to a MimeContent object.

In the top-level MimeKit source directory, there's an old [disposable.patch](https://github.com/jstedfast/MimeKit/blob/master/disposable.patch) that added this functionality, but I had to scrap it because I wanted developers to be able to re-use the same MimePart or same MimeContext object in multiple message structures and so what I *really* need is some sort of reference counting mechanism. I think it also caused the unit tests to fail because objects were getting disposed prematurely and I don't remember if I ever figured out why.

Since the .NET runtimes will eventually GC the Streams anyway, I left them alone. Probably not my best design decision...

As a sort of work-around, I made the MimeParser parse messages into custom MimeKit.IO.MemoryBlockStreams which are fully managed and therefore don't really need to be GC'd.

An easy way to work around MimeKit's dispose flaw is to do something like this:

```csharp
foreach (var part in message.BodyParts.OfType<MimePart> ())
    part.Content?.Stream.Dispose ();
```

**Comment by polterguy** [comment]
Darn it. Figures. I guess in order to correctly implement this, you'd have to implement `IDisposable` on both `MimeEntity` and `MimeMessage`, and then we'd have to make sure we ourselves in our code somehow dispose these objects.

This would only be a problem (I believe) when you combine it with `SmtpClient` (right?) and not `Pop3Client` (or IMAP?), and you create `ContentObject` instances wrapping a file stream ...?

Is there no way you could implement `IDisposable` on these two classes ...?
It would make my life easier ... :)

... or at least maybe some custom method that recursively runs through all `MimeEntity` instances, and disposes all streams in it ...?

I know memory based streams don't really need to be disposed, but when I'm sending my own messages using `SmtpClient`, I often have huge files as attachments I don't want to read into memory first. BTW, just checking, but this results in the stream being directly serialised into the socket for my `SmtpClient`, right ...?

**Comment by jstedfast** [comment]
When I wrote MailKit originally, it did stream the messages directly to the NetworkStream (so effectively directly to the socket), but these days it serializes the message to a buffered output stream (SmtpStream, ImapStream, and Pop3Stream are all buffered I/O).

**Comment by polterguy** [comment]
OK, thx :)
