### ISSUE TITLE
Subclassing PGP context

### ISSUE THREAD

**Issue by polterguy** [jstedfast/MimeKit#571]
How would I start out when wanting to subclass a PGP context, to provide my own (completely custom) persistence layer. Specifically, the idea is to save both public and private keys in a database. This is something I'll have to do, first of all because it's the server itself that _"owns"_ the private key, and for public keys there might be millions, and I also want to have referential integrity towards other database records ...?

Do you have any pointers as to how to get started with this?

**Comment by jstedfast** [comment]
Hmmm, good question.

Looking at OpenPgpContext, I'll probably need to make some methods virtual (doing it now) so that you can override the following methods to obtain public/secret keys:

- EnumeratePublicKeys()
- EnumeratePublicKeyRings()
- EnumerateSecretKeys()
- EnumerateSecretKeyRings()

and optionally:

- EnumeratePublicKeys(MailboxAddress)
- EnumeratePublicKeyRings(MailboxAddress)
- EnumerateSecretKeys(MailboxAddress)
- EnumerateSecretKeyRings(MailboxAddress)

(If your database would make it quicker/faster to do lookups based on an address or fingerprint, you'd want to override the Enumerate methods that take a MailboxAddress - otherwise they are probably not worth overriding).

You'll also need to override:

- GetPasswordForKey(PgpSecretKey)

I would also recommend overriding the Import() methods - specifically the ones that import PgpPublicKeyRing, PgpSecretKeyRing and the Bundle variants. The other Import() methods just wrap those 4, so it's not necessary to override them.

Does that help?

**Comment by polterguy** [comment]
Brilliant, thx as always :)

BTW, what I wanted to do, is to create a _"Direct Democracy"_ server system, allowing people to _"vote"_ on yes/no types of questions. This would require a security mechanism to avoid fake votes to reach the server and be registered as actually votes, which I figure PGP crypto signatures could easily accomplish.

Then I'd have a KYC (Know Your Client) process, that allows people to submit documents proving who they are (images of themselves, identification papers, etc) using the same process.

By using emails as my foundation for accepting both KYC documents, and votes, I get to avoid creating clients for iPhone, Android, Windows, etc - But rather allow others to use their existing email systems, assuming they have some email client allowing them to sign their emails with their private PGP keys :)

The thing I'd specifically need, is the ability to lookup a public key based upon the fingerprint. By overriding the methods taking a `MailboxAddress`, this would be fairly simple, only requiring one database lookup (normally), for messages signed with only one key, right ...?

The `GetPasswordForKey` override I already know about, but since the server would only (normally) have _one_ private key, which is the _"server key"_ for sending feedback emails, and answering votes/KYC emails, this would normally only contain a single private key ...

This way during the reading process, I'd fetch the fingerprint, do a lookup into my database, verify the email's signature, and accept a vote (or discard it if it fails) ...

**Comment by jstedfast** [comment]
> this would be fairly simple, only requiring one database lookup (normally), for messages signed with only one key, right ...?

That should be the case, yes.

**Comment by jstedfast** [comment]
MimeKit 2.8.0 has just been released with the virtual method changes.

**Comment by polterguy** [comment]
Brilliant mate :)
