### ISSUE TITLE
Is this a feature or a bug? :-)

### ISSUE THREAD

**Issue by mikkelbm** [jstedfast/MimeKit#574]
I have a situation where I forgot to use the incoming http headers for an http post request (for our AS2 server).
99% of them completes successful, when I use the MimeParser.ParseMessage method.
But a few of them fails. 
And now I'm curious... Because it looks like, that if the message starts with a linebreak - everything is fine, and the message can be parsed without headers.
But if this linebreak is not there, the parser fails with: "Failed to parse message headers".

I can't seem to find anything in the RFC that gives this behavior, but maybe I'm looking the wrong places? And since 99% of the partners are sending the message starting with a linebreak, I believe it's default behavior. I was just wondering if the external partner was generating a wrong mime-message not using a starting linebreak.

Everything works fine, now that I have fixed the missing headers (also without a starting linebreak), but I was wondering if this is expected behavior?

The following code can reproduce the scenario:
```
private string MimeMessage = @"--pb921567494
Content-Type:text/plain
Content-Transfer-Encoding:7bit

The message with ID <a1d30208-f3e9-4075-814d-f55418ef8d48@as2.bizbrains.dk> was successfully received.
--pb921567494
Content-Type:message/disposition-notification
Date:Fri, 29 May 2020 13:57:36 GMT

Original-Recipient:5565782504-AS2
Final-Recipient:5565782504-AS2
Original-Message-ID:<a1d30208-f3e9-4075-814d-f55418ef8d48@as2.bizbrains.dk>
Disposition:automatic-action/mdn-sent-automatically;processed
--pb921567494--";


        [TestMethod]
        public void TestWithLineBreak()
        {
            ParseMessage(Environment.NewLine + MimeMessage);
        }

        [TestMethod]
        public void TestWithoutLineBreak()
        {
            ParseMessage(MimeMessage);
        }

        private void ParseMessage(string message)
        {
            var messageStream = new MemoryStream(Encoding.Default.GetBytes(message));
            var parser = new MimeParser(messageStream);
            parser.ParseMessage();
        }
```

**Platform (please complete the following information):**
 - OS: Windows
 - .NET Framework: .NET 4.6
 - MimeKit Version: 2.7

**Comment by jstedfast** [comment]
So the problem above is that the `MimeMessage` string is actually an incomplete message. It is starting with a multipart boundary that is likely defined in the HTTP headers (in the HTTP `Content-Type` header, specifically).

There always needs to be a blank line between the end of the headers (HTTP headers in your case) and the "content" which, in your case, is the `MimeMessage` string.

There's a MimeEntity.Load() method that is designed to help with parsing MIME entities that come from HTTP responses (or, in your case, I guess it would be a post and not a response?): http://www.mimekit.net/docs/html/M_MimeKit_MimeEntity_Load.htm

It won't return a `MimeMessage` object, obviously, but the only real difference between a `MimeEntity` and a `MimeMessage` is that the `MimeMessage` has helper properties for headers like To, From, Cc, Date, Subject, etc.

The returned `MimeEntity` will be the equivalent of the `MimeMessage.Body` property.

Also: Most likely you'll find that the returned `MimeMessage` object from your sample code returns a message with a `text/plain` body that contains the raw MIME of the `MimeMessage` string as its content. But that's definitely not going to be what you want, so even though it seems to be "parsing" without error, it's not giving you what you want.

**Comment by jstedfast** [comment]
For added clarity, let me piece together what the *full* message might look like given your example MIME string:

```
From: Postmaster <postmaster@somewhere.com>
To: Original Message Sender <someone@somewhere.com>
Subject: Message received
Content-Type: multipart/report; report-type="disposition-notification"; boundary="--pb921567494"

--pb921567494
Content-Type:text/plain
Content-Transfer-Encoding:7bit

The message with ID <a1d30208-f3e9-4075-814d-f55418ef8d48@as2.bizbrains.dk> was successfully received.
--pb921567494
Content-Type:message/disposition-notification
Date:Fri, 29 May 2020 13:57:36 GMT

Original-Recipient:5565782504-AS2
Final-Recipient:5565782504-AS2
Original-Message-ID:<a1d30208-f3e9-4075-814d-f55418ef8d48@as2.bizbrains.dk>
Disposition:automatic-action/mdn-sent-automatically;processed
--pb921567494--
```

What MimeKit needs in order to parse the string you are providing to it is the following header:

```
Content-Type: multipart/report; report-type="disposition-notification"; boundary="--pb921567494"
```

That tells MimeKit's parser that the `--pb921567494` is a boundary marker. It also provides the container object that contains the 2 (sub)parts that are within the string that it is parsing.

The From/To/Subject headers *may* also be included as part of the HTTP headers and if they are, you could probably provide those to MimeKit as well but the important one for the parser is the `Content-Type` header. Everything else is just fluff to the parser (although might not be "fluff" to you, depending on whether you want/need that info or not).

If you want that info too and it is in the HTTP headers, what you can do is to use a similar technique to the way that `MimeEntity.Load()` method does which is to write those HTTP headers to a stream and then combine them with the raw content stream:

``csharp
MimeMessage ParseMessage (HttpPostRequest post)
{
    using (var headerStream = new MemoryStream ()) {
        // serialize the headers back to a stream
        foreach (var header in post.Headers) {
            var field = Encoding.ASCII.GetBytes (header.Name);
            var value = Encoding.UTF8.GetBytes (header.Value);

            headerStream.Write (field, 0, field.Length);
            headerStream.Write (new byte[] { (byte) ':' }, 0, 1);
            headerStream.Write (value, 0, value.Length);
            headerStream.Write (new byte[] { (byte) '\r', (byte) '\n' }, 0, 2);
        }

        // add the header block terminating sequence
        headerStream.Write (new byte[] { (byte) '\r', (byte) '\n' }, 0, 2);

        // rewind the header stream
        headerStream.Position = 0;

        // combine the header and content streams into a single chained stream for the parser.
        // as far as the parser knows, this is really all 1 stream, but it's actually 2.
        using (var chained = new ChainedStream ()) {
            chained.Add (headerStream);
            chained.Add (post.ContentStream);

            return MimeMessage.Load (chained);
        }
    }
}
```

**Comment by jstedfast** [comment]
Oh, and obviously, another solution instead of using a `ChainedStream`, would be to simply write the raw headers *and* the content into a single MemoryStream (or FileStream or MimeKit's MemoryBlockStream if you prefer) and then rewind it and pass that to the parser.

The ChainedStream approach just makes it so that you don't have to duplicate the raw POST content into memory.

**Comment by mikkelbm** [comment]
Thanks for your fast and detailed response. I was actually already doing the part where the headers and content should be combined/concatinated.
I found the error though - the reason that it worked in some scenarios, was because of some old code of my own putting in the Content-Type from the http headers. And this code failed if the mime message didn't end with a boundary+"--"+linebreak. And the mime message from my example above didn't end with a linebreak...

I wasn't aware of the MimeEntity.Load method - I will definitely look at that instead of doing any parsing myself...

Thanks!

**Comment by mikkelbm** [comment]
> Also: Most likely you'll find that the returned MimeMessage object from your sample code returns a message with a text/plain body that contains the raw MIME of the MimeMessage string as its content. But that's definitely not going to be what you want, so even though it seems to be "parsing" without error, it's not giving you what you want.

You are right about this and now I'm thinking of it - wouldn't it be better if both of my tests fails, if no headers are present at all? I'm aware of the required linebreak between the headers and the body - but besides the linebreak both of the messages are similar.

**Comment by jstedfast** [comment]
>  wouldn't it be better if both of my tests fails, if no headers are present at all?

Depends on whether you were parsing a MimeMessage or a MimeEntity.

I think you were parsing a MimeMessage, though, and so yes, this should probably throw an exception if the stream starts with a blank line since it should be illegal.

It probably doesn't throw an exception right now because this is actually legal for a MimeEntity.
