### ISSUE TITLE
Sending emails with S/MIME signatures via SendGrid will invalidate the signature

### ISSUE THREAD

**Issue by HiroyukiSakoh** [jstedfast/MimeKit#596]
**Is your feature request related to a problem? Please describe.**
I am trying to send an S/MIME signed email using SendGrid's STMP relay service.

If the body text is `text/plain` and Content-Transfer-Encoding is `base64`,it will be received with an invalidly signed email.

It can be sent correctly via other SMTP servers (e.g. Office365).

SendGrid seems to convert one line of body text to 76 characters and relay it, which results in a different message digest.

**Describe the solution you'd like**
**Describe alternatives you've considered**
The MimePart.WriteTo method sets the Base64Encoder to the default 72 characters and outputs it.
Now I have inherited TextPart and forced the EncoderFilter to set it to 76 characters.
Is there any way to easily change this to 76 characters from my application?

**Additional context**
SendGrid works a bit strange. The attachment file passes as 72 characters.
The RFC specification has both 72 and 76 characters correct, right?

**Comment by jstedfast** [comment]
> Is there any way to easily change this to 76 characters from my application?

Sounds like you already did? MimeKit isn't designed to change this because it's not something that developers should concern themselves with. Obviously SendGrid shouldn't be doing what it is doing.

I would instead recommend using ApplicationPkcs7Mime.Sign() instead of MultipartSigned.Create().

**Comment by Alderstrom** [comment]
Late to a closed issue, but this is where you land from a search for the error, so: we hit
this, `ApplicationPkcs7Mime.Sign()` was the right answer, and here are the measurements
behind it — including one cost of that answer that only shows up on the receiving side.

Our failure was a different encoding from the one reported. The report here is about base64
(MimeKit wrapping at 72, SendGrid re-wrapping to 76); ours was quoted-printable, and the
line-length change ran the other way. Same outcome, two separate mechanisms, so it seemed
worth writing down rather than assuming they are the same bug.

**Setup:** MimeKit 4.17.0, .NET 9, `MultipartSigned.Create` with a `CmsSigner`, relayed
through SendGrid. Detached signature valid at the moment of signing, invalid on arrival:

```
Failed to verify digital signature: message-digest attribute value does not match calculated value
```

The technique that made this tractable was writing the message to disk immediately after
signing, then diffing that against the delivered message. Until you do that, "we signed it
wrong" and "the relay rewrote it" are indistinguishable from the recipient's end. With both
files in hand it took one send.

Two independent quoted-printable changes in transit, both invisible to a reader, both fatal
to a detached signature:

**1. The trailing soft line break.** When quoted-printable content does not end with a
newline, MimeKit closes the part with a bare `=` + CRLF, which decodes to nothing. SendGrid
strips it.

```
sent     : ...example.com=\r\n\r\n--boundary
received : ...example.com\r\n--boundary
```

Three bytes per part, six across a text+HTML alternative. Fixable at the source — make the
body end with a newline before signing and MimeKit emits no soft break:

```csharp
static string EndWithNewLine(string body) =>
    string.IsNullOrEmpty(body) || body.EndsWith('\n') ? body : body + "\r\n";
```

**2. Line length, running the opposite way to the base64 case above.** In quoted-printable
it was MimeKit emitting the over-long line and SendGrid shortening it:

```
sent     : initial-scale=3D=\r\n1">     (line of 78)
received : initial-scale=\r\n=3D1">     (line of 75)
```

MimeKit will not split a `=XX` escape sequence, so when one straddles the limit it lets the
line overrun to 78. RFC 2045 caps quoted-printable at 76. SendGrid is doing nothing wrong
here — it is normalising a non-compliant line, and the signature is collateral.

Re-encoding the same HTML with `FormatOptions.MaxLineLength` set to 72, 74, 76 and 78 gave
max-78 lines every time and never reproduced SendGrid's output. As far as we can tell
`MaxLineLength` does not reach body encoding at all, so there is no public API here to
reach for. Happy to be told otherwise.

**What we shipped: opaque signing** — which is what jstedfast recommended above, so this is
a confirmation with numbers rather than a new suggestion.

```csharp
// instead of MultipartSigned.Create(ctx, signer, body)
message.Body = ApplicationPkcs7Mime.Sign(ctx, signer, body);
```

The content then rides inside the base64 blob, so there is no quoted-printable left for a
relay to normalise, and re-wrapping base64 changes bytes without changing what they decode
to. Measured through SendGrid to Gmail, the signed part arrived **byte-identical** — 16208
base64 characters, 214 lines, longest line 76, decoded CMS identical, signature valid on
both sides. Base64 at 76 already complies, so there was nothing for SendGrid to fix.

The usual objection to opaque signing is that clients without S/MIME support show
`smime.p7m` as an attachment instead of the message. Worth re-testing rather than assuming:
Gmail and Outlook both rendered it normally for us.

**The real cost turned out to be on the receiving side, and it is worth knowing before you
choose opaque.** Mail *clients* were fine. What is not fine is anything that parses inbound
mail programmatically. We found this when a signed message from one of our own addresses to
another reached our inbound webhook as an empty body plus a single `smime.p7m` attachment:
the relay's inbound parsing does not open pkcs7, so the message it handed us contained no
text, no HTML and no attachments. Any ticketing system, autoresponder, archiver or
mailing-list processor downstream will behave the same way, and the failure happens on
someone else's system where you will not see it.

Undoing it is straightforward — `Verify` hands back the original entity, and wrapping that
in a `MimeMessage` makes the ordinary accessors work again:

```csharp
var signatures = p7m.Verify(ctx, out var entity);
var opened = new MimeMessage { Body = entity };   // TextBody, HtmlBody, Attachments
```

Two details that cost us time there. The `smime-type` parameter is not reliable after a
message has been through a gateway, so it is safer to read the CMS content-type OID off the
blob itself (`ContentInfo.GetContentType`) than to trust the label. And gateways relabel
parts they do not understand as `application/octet-stream`, so matching on media type alone
misses them — the `.p7m` extension is sometimes the only thing left that says what the bytes
are.

**Two things that looked like the cause and were not**, in case anyone else is circling
them:

- `SmtpClient` calling `message.Prepare()` internally after the signature is computed. It
  is a no-op here — `BodyBuilder.ToMessageBody()` has already selected quoted-printable, so
  `Prepare` changes nothing and the digest holds.
- Anything in the local sending path. Verified by sending through MailKit's `SmtpClient`
  into a throwaway SMTP server in-process and checking the captured wire bytes: valid for a
  trivial ASCII body, a realistic body forcing quoted-printable, `Prepare(SevenBit)` and
  `Prepare(EightBit)` before and after signing, and double serialisation.

One practical note for anyone reproducing this. Getting the raw MIME of the delivered
message is harder than it sounds, and we got it wrong twice: Outlook Web cannot export raw
MIME at all (saving the page gives you OWA's own HTML), and copying from Gmail's *Show
original* page silently drops the base64 signature blob — which looks exactly like the
relay stripping the signature, and sent us down a wrong path for a round. Only Gmail's
**Download original** button gives usable bytes.

Also worth separating the two questions while debugging: `signature.Verify(verifySignatureOnly: true)`
answers "was the body modified?" without involving trust, so a self-signed test certificate
proves the whole path before you spend anything on a real one. Note that MimeKit throws
`DigitalSignatureVerifyException` on a digest mismatch rather than returning false — that
is the definitive "modified" answer, not an inconclusive one, and it is worth catching and
reporting as a failure rather than as an error checking.

One more, if you go on to check trust as well as integrity. `TemporarySecureMimeContext`
carries no trust anchors, so the full `signature.Verify()` fails with

```
Failed to verify digital signature chain: non-empty set required (Parameter 'tas')
```

for every certificate alike — a self-signed test one and a properly issued commercial one
give the identical message. That is not a verdict on the certificate, and it is easy to read
as one. We ended up answering trust separately with `X509Chain` against the OS certificate
store, seeded from the certificates carried in the CMS as intermediates, and keeping
integrity, trust and From-address identity as three reported answers rather than one.

**Comment by jstedfast** [comment]
A few comments:

> The report here is about base64 (MimeKit wrapping at 72, SendGrid re-wrapping to 76);

MimeKit's base64 encoder wraps at 76 unless explicitly requested otherwise. For example, calling MimeMessage.Prepare() with the maxLineLength argument having a value less than 76.

> SendGrid is doing nothing wrong here — it is normalising a non-compliant line, and the signature is collateral.

I would argue otherwise. Relay servers should never re-encode a message. This is how DKIM, ARC and S/MIME signatures get broken.

I have spent an insane amount of time trying to make sure that MimeKit, for example, can always re-serialize a message *exactly* as it was in the original stream before being parsed.

> Re-encoding the same HTML with FormatOptions.MaxLineLength set to 72, 74, 76 and 78 gave
max-78 lines every time and never reproduced SendGrid's output. As far as we can tell
MaxLineLength does not reach body encoding at all, so there is no public API here to
reach for. Happy to be told otherwise.

If you look at MimePart.cs, the default maxLineLength is defined as 78 (arguably it should be 76, but changing this would only bandaid over the problems in SendGrid).

If you call the Prepare() method with a maxLineLength of 76, it should record that preference and later use that length when quoted-printable or base64 encoding the content when writing the message out to a stream.
