### ISSUE TITLE
Linebreaks in body.HtmlBody or body.TextBody

### ISSUE THREAD

**Issue by biapopescu** [jstedfast/MimeKit#605]
Hello, it's me again! haah
I am trying to hash the text body of an email but I face a problem: if the app is on a Linux platform and the body id parsed, the line breaks are interpreted as "\n" and if I runt it on a Windows they are interpreted as "\r\n". I am trying to get the same hash on both platforms but I am not able to achive it because if this.

One way I was able to sort this out is by replacing the line breaks in the body with the ones that I need but I don't know if that is the correct aproach, because the body can have any kind of data.

Is there a way to get the original linebreaks of the email?

Thank you very much!

**Comment by jstedfast** [comment]
What do you mean that you are trying to hash the body?

If you parse a stream into a MimeMessage, then the body will contain whatever line endings were originally in the stream. There's no line-ending conversion done by the parser.

When you write the message back out to a stream using something like message.WriteTo(stream), then conversion is done in order to convert to the native line endings for the system. You can override this by using a FormatOptions parameter to specify Unix vs DOS line-endings.

```csharp
var options = FormatOptions.Default.Clone ();
options.NewLineFormat = NewLineFormat.Dos;

message.WriteTo (options, stream);
```

If you are trying to generate an md5/sha1 hash (or something like that) in order for some sort of unique identifier, then I would recommend *always* using DOS format no matter what the platform.

Are you trying to hash the entire message? Or just 1 MimePart of the body?

If you are only trying to hash the content of a MimePart (and not the MimePart headers), you can do something like this:

```csharp
using (var filtered = new FilteredStream (stream)) {
    filtered.Add (new Unix2DosFilter ());
    message.WriteTo (filtered);
    filtered.Flush ();
}
```

You could then hash the content of the resulting `stream` (or, if you were so inclined, write a Stream subclass that does the hashing for you as content is written to it). For inspiration, see https://github.com/jstedfast/MimeKit/blob/master/MimeKit/Cryptography/DkimHashStream.cs

**Comment by jstedfast** [comment]
Ah, I see why your body.HtmlBody or body.TextBody strings are converted to the native system format. TextPart.Text/GetText() convert to the system line ending format.

You can bypass this, though, by accessing the part.Content directly.
