### ISSUE TITLE
Add hostname to BodyBuilder for performance

### ISSUE THREAD

**Issue by MartijnFLC** [jstedfast/MimeKit#612]
From version 2.4.0 and up I'm facing performance issues (in combination with .NET Core 3.1 at least). Not big ones, but enough care about it.
See the following example:
```
for(var i =0; i < 1000; i++)
{
	var mail = new MimeMessage();
	var bodybuilder = new BodyBuilder();
	bodybuilder.TextBody = "Hello";
	bodybuilder.HtmlBody = "<p>Hello</p>";
	mail.Body = bodybuilder.ToMessageBody();
}
```
Version 2.3.2: 102ms
Version 2.4.0 and up (including latest 2.9.2): 8383ms

I tried running my example code both on dev, test and prod and both gave similar results.

After looking through the source of MimeKit I found the cause. Both MimeMessage and BodyBuilder call MimeUtils.GenerateMessageId() (without hostname parameter).
Since version 2.4.0 there are specific version added for .NET standard 1.3 and 1.6. See the snippet from the source of MimeUtils.cs:
```
public static string GenerateMessageId ()
{
#if NETSTANDARD1_3 || NETSTANDARD1_6
	return GenerateMessageId ("localhost.localdomain");
#else
	var properties = IPGlobalProperties.GetIPGlobalProperties ();

	return GenerateMessageId (properties.HostName);
#endif
}
```
Therefore now IPGlobalProperties.GetIPGlobalProperties().HostName is called instead of using hardcoded localhost.localdomain.

I guess calling IPGlobalProperties.GetIPGlobalProperties().HostName is better then using localhost.localdomain hardcoded, but this function is somehow extremely slow and adds a 4ms delay per call (in my situation twice, once for MimeMessage and once for BodyBuilder).

When sending large personalized mailings (>10.000) this means more then 80 seconds extra.

MimeMessage has an option to provide the MessageId header so if you manually generate it with the hostname as parameter (manual onetime lookup for example), this function doesn't get called. Not the most user friendly way, but it is a workaround.

In the BodyBuilder on the other hand the parameterless constructor is always called if there is and Html part.

I think there are some solutions:
- Specify the hostname in the constructors and, if not null, use this one instead of looking it up.
- Add an option to both MimeMessage and BodyBuilder to set the MessageId manually and use this one it not null.
- Add a hostname caching option to only look it up once.

I hope to hear the thoughts of one of the developers.

**Comment by jstedfast** [comment]
Wow, I had no idea... thanks for digging into this!

Right now, I'm leaning toward the caching option. I don't want to add a hostname property to MimeMessage as it would be an odd property to set (not intuitive at all - e.g. if I parse a message from a file, I get back a MimeMessage with a null `HostName` property even though when I serialized it, it might have been non-null). Same for BodyBuilder (although with BodyBuilder, it would be more acceptable because it's a builder class where something like that wouldn't be as gross).

**Comment by jstedfast** [comment]
I've added a cache which should fix the main issue. I'll think about adding a property to BodyBuilder, but I think it might be awkward. Perhaps I could instead add a protected virtual method GenerateContentId() or something?

**Comment by MartijnFLC** [comment]
Thank you for the cache option. This should improve the performance a lot, including the BodyBuilder. And I agree that a HostName property on a MimeMessage object doesn't make much sense.

Regarding the virtual method on BodyBuilder: it will make it more flexible and I can't see any harm in it. In my current workaround I was actually missing this.

Furthermore in my best knowledge it is preferred to use a FQDN and not a hostname for the Message and Content ID. The FQDN cannot be reliable determined by code in general, so if you add the virtual method to BodyBuilder it is possible to use a FQDN from a settings file or something.

Wouldn't it also make sense to provide a similar function on the MimeMessage class, for example virtual GenerateMessageId() so it works in line with bodybuilder?
Now it is possible provide it in a header in the constructor that works, but I think I only found it out by studying the source code.
Using the property MessageId will work and sounds more intuitive, but then the MessageId is always generated twice if you use a custom code.
It is not really necessary if the virtual function on the BodyBuilder is implemented. In both classes there is at least an option to use a custom method. But I like to hear your thought about this.

**Comment by jstedfast** [comment]
I don't mind adding a protected virtual GenerateMessageId() method to MimeMessage - I'm just not sure offhand how valuable it is.

Now that MimeUtils.GenerateMessageId() caches the hostname result, it shouldn't be quite as expensive going forward.

That said, if you would like a virtual method in MimeMessage - I'm willing to add it.

As for BodyBuilder... I discovered the other day when investigating this bug that MultipartRelated.set_Root() would set the ContentId property if it wasn't already set. Since set_Root() was doing that, I realized that BodyBuilder.ToMessageBody() didn't need to *also* set it, so I removed that code.

Just now, I looked at the code again to see if there was a way to maybe put the virtual GenerateMessageId() method on something like FormatOptions to maybe simplify things (rather than force developers to subclass MimeMessage and MultipartRelated in order to customize the message-id/content-id generation).

It dawned on me that since multipart/related only needs to set a Content-Id header if it plans to use it as a `start=<id@example.com>` parameter and because we *only* do that if the Root is *not* the first child, then we don't need to set the Content-Id unless we need to use it:

https://github.com/jstedfast/MimeKit/commit/13f231e673ab10333a81bfc4d44e9dce09fc6e3c

What does this mean for you?

Well, it means that you'll no longer have to worry about Content-Id generation for your HTML body because the way BodyBuilder constructs messages, the Root of a multipart/related is *always* the first child.

That leaves any Content-Ids that you generate manually for the images that need to be referenced by the HTML body (which your code needs to handle explicitly anyway) and `MimeMessage.MessageId`.

And again... I'm willing to add a virtual method to MimeMessage for this, I'm just not sure if it's really worth it or not.

Keep in mind, too, that the MimeParser cannot currently return an instance of a custom MimeMessage subclass, so that makes subclassing MimeMessage a little awkward.

Long-term, I have thought about making it possible to register a MimeMessage subclass on the ParserOptions so that the MimeParser can return custom subclass instances, but I haven't done that yet since I don't know if that's something anyone really cares about. Maybe I should anyway, just for "completeness", but since no one has asked, I haven't bothered.

Those are my thoughts. Hopefully my rambling hasn't been a confusing twisty-turny road, haha!

**Comment by MartijnFLC** [comment]
For me with the adjustments you just made everything is perfect. 

I agree if other classes like MimeParser cannot handle a subclass of MimeMessage, you should not add the virtual method.

The only reason to apply a custom MessageId I can think of is if you want to follow the recommendation of RFC 5322 to always put a domainname on the right side of the @, not the hostname like MimeUtils now does. Due to the fact it is a recommendation and there is a way to specify your own messageid through the headers, I would leave it for now.

Thank you for the great work.
