### ISSUE TITLE
[Question] Detect "aktive" Message from mbox

### ISSUE THREAD

**Issue by wolfgangmauer** [jstedfast/MimeKit#622]
I use Thunderbird with mbox and try to read a local folder(file) like this
```
            var parser = new MimeParser(File.Open(@"....default\Mail\Local Folders\....", FileMode.Open), MimeFormat.Mbox);
            while (!parser.IsEndOfStream)
            {
                var message = parser.ParseMessage();
```
I get a lot more messages than Thunderbird shows in the local folder view, how can I fix this?
Thanks for Help!

**Comment by jstedfast** [comment]
The messages might be marked as "Deleted" in Thunderbird and hidden from your view.

If you "Compact Folders", this should get rid of the deleted messages from the mbox files.

If you don't want to do that, I *think* Thunderbird sets a message header. Try looking at the message headers to see if any of them might be useful. I would *guess* that the header name will be something like `X-Thunderbird-Something` or `X-Mozilla-Something` (maybe `X-Mozilla-Status`?), but other headers like `Status` or `X-Status` may also be used.

Keep in mind that the value may look like hex or base64 blobs. All this means is that the flags are probably an encoded bitfield. What you'll need to do is figure out how to read those headers.

If you reply back to me with a list of potential headers (and their values), I *might* be able to help you narrow it down to the correct one. And once we do that, I *might* be able to give you ideas on how to reverse engineer the value so that you can read it in code and figure out if it has been deleted or not.

**Comment by wolfgangmauer** [comment]
Thank you so much!
If the message.Headers["X-Mozilla-Status"] == "0001", the mail is visible/active in Thunderbird.
Works wonderfully, great job!

**Comment by jstedfast** [comment]
The parser parses the messages in the order that they exist in the mbox file.

You could put them all in an array and write a custom IComparer to sort them in whatever order you want (but keep in mind that MimeMessages can be quite large and having them all in memory might be a bad idea depending on the size of the mbox file).
