### ISSUE TITLE
MailboxAddress TryParse/Parse parsing "correctly" invalid email addresses

### ISSUE THREAD

**Issue by intelartificial** [jstedfast/MimeKit#643]
Hi,

I was building unit testings for my application and noticed that some of the tests were failing due to the fact that MailboxAddress.TryParse("green@hornet", out MailboxAddress address) was returning true and a "valid" MailboxAddress object.

Same with MailBoxAddress.TryParse("smurfette", out MailboxAddress address).

Is it normal? Because both are invalid email addresses based on https://en.wikipedia.org/wiki/Email_address.

Thank you,

**Comment by rufanov** [comment]
RFC-5322 does not require presence of '@' symbol with external domain name in email address - only local-part is required.

So, yes, "smurfette" is actually totally correct e-mail address for current domain.

**Comment by jstedfast** [comment]
`green@hornet` is valid according to the syntax specification because the syntax specification does not require that the domain exists or that the `domain` portion of the addr-spec is a subdomain.

As far as `smurfette`, that *is* invalid according to the syntax, *but* it is a format that has historically been used on UNIX systems when sending mail to another local user.

If you want to not allow `smurfette`, then you can provide a `ParserOptions` that has a [AllowAddressesWithoutDomain](http://www.mimekit.net/docs/html/P_MimeKit_ParserOptions_AllowAddressesWithoutDomain.htm) set to `false`.
