### ISSUE TITLE
InternetAddressList fails to parse valid email addresses when the display name contains unicode (not all cases, unsure what conditions are required), names like ""

### ISSUE THREAD

**Issue by JerryFenghu** [jstedfast/MimeKit#668]
**Describe the bug**
InternetAddressList fails to parse valid email addresses when the display name contains unicode (not all cases, unsure what conditions are required), names like ""

��Ѷ��ҵ����<10000@exmail.weixin.qq.com> you can see it in attach file

[Error parse.zip](https://github.com/jstedfast/MimeKit/files/6322219/Error.parse.zip)

**To Reproduce**
1. Use InternetAddressList parse the ��Ѷ��ҵ����<10000@exmail.weixin.qq.com>(it's in the attach file) fails

**Expected behavior**
InternetAddressList should parse the email successfully

**Comment by jstedfast** [comment]
Seems like it parses it successfully to me. What do you mean by "it fails"?

Do you mean that the `Name` property doesn't contain Chinese characters?

If so, that's because:

1. The email specifications say that headers MUST be in US-ASCII (latest versions of the spec also allow UTF-8)
2. The raw byte sequence in your example message are really GB2312 but can also be cleanly interpreted as UTF-8 (even though it is not UTF-8).

Because of this, MimeKit interprets the byte sequence as UTF-8 and does not fall back to the user-specified fallback charset (which I presume you are setting to gb2312).

The only solution is get the person sending these mails to start using a better mail client that doesn't break the rules.

FWIW, the sending client is also broken in that it does not put a space between the name and `<10000@exmail.weixin.qq.com>` (which is also a syntax error, it's just that MimeKit deals with this error).

**Comment by LeftofZen** [comment]
I found MimeKit gives the same exception parsing standard-ascii `<example@test.com> [displayName]`

**Comment by jstedfast** [comment]
@LeftofZen that's invalid syntax. The display name has to come first.
