### ISSUE TITLE
[MimeKit.MimeMessage]::new() throws an error when using standard library in Net Framework 4.8

### ISSUE THREAD

**Issue by PrzemyslawKlys** [jstedfast/MimeKit#683]
**Describe the bug**
I use your MimeKit/MailKit libraries in [Mailozaurr PowerShell module](https://github.com/EvotecIT/Mailozaurr). So far I've been using NET Standard libraries to support NET Core (PS 6, PS 7) and NET 4.5 library to support PowerShell 5.1. It worked but it was kind of double the amount of megs. So I tried to use NET STandard 2.0 in PowerShell 5.1 which should work just fine (because it's supported) but it throws an error whenever I try to use:

```powershell
[MimeKit.MimeMessage]::new()
```

Error:

```
Exception calling ".ctor" with "0" argument(s): "The type initializer for 'MimeKit.ParserOptions' threw an exception."
At C:\Support\GitHub\Mailozaurr\Public\Send-EmailMessage.ps1:440 char:5
+     $Message = [MimeKit.MimeMessage]::new()
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : TypeInitializationException
```

Do you see any reason why would it throw an error like that? It works fine in PowerShell 6 and 7 so it would seem that MimeKit.ParserOptions could potentially have a code that only works in .NET Core but doesn't work in .NET 4.6.1+

![image](https://user-images.githubusercontent.com/15063294/121784991-7b1ec580-cbb7-11eb-96d9-a761a0d4c617.png)

I can of course use different libraries if NET Framework is used, but it;'s just unnecessary space filler. 

**Platform (please complete the following information):**
 - OS: Windows 10
 - .NET Runtime: 
 - .NET Framework: Net 4.6.2+ (I believe 4.8 or later is currently installed)
 - MimeKit Version: 2.13 but I checked 2.11, and 2.11 - same thing

**Comment by jstedfast** [comment]
ParserOptions is very simple, so I can't think of anything there that would cause problems.

Normally, when a similar exception has occurred for MimeMessage .ctor, it's been related to charset related and it's been a TypeLoadException (or some such) thrown in the CharsetUtils static .ctor

This is because not all character encodings (aka text encodings) are supported by default in .netstandard and it's necessary to pull in additional nugets for the non-unicode character encodings. Or at least that *was* the case with older .netstandard versions. I forget if that's an issue for 2.x.

Do you think it might be possible to get more information, such as line numbers or something?

I wonder if the ParserOptions error is just a side-effect of something else and is therefore a red-herring.

**Comment by PrzemyslawKlys** [comment]
No, no line numbers however:

```powershelll
 [MimeKit.ParserOptions]::new()
```

Gives:

```
Exception calling ".ctor" with "0" argument(s): "The type initializer for 'MimeKit.Utils.CharsetUtils' threw an exception."
At line:1 char:1
+ [MimeKit.ParserOptions]::new()
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : TypeInitializationException
```

**Comment by jstedfast** [comment]
CharsetUtils is an internal class, it's not exposed in the public API.

I suspect this may be where things are breaking in CharsetUtils.cs?

#if NETSTANDARD
			Encoding.RegisterProvider (CodePagesEncodingProvider.Instance);
#endif

**Comment by PrzemyslawKlys** [comment]
I would say so. Any way this can be a workaround? Maybe I'm missing some NuGet?

**Comment by jstedfast** [comment]
I want to say it depends on the [System.Text.Encoding.CodePages](https://www.nuget.org/packages/System.Text.Encoding.CodePages) nuget package, but I'm not 100% positive.

**Comment by PrzemyslawKlys** [comment]
I tried that, it didn't change anything :(

**Comment by jstedfast** [comment]
I'm not sure what else you could try :(

Best I can offer is maybe try adding some logging to the CharsetUtils static .ctor to see if that helps narrow things down.

That class basically tries to load a bunch of widely-used text encodings and maps various aliases to them that are commonly used in mail headers. It tries to catch exceptions, but apparently some exceptions make it out.

**Comment by PrzemyslawKlys** [comment]
I guess I have no other way - I'll try to play with it and add some debugging/try/catches all over the place to find what is actually throwing this. Till then I will use 2 separate sets of libraries.

**Comment by jstedfast** [comment]
If you figure out where in the code an exception is being thrown, let me know and I will help you try to figure out a solution.

**Comment by jstedfast** [comment]
Oh, I bet I know the issue...

I think that Register method was meant to be called from the main program and not a library as part of any initialization.

When that code runs in your .NET 4.8 environment, it throws because .NET 4.7 doesn't have that method - it's only supposed to be called from a .NET Core app.

**Comment by PrzemyslawKlys** [comment]
Is there anything I can do?

**Comment by jstedfast** [comment]
No, I think the solution is for me to remove that line of code from MimeKit - if you want, can you test that theory for me?

If that works, then the next step is for me to write docs and a FAQ about needing to call that method from .NET Core apps manually (since MimeKit won't do it anymore).

Hopefully that won't break too many people, but I think if I'm right about this bug, then it'll be the Right Thing To Do(tm) since your use-case scenario should totally be expected to work.

**Comment by PrzemyslawKlys** [comment]
Yes, lets try to remove that line and see how it goes. Maybe this could be somehow detected that it's running as part of Net Framework or Net Core?

**Comment by jstedfast** [comment]
Did some more digging here...

It looks like the following code should work in .NET >= 4.6 according to the docs.

```csharp
Encoding.RegisterProvider (CodePagesEncodingProvider.Instance);
```

Docs link: https://docs.microsoft.com/en-us/dotnet/api/system.text.encoding.registerprovider?view=netframework-4.6

```
Starting with .NET Framework 4.6, .NET Framework includes one encoding provider, CodePagesEncodingProvider, that makes the encodings available that are present in the full .NET Framework but are not available in the Universal Windows Platform. By default, the Universal Windows Platform only supports the Unicode encodings, ASCII, and code page 28591.
```

I re-read the comments above and I think I thought that this was being hit in .NET 4.8, but now that I just re-read again, it's .NET 4.5? Is that right? If so, then this is still likely the culprit.

**Comment by PrzemyslawKlys** [comment]
The minimal version for Net Standard 2.0 is 4.6.1 and this is what I "support". I expect PowerShell 5.1 users to at least install 4.6.1 net framework but it should work for 4.8 as well. 

I have 4.8 installed and it throws errors.

**Comment by jstedfast** [comment]
Ah, interesting...

**Comment by jstedfast** [comment]
This should be fixed in 2.14.0

**Comment by PrzemyslawKlys** [comment]
Will test it out. Thank you ;)

**Comment by danielchent** [comment]
Hi
my development environment
windows 10, powershell 7, visual studio code / visual studio
i installed the module according to your instructions.
i copied the  send email example that you have here
i keep getting the folowing error:  " Unable to find type [MimeKit.MimeMessage] "
can you help?
thank you

**Comment by PrzemyslawKlys** [comment]
You should take this into Mailozaurr repo and provide what exactly you're using, which version and when you get the error. 

This is probably not proper way to report an issue.

**Comment by Chaos02** [comment]
> Hi my development environment windows 10, powershell 7, visual studio code / visual studio i installed the module according to your instructions. i copied the send email example that you have here i keep getting the folowing error: " Unable to find type [MimeKit.MimeMessage] " can you help? thank you

Hi - This is probably caused by your Wrong Syntax.
It should be along the lines of:
```ps
$message = New-Object MimeKit.MimeMessage
```
You can type `[MimeKit.MimeMessage].` into the powershell and hit tab to explore the object. Otherwise - loose the brackets!

**Comment by PrzemyslawKlys** [comment]
Pretty sure the brackets work perfectly fine. New-Object is the old way (and slower) to work with types in PowerShell. 

![image](https://user-images.githubusercontent.com/15063294/213133086-c4555c92-b900-4aa5-9418-3e3d98c85e3e.png)

**Comment by Chaos02** [comment]
Regarding my issue:
This Issue still exists!
The Missing Latin1 support is one thing (I was able to solve by loading System.Text.Encoding from ASP.NET > V5)
However, there still persists another issue I cannot get solved:

When creating a new MimeMessage via `New-Object MimeKit.MimeMessage` I get the first-mentioned MimeKit.ParserOptions threw an exception.

Through the Automatic $Error variable (Which for some reason now is empty, even after a reboot) I recursively doug down in the .Innerexceptions property and ran a .ToString() on each of them, to get the exception message.
because of the weird $Error behaviour I will need to quote from memory as best as I can:
> `"System.Reflection.ConstructorInfo" in "System.Runtime" could not be loaded` with a HResult of 0x80131515

I think this string is missing the System.Runtime assembly infos like Version and PublicKey but I had made sure before that they matched:
When viewing the AppDomain assemblies (via `[System.AppDomain]::CurrentDomain.GetAssemblies() | Where-Object Location | Sort-Object -Property FullName | Select-Object -Property FullName, Location, GlobalAssemblyCache, IsFullyTrusted | Out-GridView`)
I can see both MailKit/MimeKit DLLs loaded. Both are fully trusted.
I have also tried (additionally) loading the System.Reflection and System.Runtime DLLs from the ASP(?).NET 7 binary package. Both load with success but it doesn't help.

What I also made sure is that the Project I'm working on sits locally, to circumvent issues (TypeLoadExceptions) i got earlier.

At this point I've googled everything and doug deeply into it until my search results consistently only had about 2 entries.
Now I've desperately found this old thread which seems to be only half solved to me.

I've obtained `MailKit.dll` and `MimeKit.dll` `v3.4.3.0` via the NuGet online repo and extracted the file for .NET 6 from the .nupkg archives.
I'm on Windows 11, developing a PowerShell (at this point more C#) (gui) application and have `.NET SDK 7.0.102` and `ASP.NET Core 7.0.2`, aswell as `Windows Desktop Runtime 7.0.2` installed to try solve this issue.

**Comment by PrzemyslawKlys** [comment]
There's few more DLLs that are required for things to just work:

![image](https://user-images.githubusercontent.com/15063294/213145125-b8dd1d30-eb24-4423-be64-4e611185a8f9.png)

Default = 5.1, Core = PS7+

https://github.com/EvotecIT/Mailozaurr/tree/master/Lib you can see those files here. If you load them up it will work.

**Comment by Chaos02** [comment]
Is this for Mailozaurr only or just to use MailKit successfully?
Incase MailKit:
ouhh damn I totally didn't find this information in the nuGet dependencies or webpage..
Please make it more obvious for next time! ;)
Until then I'll test it out! Thank you!!

**Comment by PrzemyslawKlys** [comment]
Mailozaurr works with Mailkit/MimeKit. DNSClient, EmailValidation and Google* are not needed, but the rest of it pretty much yes

**Comment by Chaos02** [comment]
Nope, still same results.
However I was now able to copy a full stacktrace: (Note end of first line!)
```
System.Management.Automation.MethodInvocationException: Ausnahme beim Aufrufen von ".ctor" mit 0 Argument(en):  "Der Typeninitialisierer für "MimeKit.ParserOptions" hat eine Ausnahme verursacht." ---> System.TypeInitializationException: Der Typeninitialisierer für "MimeKit.ParserOptions" hat eine Ausnahme verursacht. ---> System.TypeLoadException: Der Typ "System.Reflection.ConstructorInfo" in der Assembly "System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" konnte nicht geladen werden.
   bei MimeKit.ParserOptions..ctor()
   bei MimeKit.ParserOptions..cctor()
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei MimeKit.MimeMessage..ctor()
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei System.Management.Automation.DotNetAdapter.AuxiliaryConstructorInvoke(MethodInformation methodInformation, Object[] arguments, Object[] originalArguments)
   bei System.Management.Automation.DotNetAdapter.ConstructorInvokeDotNet(Type type, ConstructorInfo[] constructors, Object[] arguments)
   bei Microsoft.PowerShell.Commands.NewObjectCommand.CallConstructor(Type type, ConstructorInfo[] constructors, Object[] args)
```
Sorry for it being german ^^' 
the HResult of the TypeLoadException is `0x80131501`.
BTW same result when using `[MimeKit.MimeMessage]::new()`

**Comment by PrzemyslawKlys** [comment]
Why dont you use Mailozaur?

**Comment by Chaos02** [comment]
> Why dont you use Mailozaur?

II haven't looked enough into Mailozaur as a viable solution yet - My requirements are:
- Fast API interface
- Lightweight
- adaptable

As far as I've looked, Mailozaurr is an incredibly complex solution and would probably run into the same error I have on my machine because it also uses `[MimeKit.MimeMessage]::new()`

**Comment by PrzemyslawKlys** [comment]
well have you tried installing Mailozaurr and seeing if you have that error? If not - you can just use "native" mailkit/mimekit with it as well. Just because the functions simplify things you don't want doesn't mean you have to use them.

**Comment by jstedfast** [comment]
The dll that has been the cause of most of the reported TypeLoadExceptions over the past 6+ months has been System.Runtime.CompilerServices.Unsafe. MimeKit no longer event attempts to load System.Text.Encoding.CodePages anymore for similar reasons.

Apparently there is/was a bug in the standard MSBuild targets that incorrectly resolved which version of that dll to bundle in the app directory if multiple nugets depended on different versions and also incorrectly populated the assembly mappings.

Essentially, there seems to be no way for me to solve the issue without dropping the dependency completely.

**Comment by jstedfast** [comment]
@PrzemyslawKlys Yea, I think in all of the cases so far where someone is getting a TypeLoadException with MimeKit now (typically the Unsafe.dll), it is usually because their project is also depending on another nuget which depends on a *different* version of the Unsafe.dll.

With that in mind, I had bumped the Unsafe.dll dependency to 6.0.0 instead of using an old version, this way it would be easier to make everything work. Now users just need to edit their own app.config and create the mapping (or let VS do it).

**Comment by Chaos02** [comment]
@PrzemyslawKlys I have tested Mailozaurr and it does (for some magical reason) not have any issues with MimeKit::new()...
However it lacks the RTF support - Shall I open a Ticket?
It would also be great if I could send batches of mails from the same account with some shared attachments but an individual one per mail (I already had built the logic for this but since MimeKit troubles me...)
If it takes even one second per mail that is too long.

**Comment by PrzemyslawKlys** [comment]
You could always add RTF support to mailozaurr - make a PR - it's 5 lines of code. It already supports attachments and has all the logic so it's as easy as adding small feature. 

If the server is fast it send an email in 250ms or so
