### ISSUE TITLE
Get files from MimeMessage

### ISSUE THREAD

**Issue by CristinaHP** [jstedfast/MimeKit#709]
Hi, I want to get all files (attachments and linked resources) from a MimeMessage. I know I can get attachments like this:

`var attachments = email.Attachments;`

But there isn't something similar for linked resources, so I tried something like:

`var resources = email.BodyParts.Where(x => x.ContentType.MediaType != "text");`

But then I figured that a text/something file can also be an attachment so that is not valid for what I want.
So how can I get all the attachments and linked resources?

**Comment by jstedfast** [comment]
For that, you'll need to understand the structure of MIME messages and likely implement a MimeVIsitor or else use the MimeIterator to collect the MIME parts that you want.

You won't be able to use MimeMessage.BodyParts because you won't have the needed context.

Generally, the images that are referenced by HTML message bodies are contained within a multipart/related (which the HTML part is also a child of).

MimeKit's MultipartRelated class has a property called [Root](http://www.mimekit.net/docs/html/P_MimeKit_MultipartRelated_Root.htm) which maps to the root "document" which references all of the other "documents" within it. In the practical world, the Root is the HTML body while all of the other parts are the images/etc that will be referenced by the HTML.

You could probably start with the HtmlPreviewVisitor class that you'll find in the docs for the Root property.

**Comment by CristinaHP** [comment]
Thanks!

So, maybe a possible solution with a MimeIterator would be to iterate over the MIME parts. And when I find a MultipartRelated, get all the parts inside it that aren't "text/html", as a MultipartRelated would only have one HTML part, hasn't it?

**Comment by jstedfast** [comment]
You've got it pretty close, but what I would recommend is that you iterate over the MultipartRelated children and check if they are the `Root`.

```csharp
foreach (var child in multipartRelated) {
    if (child == multipartRelated.Root)
        continue;

    resources.Add (child);
}
```

**Comment by CristinaHP** [comment]
Great! Thank you!
