### ISSUE TITLE
Problem with MineKit 3.2.0 on a .net Framework that uses a version of System.Text.Encoding.CodePages that isn't 4.1.1.0

### ISSUE THREAD

**Issue by XavierDa** [jstedfast/MimeKit#785]
**Describe the bug**

When updating to the lastest Mimekit version i have an issue System.Text.Encoding.CodePages, when i try to use dkim signer i got the following issue, but i have another library that links to System.Text.Encoding.CodePages 6.0.0

System.TypeInitializationException: The type initializer for 'MimeKit.ParserOptions' threw an exception.
System.TypeInitializationException: The type initializer for 'MimeKit.Utils.CharsetUtils' threw an exception.
System.IO.FileNotFoundException: Could not load file or assembly 'System.Text.Encoding.CodePages, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
at MimeKit.Utils.CharsetUtils..cctor()

**Platform (please complete the following information):**
 - OS: Windows, inside an exchange transport agent
 - .NET Runtime: 4.6.2
 - .NET Framework: .Net 4.6.2
 - MimeKit Version: 3.2.0

**To Reproduce**
1. Create a project with a linked package that use a recent System.Text.Encoding.CodePages (other than 4.1.1.0)
2. Import mimekit 3.2.0
3. UseDkimSigner

**Expected behavior**
When using 3.1.1 or below i don't have the issue so it seems something changed with this library, maybe a fixed version on build ?

**Code Snippets**
```csharp
  DkimSigner dkimSigner = new DkimSigner(GetSelectedCertificate(), domain, selector, algorithm)
  {
      BodyCanonicalizationAlgorithm = canonicalization,
      HeaderCanonicalizationAlgorithm = canonicalization
  };
dkimSigner.Sign(message, headers);
```

**Comment by XavierDa** [comment]
My main issue is that i have it imported from another nuget package with version 6.0.0 so when Mimekit tries to load its own version it fails.

**Comment by XavierDa** [comment]
We recently migrated all our internal nuget packages and app to .net 6 /.net standard 2.0 from .net core 3.1 / .net framework multi targeting and we updated our packages back then.

But one thing strange is that it doesn't do auto binding redirect (and in your csproj you only set the minimal version so... it should works) , guess the problem must be on my side / transport agent side then. Sorry for the noise.

**Comment by jstedfast** [comment]
In your original comment, you started you are using .NET Framework v4.6.2, but your latest comment says net6?

I'm confused.

**Comment by Hurricane31337** [comment]
We have exactly the same problem. We use both MailKit and MimeKit 3.2.0 as NuGet package. Which version of System.Text.Encoding.CodePages should we include? Fully uninstalling it (for referencing 4.1.1 manually) is not even possible, because NuGet knows that it's a requirement for MimeKit. Additionally, 4.1.1 is not even available for download by the NuGet store.
I guess MimeKit referencing the latest version 6.0.0 should be the best approach, because most people that use the latest and greatest MailKit and MimeKit (updating regularly via NuGet) will also use the latest and greatest System.Text.Encoding.CodePages.

If every library was updating their NuGet package regularly and used the latest available version of a reference, version conflicts like this shouldn't be an issue.

**Comment by jstedfast** [comment]
@Hurricane31337 MimeKit depends on System.Text.Encoding.CodePages v4.5.1, not v4.1.1, so I'm not sure where the reference to v4.1.1 is coming from.

It's usually not a good idea for libraries like this to always depend on the latest of other packages because there may be breakages in the newer versions or reasons that consumers of this library cannot update.

Also, the way these dependencies are *supposed* to work is that the versions they depend on are the *minimal* version required, not an *absolute* version, which should make it possible for you to use v6.0.0 and everything should theoretically work.

**Comment by Hurricane31337** [comment]
Well, after updating to 3.2.0 the problem arised and we were actually using 6.0.0. We got exceptions that it wasn’t able to find System.Text.Encoding.CodePages 4.1.1.

What’s the disadvantage for using System.Reflection? In our case, everything was just fine using MimeKit 3.1.1 and System.Text.Encoding.CodePages 6.0.0.

**Comment by jstedfast** [comment]
@Hurricane31337  if you try:

```
Install-Package MimeKit -Version 3.2.0.458 -Source https://www.myget.org/F/mimekit/api/v3/index.json
```

Do you run into the same issues as the guy in the issue linked above?

**Comment by jstedfast** [comment]
That package bumps the System.Text.Encoding.CodePages package dependency to 6.0.0

**Comment by jstedfast** [comment]
@XavierDa In your last comment, you concluded the issue was on your side but didn't expand on that. Did you figure out the issue on your side and solve it somehow? Could you share what you found?

**Comment by jstedfast** [comment]
Seems like what you guys need to do is add binding redirects to your app.config:

https://stackoverflow.com/questions/62764744/could-not-load-file-or-assembly-system-runtime-compilerservices-unsafe
