### ISSUE TITLE
Attachments with duplicate names are not parsed correctly

### ISSUE THREAD

**Issue by smddzcy** [jstedfast/MimeKit#800]
**Describe the bug**
When Mimekit parses an email that has multiple attachments with duplicate names, it just parses 1 attachment and ignores the other ones.

Example with attachments having the same name but different attachment IDs:

<img width="817" alt="image" src="https://user-images.githubusercontent.com/13895224/172932042-65ad9054-8937-428a-86d7-1d5952ffb54b.png">

<img width="804" alt="image" src="https://user-images.githubusercontent.com/13895224/172932070-c766885e-2f79-437b-be18-817a2a9de3b2.png">

My mail client, Spark, parses them just fine:
<img width="499" alt="image" src="https://user-images.githubusercontent.com/13895224/172932188-094f1aca-0b40-42ad-8081-6423b1908a10.png">

Mailkit parses just a single attachment:

<img width="1010" alt="image" src="https://user-images.githubusercontent.com/13895224/172932347-b9900b94-9624-4a97-8b54-76c744b60e3f.png">

**Platform (please complete the following information):**
 - OS: MacOS 12.4
 - .NET Runtime: .NET 6.0.300
 - .NET Framework: .NET Core
 - MimeKit Version: 3.2.0

**To Reproduce**
1. Send an email that has multiple attachments with the same name (e.g. `abc.png`)
2. Parse the email with Mailkit / Mimekit - it only parses one of them

**Expected behavior**
Mimekit should parse all files correctly just like other mail clients.

**Comment by jstedfast** [comment]
The MessageSummary.Body structure does not come from MimeKit's MIME parser, it comes from the IMAP server's MIME parser.

It's possible that the MailKit code that parses the LISP-expression containing the serialized MIME structure parsed by the IMAP server is faulty, but I can't know that without a protocol log.

**Comment by jstedfast** [comment]
I can't reproduce this.

This is probably a bug in your IMAP server.

I'd be happy to dig into this more if you provider either a test message that MimeKit fails to parse or a [protocol log](https://github.com/jstedfast/MailKit/blob/master/FAQ.md#ProtocolLog) from a MailKit session where this failed reading the message via IMAP.

**Comment by jstedfast** [comment]
It's fine to either anonymize it or you can email it to me personally at jestedfa@microsoft.com. I would recommend archiving the message in a zip file because Outlook/Exchange tend to modify message attachments.

**Comment by jstedfast** [comment]
Oh, and yes, if the problem is with the IMAP server, then I would expect other clients to also fail to see the attachments... assuming that they are using the FETCH command to obtain the BODY property of the message(s).

I'd be curious to know if there is a difference between using MessageSummaryItems.Body and MessageSUmmaryItems.BodyStructure in your case.

For more on the difference, see https://datatracker.ietf.org/doc/html/rfc3501#section-6.4.5

In my own personal experience, BODYSTRUCTURE tends to be more reliable.

FWIW, Body and BodyStructure return similar data. The main difference between Body and BodyStructure is that BodyStructure returns Content-Type and Content-Disposition parameter values, where Body won't.

**Comment by smddzcy** [comment]
I just sent the IMAP log to your email. Indeed, the log displays only a single file, but we're using the Mailkit's IMAP client, so I think it's a bug in Mailkit's IMAP client rather than Mimekit. 

> What happens if you iterate over the message's BodyParts? Does that contain all of the parts?

It has a single text part and an image file part.

**Comment by jstedfast** [comment]
I can move the issue over to MailKit (nifty feature that GitHub has). But let me take a look first.

**Comment by smddzcy** [comment]
Thanks a lot for the detailed investigation.

The email contains 3 different files with the same name, I just forwarded the email to you so you can have a better look.

**Comment by jstedfast** [comment]
The message you forwarded to me seems to have a different subject compared to the one in the log. Are you sure your code is fetching the right message?

**Comment by jstedfast** [comment]
Ok.

**Comment by smddzcy** [comment]
But if the problem is with the IMAP server, shouldn’t other clients also have issues? Gmail, Spark, Outlook, all display the attachments just fine.

Also I just forwarded the email to another IMAP server and Mailkit still cannot detect the attachments, even though Spark detects them.

**Comment by jstedfast** [comment]
How are you "detecting" attachments? Are you just counting the number of items in MimeMessage.Attachments?

This is a very common hang-up that a lot of developers get confused by.

What a mail client like Outlook shows you as an attachment and what is defined as an attachment in MIME are not necessarily the same thing.

MimeKit only includes MIME parts with a `Content-Disposition: attachment` header. If the Content-Disposition header is missing or the value is `inline` instead of `attachment`, then it won't be included in the MimeMessage.Attachments list.

You will have to iterate over the MimeMessage.BodyParts using your own heuristic for deciding if something is an attachment or not.
