### ISSUE TITLE
Message-ID or Message-Id

### ISSUE THREAD

**Issue by Przemol-PL** [jstedfast/MimeKit#803]
Hello Jeff,

first of all thank you for this project and MailKit as well. It's a pleasure to use it.

Back to the topic, I've had an issue earlier with sending to gmail and receiving 5.7.1, after research I find out that it's because I'am adding to header field Message-ID and at the same time MimeKit adds automatically Message-Id. It propably causes some validator at gmail to reject such messages (duplicates). I use only MessageId setter now and it works fine (without bounces). I've verified my old project based on .Net smtp implementation, gmail account and outlook and all of these adds Message-ID. I can't find in Rfc's information that it can be named different than Message-ID however looks like software really doesn't matter which version is used. I would like to ask you as to an expert what do you think about this difference and why MimeKit uses Message-Id? Is there any official information that it really doesn't matter letter size and I can create even meSsAgE-iD? I was trying to somehow replace it in mimekit but looks like it's not possible now, maybe it should for rfc compliance.

Regards
Przemek

**Comment by jstedfast** [comment]
Header names are case-insensitive.

It's not particularly obvious in the specifications, but [rfc2822, section 1.2.2](https://datatracker.ietf.org/doc/html/rfc2822#section-1.2.2) (and [rfc5322, section 1.2.2](https://datatracker.ietf.org/doc/html/rfc5322#section-1.2.2) which supersedes it) both state:

> This specification uses the Augmented Backus-Naur Form (ABNF)
> [[RFC5234](https://datatracker.ietf.org/doc/html/rfc5234)] notation for the formal definitions of the syntax of
> messages.  Characters will be specified either by a decimal value
> (e.g., the value %d65 for uppercase A and %d97 for lowercase A) or by
> a case-insensitive literal value enclosed in quotation marks (e.g.,
> "A" for either uppercase or lowercase A).

If we then look at the definition of the Message-ID header, for example, we see the syntax definition is defined as:

```
message-id      =   "Message-ID:" msg-id CRLF
```

And so, because these RFCs use the ABNF form, "Message-ID:" can be written as "messAGE-ID:" or "mEsSaGe-iD:", etc.

FWIW, if you want to override the capitalization of "Message-ID", you can use the [HeaderList.Replace](http://mimekit.net/docs/html/Overload_MimeKit_HeaderList_Replace.htm) method(s):

```csharp
var message = new MimeMessage ();
message.Headers.Replace ("Message-ID", "<" + MimeUtils.GenerateMessageId () + ">");
```

The Replace() methods will remove any existing header of that name and replace it with the new header (using the capitalization in the field name that you specify).

If the header you are trying to replace doesn't exist, it will work the same as Add().
