### ISSUE TITLE
HTML entity for carriage return is being encoded

### ISSUE THREAD

**Issue by SenaraW** [jstedfast/MimeKit#808]
**Describe the bug**
When you convert a mimetext containing \&\#13; it will be encoded an additional time, resulting in the output being  \&amp;\#13;
Other html entities seem to not be affected.

**Platform (please complete the following information):**
 - OS: Windows
 - .NET Runtime: CLR
 - .NET Framework: .NET 4.8
 - MimeKit Version: 3.3.0

**To Reproduce**
Convert the following mimetext to html:

```
Content-Type: text/html; charset=utf-8

<html>
<body>
I'm on holiday until&nbsp; June 17, 2022.&#13;
</body>
</html>
```

This will result in the following html:

```
<html>
<body oncontextmenu="return false;">
I&#39;m on holiday until&#160; June 17, 2022.&amp;#13;
</body>
</html>
```

**Expected behavior**
Output should be \&\#13;

**Comment by jstedfast** [comment]
How are you converting?

**Comment by SenaraW** [comment]
Here's a small test program to reproduce the bug: [HTMLEntityTest.zip](https://github.com/jstedfast/MimeKit/files/8977035/HTMLEntityTest.zip) 
It converts the above mentioned mime text and converts it to html and outputs it to the textbox.

I hope this helps!

**Comment by jstedfast** [comment]
Okay, so the problem is that according to the W3 HTML5 specification, &#13; is a parse error.

Note here: https://dev.w3.org/html5/spec-LC/tokenization.html#consume-a-character-reference

> ... If the number is in the range 0x0001 to 0x0008, 0x000E to 0x001F, 0x007F to 0x009F, 0xFDD0 to 0xFDEF...
> then this is a [parse error](https://dev.w3.org/html5/spec-LC/parsing.html#parse-error).

When MimeKit's HtmlTokenizer encounters a parse error, it just emits the raw entity instead of decoding it and when the HtmlToHtml converter writes out the tokens it gets, the token re-encodes the cdata, therefore creating this issue.

I think the solution is to tell the tokenizer not to decode character references which will resolve this.

**Comment by jstedfast** [comment]
MimeKit v3.4.0 has been released with this fix.
