### ISSUE TITLE
There is one more unexpected  space(' ') appear in the attachment name after parsing

### ISSUE THREAD

**Issue by kenizhou** [jstedfast/MimeKit#809]
**Describe the bug**
I am using Lotus Notes to extract an eml file , and found the "Content-Disposition" will be wrapped into two lines and there is a TAB('\t') appended in the second line when the attachment name is long.   

Please see the sample below:
![image](https://user-images.githubusercontent.com/614477/175932959-9a2efdb4-1890-4710-8212-573d6d908b01.png)

After parsing by using the mimekit, the TAB '\t' will become a Space (' ')

![image](https://user-images.githubusercontent.com/614477/175933314-2a9b212e-e7d4-4f49-ba45-41fb62938d12.png)

I am not sure if it is because Lotus Notes did not follow the standard.

Thanks in advance!

**Comment by kenizhou** [comment]
thanks very much!

**Comment by kenizhou** [comment]
Thanks very much! 
Just pull the source down and have a testing, the workaround works fine for me.  
but seems the enhancement caused something other issues. there are many unreadable characters appear in the mailbody: 

![image](https://user-images.githubusercontent.com/614477/176768406-ec8bb659-b5f9-40b2-9c07-caf2f82e3927.png)

**Comment by jstedfast** [comment]
Unfortunately your screenshot doesn't give me much context. What am I looking at? Are those header values? Or is that the content of a TextPart? Or?

**Comment by kenizhou** [comment]
The content of the textpart.
![image](https://user-images.githubusercontent.com/614477/176782733-99399532-c390-4f1e-afcc-12341968a796.png)
![image](https://user-images.githubusercontent.com/614477/176782996-0a78f90a-b637-4b82-b301-6dc60e0f85ec.png)
![image](https://user-images.githubusercontent.com/614477/176783572-5f7f0fd7-a82c-45ec-b640-a4a7238dd377.png)

**Comment by jstedfast** [comment]
Are you using a MimeKit.Text.HtmlToHtml text converter?

**Comment by kenizhou** [comment]
Yes, I am using the "HtmlPreviewVisitor" of your sample source.

**Comment by jstedfast** [comment]
Thanks. I'll look into this bug which I think I probably introduced a few days ago in the converter.

**Comment by kenizhou** [comment]
Noted, thanks!

**Comment by jstedfast** [comment]
In the original message, what are the `<meta>` tags? And what is the charset specified in the Content-Type header?

**Comment by jstedfast** [comment]
Here's what I *think* the problem is:

* The old HtmlToHtml converter used to ask the HtmlTokenizer to decode character references and then it would encode any character that needed to be encoded (whether it was originally encoded or not) when it wrote it back out. This is part of what caused issue #808 (the other part is that &#13; is invalid even though you'd think it would decode to `\r`, the HTML5 specification says that should throw a parse error).
* The new HtmlToHtml logic tells the HtmlTokenizer *not* to decode character references and passes the raw data through to the output stream unchanged (other than the conversion to unicode) which is arguably a better strategy as it is less likely to alter the meaning of the original HTML if MimeKit has any bugs in the HTML writer.

Why is that a problem? Well, it means that the output of the conversion is no longer guaranteed to be ASCII which means that the charset declared in the `<meta>` tags is going to be needed by the HTML rendering engine.

Depending on how you pass the output along to the IE11 browser window, this can make a big difference.

In my [MessageReader](https://github.com/jstedfast/MimeKit/tree/master/samples/MessageReader) sample, the code gets the converted string and sets it on the browser control via the [DocumentText](https://github.com/jstedfast/MimeKit/blob/master/samples/MessageReader/MessageReader/MessageViewWindow.cs#L68) property which means that the browser control knows that the text it is getting is *already* a string (or, if it's a native control, it'd be converted to UTF-8 or UTF-16) and so no charset conversion would be needed.

If the browser control/window loads the converted HTML via a Stream (e.g. by reading it from a saved output file), then it will end up using the `<meta>` tags to determine what charset to use to convert it into UTF-8 or UTF-16 (whichever the browser control uses internally), so it is very important that you save the file using the correct System.Text.Encoding and not blindly save the content as UTF-8 (which is the default for File.WriteAllText() and for any TextWriter implementations that you might use).

I'm thinking that the best way to fix this is to continue saving the content to a file using UTF-8 but change the code in the HtmlTagCallback to modify the `<meta>` tags in order to override any charset values specified in them.

```csharp
void HtmlTagCallback (HtmlTagContext ctx, HtmlWriter htmlWriter)
{
	if (ctx.TagId == HtmlTagId.Meta && !ctx.IsEndTag) {
		bool isContentType = false;

		ctx.WriteTag (htmlWriter, false);

		// replace charsets with "utf-8" since our output will be in utf-8 (and not whatever the original charset was)
		foreach (var attribute in ctx.Attributes) {
			if (attribute.Id == HtmlAttributeId.Charset) {
				htmlWriter.WriteAttributeName (attribute.Name);
				htmlWriter.WriteAttributeValue ("utf-8");
			} else if (isContentType && attribute.Id == HtmlAttributeId.Content) {
				htmlWriter.WriteAttributeName (attribute.Name);
				htmlWriter.WriteAttributeValue ("text/html; charset=utf-8");
			} else {
				if (attribute.Id == HtmlAttributeId.HttpEquiv && attribute.Value != null
					&& attribute.Value.Equals ("Content-Type", StringComparison.OrdinalIgnoreCase))
					isContentType = true;

				htmlWriter.WriteAttribute (attribute);
			}
		}
	} else if (ctx.TagId == HtmlTagId.Image && !ctx.IsEndTag && stack.Count > 0) {
		ctx.WriteTag (htmlWriter, false);

		// replace the src attribute with a "data:" URL
		foreach (var attribute in ctx.Attributes) {
			if (attribute.Id == HtmlAttributeId.Src) {
				if (!TryGetImage (attribute.Value, out var image)) {
					htmlWriter.WriteAttribute (attribute);
					continue;
				}

				var dataUri = GetDataUri (image);

				htmlWriter.WriteAttributeName (attribute.Name);
				htmlWriter.WriteAttributeValue (dataUri);
			} else {
				htmlWriter.WriteAttribute (attribute);
			}
		}
	} else if (ctx.TagId == HtmlTagId.Body && !ctx.IsEndTag) {
		ctx.WriteTag (htmlWriter, false);

		// add and/or replace oncontextmenu="return false;"
		foreach (var attribute in ctx.Attributes) {
			if (attribute.Name.Equals ("oncontextmenu", StringComparison.OrdinalIgnoreCase))
				continue;

			htmlWriter.WriteAttribute (attribute);
		}

		htmlWriter.WriteAttribute ("oncontextmenu", "return false;");
	} else {
		// pass the tag through to the output
		ctx.WriteTag (htmlWriter, true);
	}
}
```

**Comment by jstedfast** [comment]
MimeKit v3.4.0 has been released with this fix.
