### ISSUE TITLE
Could not load file or assembly 'System.Text.Encoding.CodePages, Version=4.1.1.0, Culture=neutral, 

### ISSUE THREAD

**Issue by Sicos1977** [jstedfast/MimeKit#816]
Since upgrading to the latest version with nuget I keep getting the error below

The type initializer for 'MimeKit.ParserOptions' threw an exception.
The type initializer for 'MimeKit.Utils.CharsetUtils' threw an exception.
Could not load file or assembly 'System.Text.Encoding.CodePages, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

I used a redirect to point to a newer version but that does not solve the problem, any ideas how to fix this?

I'm using MimeKit 3.3.0 and .NET framework 4.8

```xml
<dependentAssembly>
	<assemblyIdentity name="System.Text.Encoding.CodePages" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
	<bindingRedirect oldVersion="0.0.0.0-6.0.0.0" newVersion="6.0.0.0" />
</dependentAssembly>
```

**Comment by jstedfast** [comment]
This has been a recurring problem with depending on System.Text.Encoding.CodePages :-(

Some people seem to run into this issue while others don't have a problem.

What is even odder is that neither the nuspec files nor the csproj files have a dependency on v4.1.1.0 (they depend on v4.5 I think), so I also have no idea where that version is coming from.

I might have to drop it as a dependency and just tell people that they need to initialize their encodings themselves (instead of having MimeKit do it).

I've tried solving it by bumping the dependency to v6.0.0 and that still doesn't fix it: https://github.com/jstedfast/MimeKit/issues/792

**Comment by Sicos1977** [comment]
I just cloned your repro but that one is still pointing to 4.5.1

![image](https://user-images.githubusercontent.com/6692947/177338540-b6c4a7b7-a58f-4f0b-b095-579aba64be9b.png)

**Comment by jstedfast** [comment]
Yea, I reverted the 6.0.0 change once someone tested it and got a new error (also about another library not being v6.0.0).

**Comment by Sicos1977** [comment]
I'm going to try your fix you did just a few minutes ago to see if that solves my problem because even after rebuilding mimekit with 6.0.0 is still is complaining about version 4.1.0.0 ... it is probably a dependcy somewhere else

It is weird though that I can't get it resolved with a binding redirect.

**Comment by jstedfast** [comment]
Could be? I honestly don't know

**Comment by jstedfast** [comment]
That's the same issue the other person hit in issue #792

**Comment by jstedfast** [comment]
Theory:

What if the problem is because I used different dependency versions for net4x vs netstandard vs net5.0 vs net6.0?

Could the compiler being referencing wrong assembly versions?

**Comment by Sicos1977** [comment]
I cant just replace the unsafe assembly because I then break something else
There is also a binding redirect for it

			<dependentAssembly>
				<assemblyIdentity name="System.Runtime.CompilerServices.Unsafe" publicKeyToken="b03f5f7f11d50a3a" culture="neutral"/>
				<bindingRedirect oldVersion="0.0.0.0-6.0.0.0" newVersion="6.0.0.0"/>
			</dependentAssembly>

**Comment by jstedfast** [comment]
What I don't understand is why I am not hitting this when I use net48

**Comment by Sicos1977** [comment]
I also see after modifying the project file that the correct version is placed in the build output folder. Before that it was using an older version

I have dutch date formats :-)

![image](https://user-images.githubusercontent.com/6692947/177344509-8dffe3d7-2414-407f-8f6b-c04c29b212ab.png)

**Comment by Sicos1977** [comment]
I add unsafe version 6.0.0.0 as a nuget reference. This is the error I get now

![image](https://user-images.githubusercontent.com/6692947/177348587-ea029966-b241-4043-8bea-ee24552f34e4.png)

**Comment by Sicos1977** [comment]
I reverted to mailkit 3.1.0 after that everything started working again, from 3.2.0 and higher I keep hitting the same error and that drove me nuts after a few hours so I guess I will be stuck at version 3.1.0

**Comment by jstedfast** [comment]
3.2 is when MimeKit started using `Span<T>`

**Comment by Sicos1977** [comment]
Okey... I don't know if it makes any differences but the code that is using MimeKit is running in 32 bits mode because it is a somewhat older program written in an acient language.

I have no problems with MailKit 3.3.0 but I guess that that one isn't using `Span<T>`

**Comment by Sicos1977** [comment]
Microsoft also uses very strange version numbers for the unsafe assemblies. see this --> https://stackoverflow.com/questions/62764744/could-not-load-file-or-assembly-system-runtime-compilerservices-unsafe

**Comment by jstedfast** [comment]
Do you have any sort of runtime restrictions enabled? I'm not sure how/where to set them, but if your system is locked down such that unsafe code is not allowed, that might explain this (for example).

**Comment by Sicos1977** [comment]
No I have not

**Comment by jstedfast** [comment]
This is frustrating because it clearly works in the unit tests which target net48

**Comment by JuergenAuer** [comment]
I have a "hand-written .NET Web-application", developed .NET1.1, started .NET2, now .NET.4, online since 2006, only own code and standard-.NET libraries. Written with TextPad, no IDE, compiled via cmd with a list of dependencies, a small number of files. A lot of use of SmtpClient + MailMessage.

Found "We don't recommend that you use the SmtpClient class for new development because SmtpClient doesn't support many modern protocols" ( https://docs.microsoft.com/en-us/dotnet/api/system.net.mail.smtpclient?view=net-6.0 ).

Tried to install and use MimeKit.

PowerShell install didn't work - Dependency-loop. Oh.

Used NuGet, renamed the package, unzipped. Tried to use (Application.exe.config - tests only local)

```
         <dependentAssembly>
            <assemblyIdentity name="MimeKit"
                              publicKeyToken="bede1c8a46c66814"
                              culture="neutral" />
            <codeBase version="3.3.0.0"

                      href="file://g:/nuget/projects/MimeKit/MimeKit.3.3.0/lib/net48/mimekit.dll"/>
         </dependentAssembly>
```

then added the next "not found file". 6 additional DLL are required (+ MimeKit and MailKit).

Result: A StackOverflow starting the test application. "Not Found" or StackOverflow - excellent.

Solution. Copied all of these files (selected net46 - net48) in a single, separated folder (completely separated from the nuget folder), used a modified config file (see below) or copy all files in the .\bin - directory. That works, one week online. Online - all files in the .\bin, without any problem / loop. Now messages are DKIM-signed.

Found one source (problem may be 2013 found, one year later fixed) with a similar problem. There it was an error in the .NET initialization (but not bookmarked).

--

List of required dll:

```
         <dependentAssembly>
            <assemblyIdentity name="MimeKit"
                              publicKeyToken="bede1c8a46c66814"
                              culture="neutral" />
            <codeBase version="3.3.0.0"

                      href="file://d:/sd-code/assemblies-shared/mimekit/mimekit.dll"/>
         </dependentAssembly>



         <dependentAssembly>
            <assemblyIdentity name="System.Text.Encoding.CodePages"
                              publicKeyToken="b03f5f7f11d50a3a"
                              culture="neutral" />

            <codeBase version="4.1.1.0"
                      href="file://d:/sd-code/assemblies-shared/mimekit/System.Text.Encoding.CodePages.dll"/>

         </dependentAssembly>


         <dependentAssembly>
            <assemblyIdentity name="System.Memory"
                              publicKeyToken="cc7b13ffcd2ddd51"
                              culture="neutral" />
            <codeBase version="4.0.1.1"
                      href="file://d:/sd-code/assemblies-shared/mimekit/System.Memory.dll"/>

         </dependentAssembly>


         <dependentAssembly>
            <assemblyIdentity name="System.Buffers"
                              publicKeyToken="cc7b13ffcd2ddd51"
                              culture="neutral" />
            <codeBase version="4.0.3.0"
                      href="file://d:/sd-code/assemblies-shared/mimekit/System.Buffers.dll"/>

         </dependentAssembly>

         <dependentAssembly>
            <assemblyIdentity name="System.Runtime.CompilerServices.Unsafe"
                              publicKeyToken="b03f5f7f11d50a3a"
                              culture="neutral" />
            <codeBase version="4.0.4.1"
                      href="file://d:/sd-code/assemblies-shared/mimekit/System.Runtime.CompilerServices.Unsafe.dll"/>

         </dependentAssembly>


         <dependentAssembly>
            <assemblyIdentity name="MailKit"
                              publicKeyToken="4e064fe7c44a8f1b"
                              culture="neutral" />
            <codeBase version="3.3.0.0"
                      href="file://d:/sd-code/assemblies-shared/mimekit/MailKit.dll"/>

         </dependentAssembly>

         <dependentAssembly>
            <assemblyIdentity name="BouncyCastle.Crypto"
                              publicKeyToken="0e99375e54769942"
                              culture="neutral" />
            <codeBase version="1.9.0.0"
                      href="file://d:/sd-code/assemblies-shared/mimekit/BouncyCastle.Crypto.dll"/>

         </dependentAssembly>

         <dependentAssembly>
            <assemblyIdentity name="System.Numerics.Vectors"
                              publicKeyToken="b03f5f7f11d50a3a"
                              culture="neutral" />
            <codeBase version="4.1.4.0"
                      href="file://d:/sd-code/assemblies-shared/mimekit/System.Numerics.Vectors.dll"/>

         </dependentAssembly>
```

**Comment by jstedfast** [comment]
MimeKit for net4x no longer depends on System.Text.Encoding.CodePages

**Comment by Sicos1977** [comment]
I will give it a try and let you know if the problem is fixed
