### ISSUE TITLE
MimeEntityBeginEventArgs LineNumber 

### ISSUE THREAD

**Issue by gungora** [jstedfast/MimeKit#819]
I need to get the line number where each MIME entity starts. Currently, I am subscribing to the MimeEntityBegin event of the MIME parser but the LineNumber property is internal. It would be wonderful to have a public getter there so that we can get the line number without resorting to reflection.

If there is another way to get this information, please let me know.

**Comment by jstedfast** [comment]
Looks like I added it here: https://github.com/jstedfast/MimeKit/commit/e59521b4911ae129ce7a5bf18874866b0ac34428

Based on that comment, I wasn't sure it'd be useful.

Most of the time when you want to know where in a file a MIME entity starts, you only care about file offset because that's how you would seek to that location.

What are you doing where you have line numbers?

Note: I'll make those properties public, I'm just curious to know how you are using it so that I can better understand the use case.

**Comment by jstedfast** [comment]
Yea, that would probably work better for you. The filter should be very fast.

**Comment by jstedfast** [comment]
MimeKit v3.4.0 has been released with this feature.

**Comment by gungora** [comment]
Amazing! Thanks.
