### ISSUE TITLE
Install-Package : Dependency loop detected for package 'MailKit'

### ISSUE THREAD

**Issue by schittli** [jstedfast/MimeKit#826]
Hello
**Thank you very much for sharing your great work!**

**Describe the bug**

If one tries to install MailKit, one gets the `Dependency loop detected` exception:
```PowerShell
Install-Package MailKit

The package(s) come(s) from a package source that is not marked as trusted.
Are you sure you want to install software from 'nuget.org'?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"): A
Install-Package : Dependency loop detected for package 'MailKit'.
```

**Platform (please complete the following information):**
 - OS: Windows 10, x64
 - .NET Runtime: N/A?
 - .NET Framework: N/A?
 - MimeKit Version: It is not installed

```PowerShell
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.19041.1682
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1682
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**To Reproduce**
1. Open PowerShell 5.1 on Windows
2. Call: `Install-Package MailKit`
3. Answer `a` to answer "Yes to All"
4. See the error: `Install-Package : Dependency loop detected for package 'MailKit'.`

**Expected behavior**

- at least, the Installation Instruction should be clear
- and, even better: `Install-Package MailKit` knows how to install the MailKit 😃 

Thanks a lot, kind regards,
Thomas

**Comment by jstedfast** [comment]
The fact that you get this:

```The package(s) come(s) from a package source that is not marked as trusted.
Are you sure you want to install software from 'nuget.org'?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"): A
```

means you've got some sort of weird NuGet.Config setup which is probably 100% the cause of all of your problems.

Either that or the problem is PowerShell 5.1 which is not capable of handling netstandard.

I don't know how to help you beyond that because I've never seen this problem.

The Install-Package MailKit is meant to be run in Visual Studio's Package Console. The directions specifically state that :-)

**Comment by mbaas2** [comment]
I had the same problem and was able to get over it by doing this:
```
    Install MimeKit -SkipDependencies
    Install MailKit -SkipDependencies
```

(With thank to [Rich Matheisen](https://learn.microsoft.com/en-us/answers/questions/818301/easy-way-to-replace-powershell-send-mailmessage-fu?sort=oldest&orderby=helpful))

**Comment by mbaas2** [comment]
Right - one has to install them seperately. Not ideal - but feasible and it helps to get moving in an environment w/o 
Visual Studio.

**Comment by mbaas2** [comment]
BTW, I now found that root cause for my problem. Thought I'd share it - in case the issue comes up again: I had stupidly named my little toy project "MailKit". And that using "MailKit"...ah, NOW it is clear why the story ended the way it did, but somehow I had assumed this could not be a problem...🤭
