### ISSUE TITLE
MimeMessage.ToString() vs .WriteTo()

### ISSUE THREAD

**Issue by DierkDroth** [jstedfast/MimeKit#832]
@jstedfast I'm sending the MimeMessage to an [email parsing service](https://sigparser.com/) via a POST HTTP request and found that 
```
	File.WriteAllText("file.eml", mimeMessage.ToString());
```
... would yield the same text (when written to a file) as
```
		using (MemoryStream stream = new MemoryStream())
		{
			await mimeMessage.WriteToAsync(stream);
			File.WriteAllBytes("file.eml", stream.ToArray());
		}
```

I could send the content as
```
Encoding.UTF8.GetBytes(mimeMessage.ToString())
```
... or
```
	using (MemoryStream stream = new MemoryStream())
	{
		await mimeMessage.WriteToAsync(stream);
		stream.Position = 0;
		byte[] bytes = stream.ToArray());
	}
```
... and wonder which is the right way.

You're recommending [to not use .ToString()](http://www.mimekit.net/docs/html/M_MimeKit_MimeMessage_ToString.htm) but .WriteTo(). 

Could you elaborate why that is?

**Comment by jstedfast** [comment]
ToString() was only ever meant to be for debugging purposes and as such, it uses iso-8859-1 as the charset to convert the byte array into a string.

This obviously won't work correctly if your message uses any charsets that aren't ASCII or iso-8859-1.

**Comment by DierkDroth** [comment]
@jstedfast thanks for your feedback.

So I'll go with the byte approach then. However, I wonder what SigParser will complain about (or not) if the actual message would neither use ASCII nor iso-8859-1. We'll see...

**Comment by jstedfast** [comment]
MIME is a compound document format that should generally be treated as binary and not a "string" (at least not a C# string) because each MIME part could be in a different charset and the headers may or may not contain 8bit text as well (although unless it is UTF-8, headers should always be encoded such that they fit within US-ASCII, but that is not always the case in the real world).

Then of course there's also `Content-Transfer-Encoding: binary` which means the content will likely contain even null bytes.

**Comment by DierkDroth** [comment]
Thanks again @jstedfast. Glad I don't have to care about that stuff (for the most part) ... ;-)
