### ISSUE TITLE
Malformed message id (I don't think it is a bug in MimeKit)

### ISSUE THREAD

**Issue by Sicos1977** [jstedfast/MimeKit#835]
I used the latest version.

We received an e-mail with what I think is a malformed message-id, because of that mimekit is returning `null` for the e-mail id.

```
From: XXXX | XXXXXXX <xxxx@xxx.nl>
Reply-To: Schade | XXXXXXXXXXXXXX<xxxx@xxx.nl>
Message-ID: <#D26928#O108924#S 20094.9b3890045df8d8ac0132ba357fd8651d@habithuis.fasterforwardelements.nl>
X-Elements: <#D26928#O108924#S 20094.9b3890045df8d8ac0132ba357fd8651d@habithuis.fasterforwardelements.nl>
DD-Elements: <7354ec2df7e0cafd72bf99f4d6353441@habithuis.fasterforwardelements.nl>
```

Is there a way to get the message id even when it is malformed?

**Comment by jstedfast** [comment]
Ugh, yea, that is invalid syntax :(

I guess the easiest solution would be to use `message.Headers[HeaderId.MessageId].Trim ()` which *should* get you the value `<#D26928#O108924#S 20094.9b3890045df8d8ac0132ba357fd8651d@habithuis.fasterforwardelements.nl>`. If you want it in the same format as it would be from `message.MessageId`, just trim the `<>`'s.

I wonder how common this is... I tried to make the Message-ID parser more lenient but I guess it needs to be *even more* lenient - as in something ridiculous like:

```csharp
int lessThan = header.Value.IndexOf ('<');
int greaterThan = header.Value.IndexOf ('>', lessThan + 1);
msgId = header.Value.Substring (lessThan + 1, greaterThan - (lessThan + 1));
```

**Comment by Sicos1977** [comment]
I use the message id as a unique key in a database to identify if I have seen an e-mail before so I'll try your solution with `message.Headers[HeaderId.MessageId].Trim ()` and if that does not return anything just generate a random guid because I need something in the database because the field is not nullable.

**Comment by jstedfast** [comment]
A few points:

1. You are probably already thinking this, but just to make sure, you'll want to keep the format of the string in the database consistent, so if you've been using `message.MessageId` up until now, you'll want to trim the `<>`'s as well, for consistency.
2. The Message-Id header is not guaranteed to be globally unique and you'll want to be careful about making the assumption that they are. They can be a useful tool in helping to narrow down potential matches, but design your software such that if a hacker knows the Message-Id of an incoming important message, he/she can't just send you another message using that same Message-Id in order to deny that message from getting to the user (by tricking your software into thinking that it already has that message based on the Message-Id value).

I was going to try taking a closer look at the code that parses Message-Ids before I close this to see if there isn't a way I can improve the code to handle this case.

I am wondering if perhaps that space could have come from some folding logic in the sending software because the value is so long and if that is the case, it's arguable that MimeKit should better handle that.

If you look at the raw original header of the message, does it look like this?

```
Message-ID: <#D26928#O108924#S
 20094.9b3890045df8d8ac0132ba357fd8651d@habithuis.fasterforwardelements.nl>
```

**Comment by Sicos1977** [comment]
I know that the message id is not unieke enough because everyone can just generate something but it is unique enough for me. The primary key in my database is also build up with more then one field so just not only the message id. Because someone can sent the same e-mail to more then one e-mail adress and in that case all those e-mails have the same message id.

I mainly use the message id to track logging and things like that because I want to know if the e-mail was sent to more then one e-mail address. I also could just generate a random guid as an id but then the logic fails to match it with the same e-mail on another e-mail address. So in my case this was the best solution for me.

The header was copied from the raw headers. I just opened the EML file in notepad on windows and got it from there.

**Comment by jstedfast** [comment]
Okay, thanks for the info.

**Comment by Sicos1977** [comment]
Did you release this fix in a nuget package already? I yet have another e-mail (that is comming from office365) that also has the same issue. All id's are not on the same line but on the next line.

```
Date: Wed, 12 Oct 2022 11:32:11 +0000
Message-ID:
 <AM8P189MB120401270C7242CC4AD1B8ADBF229@AM8P189MB1204.EURP189.PROD.OUTLOOK.COM>
References:
 <AM0PR03MB6195B2252B446B7DDD24C93797209@AM0PR03MB6195.eurprd03.prod.outlook.com>
 <AM0PR03MB6195F3CEAE1DF3882FA43D8D97239@AM0PR03MB6195.eurprd03.prod.outlook.com>
 <85cf88285867483498a4403a16453ba1@AM9P189MB1732.EURP189.PROD.OUTLOOK.COM>
In-Reply-To:
 <85cf88285867483498a4403a16453ba1@AM9P189MB1732.EURP189.PROD.OUTLOOK.COM>
Accept-Language: nl-NL, en-US
Content-Language: nl-NL
```

**Comment by rogatec** [comment]
Hey @jstedfast , I encountered a similar problem with a MessageId.

The `MessageId` was null, but when the customer checked the E-Mail in Outlook, it had a `MessageId` in the header, but with no closing `>` which seemed very weird.

Is there a way to get the (faulty?) MessageId - maybe by parsing the `MimeMessage.Headers` ?

**Comment by rogatec** [comment]
Hey @jstedfast thanks for your advice and thoughts. Another question comes to my mind, have you thought about making the `MimeMessage` object available for testing through an interface?

I dislike the idea to write a wrapper class with an own interface around it, because I wanted to test the raw case where the `MessageId` is null and the Setter id the property disallows a nullable setting.

**Comment by jstedfast** [comment]
@rogatec it is something I've thought about. Can you submit a new issue to track that? I agree it's worth doing.

I've been thinking of changing things to make use of Microsoft.DependencyInjection and interfaces would be a good step toward that.
