### ISSUE TITLE
default line format should always be CRLF instead of LF (on macOS/Linux

### ISSUE THREAD

**Issue by schmitch** [jstedfast/MimeKit#843]
**Is your feature request related to a problem? Please describe.**
currently I talked with @jstedfast already over a pdf that got broken because the line ending was incorrect.
the problem however was in the way how mimekit does write eml's to disk.

**Describe the solution you'd like**
instead of having something like:

```
      if (Environment.NewLine.Length == 1)
        this.newLineFormat = NewLineFormat.Unix;
      else
        this.newLineFormat = NewLineFormat.Dos;
```

inside the `FormatOptions` constructor it should be just `this.newLineFormat = NewLineFormat.Dos;`

**Additional context**

all RFC's for mime are actually talking about CRLF as the default line terminator:

- https://www.rfc-editor.org/rfc/rfc2045#section-2.10
- https://www.rfc-editor.org/rfc/rfc2046#section-4.1.1

modern rfc's do not overwrite this behavior.

**Comment by jstedfast** [comment]
Hi Christian,

You are correct that none of the MIME RFCs allow the use of bare line-feeds for line endings, but the MIME RFCs are really only applicable when formatting messages for transport (SMTP, POP3 and IMAP are some of the main examples).

The reason that MimeKit saves in the native line ending format is because, historically, that's how it's always been done by every mail client in existence.

If you look at Unix mail clients like [Elm](https://en.wikipedia.org/wiki/Elm_(email_client)), [Pine](https://en.wikipedia.org/wiki/Pine_%28email_client%29), [mutt](https://en.wikipedia.org/wiki/Mutt_(email_client)), [Thunderbird](https://en.wikipedia.org/wiki/Mozilla_Thunderbird) or [Evolution](https://en.wikipedia.org/wiki/GNOME_Evolution), they all save email in the Unix line-ending format (LF as opposed to CRLF).

To override this behavior, you can do this:

```csharp
var options = FormatOptions.Default.Clone ();
options.NewLineFormat = NewLineFormat.Dos;

message.WriteTo (options, fileName);
```
