### ISSUE TITLE
EMF type not supported

### ISSUE THREAD

**Issue by SanaWaseem** [jstedfast/MimeKit#844]
This is happening in dot net core when I am giving the emf content type **image/x-emf** and sending it in the MimeTypes.TryGetExtension method, it is returning NULL. Why is not supporting emf content type

**Comment by jstedfast** [comment]
Any MIME-Type where the subtype starts with "x-" is a non-standard MIME-Type (the "x-" means it's an extension to the standard and has not yet been officially recognized).

The official MIME-Type for EMF files is **image/emf**.

You can also use [MimeTypes.Register](http://www.mimekit.net/docs/html/M_MimeKit_MimeTypes_Register.htm) to register additional mime-types.

That said, the mappings did not contain **image/emf** either because it has only been recently added.

I also added **image/x-emf**.

**Comment by SanaWaseem** [comment]
Thank you for the prompt reply and fix. 
Will this be available in 3.4.1?
