### ISSUE TITLE
InReplyTo ArgumentException for a specific value

### ISSUE THREAD

**Issue by Nevca** [jstedfast/MimeKit#912]
**Describe the bug**
`MimeMessage.InReplyTo` calls `MailboxAddress.TryParse` and throws `ArgumentException` if it fails to parse the given value.

I can reproduce this with the following string:
`[d7e8bc604f797c18ba8120250cbd8c04-JFBVALKQOJXWILKCJQZFA7CDNRQXE2LUPF6EIYLUMFGG643TPRCXQ32TNV2HA===@microsoft.com]`

However, `MimeMessage.References` does not use `MailboxAddress.TryParse`, thus the same string is accepted and inserted in the references collection.

I also tested with the following code, and it is also working:
`mimeMessage.Headers.Add(HeaderId.InReplyTo, "[d7e8bc604f797c18ba8120250cbd8c04-JFBVALKQOJXWILKCJQZFA7CDNRQXE2LUPF6EIYLUMFGG643TPRCXQ32TNV2HA===@microsoft.com]")`

I'm somewhat confused which is the correct behavior. Shouldn't all three either throw or do not, given the same input string?

Which code should I use if I accept the example string as valid? Or should I trim the invalid characters? Is there a Util class or something I could use for trimming?

**Comment by jstedfast** [comment]
MimeKit was designed to be strict in what it will send (which requires strictness in what it would accept as values for `message.InReplyTo = ...`, etc) but relaxed in what it would accept (e.g. MimeMessage.Load).

Over time, I've had to dumb down the message-id parser(s) that are used for various property setters because of the need to be able to reply to messages with garbage message-ids (presumably like in your situation).

It looks like I need to do the same for the InReplyTo property setter.

**Comment by Nevca** [comment]
Thank you.

**Comment by jstedfast** [comment]
You're welcome 🙏
