### ISSUE TITLE
High memory/CPU usage when loading mime message with big, multiline headers

### ISSUE THREAD

**Issue by rafal-bielinski** [jstedfast/MimeKit#919]
**Description**
I have a problem with loading mime message that has 80k emails in a "to" header which spans across 40k lines (~2MB of text) and uses some custom headers with similar size. MimeMessage.Load of 5MB message takes about 1 minute and there is a lot of GC going on (really a lot).

**Platform:**
 - OS: Windows 10
 - .NET Runtime: CLR
 - .NET Framework: .NET 4.7.2
 - MimeKit Version: 3.5.0

**To Reproduce**
1. Try to do MimeMessage.Load on eml file from this zip: [80k-participants.zip](https://github.com/jstedfast/MimeKit/files/11488757/80k-participants.zip) (as file stream, persistent flag set to true)
```csharp
using (var stream = File.OpenRead("80k-participants.eml"))
using (var mimeMessage = MimeMessage.Load(stream, true))
{
}
```

**Expected behavior**
File is loaded faster, with better mem usage (less gc)

**Comment by jstedfast** [comment]
I like trying to optimize this kind of stuff.

I'll try to take an in-depth look at this over the weekend.

Reducing memory allocations benefits everyone using MimeKit even if they never encounter your specific scenario.

**Comment by jstedfast** [comment]
Okay, so just looking at this message, I would bet that the issue is in MimeParser.cs's logic for resizing the header buffer byte[] array. It is probably doing a TON of reallocations as the needed buffer size grows and grows.

I added this email message to my benchmarks to test MimeParser (which is what you are using), ExperimentalMimeParser (which is a newer parser design that I was trying out and is the future for MimeKit) and MimeReader (which is a SAX-like MIME reader that ExperimenalMimeParser is based on).

|                                            Method |       Mean |    Error |   StdDev |
|-------------------------------------------------- |-----------:|---------:|---------:|
|             MimeParser_EightyThousandParticipants | 9,181.2 ms | 43.05 ms | 38.17 ms |
| ExperimentalMimeParser_EightyThousandParticipants |   152.3 ms |  2.98 ms |  4.72 ms |
|             MimeReader_EightyThousandParticipants |   167.9 ms |  7.15 ms | 21.07 ms |

Interestingly, the newer parser/reader are MASSIVELY faster.

All 3 implementations grow their header buffer by 64-byte multiples, but MimeReader/ExperimentalMimeParser use aggressive inlining. So I tried adding that to MimeParser but that didn't improve anything (which was expected based on my initial analysis).

If I change MimeParser to grow its header buffer to the nearest 512-byte multiple rather than the nearest 64-byte multiple, the time taken is *drastically* reduced:

|                                            Method |       Mean |   Error |  StdDev |
|-------------------------------------------------- |-----------:|--------:|--------:|
|             MimeParser_EightyThousandParticipants | 1,155.0 ms | 8.39 ms | 7.44 ms |
| ExperimentalMimeParser_EightyThousandParticipants |   146.5 ms | 1.87 ms | 1.57 ms |
|             MimeReader_EightyThousandParticipants |   145.5 ms | 1.50 ms | 1.25 ms |

If I then switch to using 1024-byte multiples, time taken is cut in half:

|                                            Method |     Mean |   Error |   StdDev |
|-------------------------------------------------- |---------:|--------:|---------:|
|             MimeParser_EightyThousandParticipants | 592.0 ms | 8.80 ms | 17.97 ms |
| ExperimentalMimeParser_EightyThousandParticipants | 146.2 ms | 1.18 ms |  0.99 ms |
|             MimeReader_EightyThousandParticipants | 146.2 ms | 1.69 ms |  1.50 ms |

**Next Steps:**

Would you be willing to try the ExperimentalMimeParser instead of MimeParser to see if that fits your needs?

If that solves your issue, that's just another justification for making ExperimentalMimeParser the default in a future release (v5.0?).

I have very comprehensive unit tests for both xMimeParser implementations (as well as MimeReader), but with all of the developers out there relying on MimeKit, I feel obligated to maintain trust

**Comment by jstedfast** [comment]
Okay, I see why the MimeReader/ExperimentalMimeParser implementation is so much faster...

I had forgotten what my newer header parser did, but now I remember after looking things over.

The old MimeParser implementation would scan 1 line and then append to the headerBuffer.

The new MimeReader/ExperimentalMimeParser implementation doesn't append to the headerBuffer until it either reaches the end of the header value (multi-line or not) -or- until it reaches the end if the input buffer (which is 4K).

This means that the newer implementation is likely only reallocating the headerBuffer once every 4K of input data read which, in your example test case, is obviously a MASSIVE win.

There's no way to make the old MimeParser match that level of performance unless I make the headerBuffer grow by 4K at a time which is way too much under normal operation. I would consider 1K, but 4K is too big.

**Comment by rafal-bielinski** [comment]
Hey, sorry for the late response and big thanks for the analysis of this problem.
Trying new experimental MimeParser seems like an interesting idea but I have some questions:
	• How mature you would say it is? When are you planning to release it to production (if in MimeKit 5.0, what is the plan?)
	• We would need to put new parser under some toggle, to be able to fall back to the old one in case of unexpected problems, would it be possible to have a MimeKit version with both parsers?
	• How would you ship this new parser, would it be some beta version of MimeKit 5.0, or maybe experimental parser in a separate dll which can work with MimeKit 4.0?

If I understand correctly, alternative would be to play with parameter that controls headerBuffer growth, maybe even make it configurable for the parser user (would it be even an option?).

**Comment by jstedfast** [comment]
> How mature you would say it is? When are you planning to release it to production (if in MimeKit 5.0, what is the plan?)

I have a very high trust in it (it's been part of MimeKit since v3.0). The unit tests cover 96.62% of ExperimentalMimeParser.cs vs 95.56% of MimeParser.cs and the results of parsing all of the messages in my collection 100% identical.

I had planned to make it the default in v4.0 but:

1. I would like to hear confirmation from other developers that this is not causing any unaccounted for issues (unlikely at 96.6+% code coverage, but there is that 3.4% non-tested code).
2. I pushed v4.0 because of of the move from Portable.BouncyCastle (a netstandard port of the original BouncyCastle package) to BouncyCastle.Cryptography (the *new* official package that supports netstandard). And this was needed ASAP so I dropped all of the other planned features for v4.0, including the renaming of ExperimentalMimeParser.cs to MimeParser.cs.

> We would need to put new parser under some toggle, to be able to fall back to the old one in case of unexpected problems, would it be possible to have a MimeKit dll with both parsers?

Already available. MimeKit >= v3.x ship with both parsers included. The old parser is [MimeParser](http://www.mimekit.net/docs/html/T_MimeKit_MimeParser.htm) and the new parser is [ExperimentalMimeParser](http://www.mimekit.net/docs/html/T_MimeKit_ExperimentalMimeParser.htm).

> How would you ship this new parser, would it be some beta version of MimeKit 5.0, or maybe experimental parser in a separate dll which can work with MimeKit 4.0?

MimeKit v4.0 already includes both parsers.

All you have to do is change `new MimeParser (...)` to `new ExperimentalMimeParser (...)`.

**Comment by rafal-bielinski** [comment]
That's super cool, I'll try it out. Thx.
