### ISSUE TITLE
System.Security.Cryptography vs Org.BouncyCastle.Crypto

### ISSUE THREAD

**Issue by anton-gogolev** [jstedfast/MimeKit#967]
While browsing through the source code for [DkimHashStream](https://github.com/jstedfast/MimeKit/blob/master/MimeKit/Cryptography/DkimHashStream.cs) I found a lot of `ifdef`s similar to

```c#
#if ENABLE_NATIVE_DKIM
		readonly HashAlgorithm digest;
#else
		readonly IDigest digest;
#endif
```

`ENABLE_NATIVE_DKIM` isn't defined anywhere, so that means we're always using Org.BouncyCastle.Crypto.

Now, there's ae73ad97acaac806981bb59b6a6688a00245378a from a while back that says:

> Disable System.Security DKIM implementation for now
>
> It doesn't seem to be noticably faster than the BouncyCastle implementation, so might as well continue to use the old tried & tested code for now.

Can you please elaborate on this decision of yours? .NET's been evolving quite fast and I feel that there's some potential for performance gains to be had there.

**Comment by jstedfast** [comment]
I didn't abandon the code for simply performance reasons. I abandoned it (for now) because I didn't have a way to fully support DKIM using System.Security due to the use of unsupported crypto algorithms, namely ED25519.

Unfortunately, even once dotnet adds support for it, I won't be able to switch to System.Security's implementation because it won't be supported on all versions of .NET/.NET Framework.

My hope when I implemented the non-BouncyCastle code-paths was to add DKIM support to MimeKitLite, but shortly after starting to implement it, I had to add support for ED25519 and that pretty much killed my efforts.

At that point, the only reason to keep it around was maybe perf reasons but as I noted, there wasn't any noticeable perf difference, so it became pointless.
