### ISSUE TITLE
SmtpClient with ttls just hangs

### ISSUE THREAD

**Issue by rolfwessels** [jstedfast/MimeKit#97]
Hi Jeff, 

Sorry I am back with some more connection issue. This time it is SMTP. We want to move to use Amazon SES.

Again the connection seems to hang as soon as I try to enable ttls.

```
using(SmtpClient client = new SmtpClient())
    {
        // Connect to the server
		client.Dump("Connecting");
        client.Connect("email-smtp.eu-west-1.amazonaws.com", 587, true); // The handshake failed due to an unexpected packet format.
		//client.Connect(new Uri ("smtp://email-smtp.eu-west-1.amazonaws.com:587/?starttls=false")); // SmtpCommandException: Must issue a STARTTLS command first
		//client.Connect("email-smtp.eu-west-1.amazonaws.com", 587, false); // just hangs
		//client.Connect(new Uri ("smtp://email-smtp.eu-west-1.amazonaws.com:587/?starttls=true")); // just hangs
		
		client.Dump("Connected");
        // Authenticate ourselves towards the server
        client.Authenticate("hmmuser", "invalidpassword"); // should fail here
		client.Dump("Authenticated");
    } 
```
I'm really supprised that im the only person with this issue.

Anyway, if you have some time. Your assitance would be greatly appriciated

**Comment by jstedfast** [comment]
I don't get a hang... it makes it all the way to the authentication step and fails there due to an invalid user/pass. Here's the test program I used:

```csharp
using System;

using MailKit;
using MailKit.Net.Smtp;

namespace StartTlsHang {
	public class Program
	{
		public static void Main ()
		{
			using (var client = new SmtpClient (new ProtocolLogger (Console.OpenStandardOutput ()))) {
				// Connect to the server
				client.Connect("email-smtp.eu-west-1.amazonaws.com", 587, false);
				
				// Authenticate ourselves towards the server
				client.Authenticate("hmmuser", "invalidpassword"); // should fail here
			} 
		}
	}
}
```

and here's the output:

```
Connected to smtp://email-smtp.eu-west-1.amazonaws.com:587/
S: 220 email-smtp.amazonaws.com ESMTP SimpleEmailService-909942753 SQ0ZvlrymHnyOtVtfVCX
C: EHLO [192.168.1.105]
S: 250-email-smtp.amazonaws.com
S: 250-8BITMIME
S: 250-SIZE 10485760
S: 250-STARTTLS
S: 250-AUTH PLAIN LOGIN
S: 250 Ok
C: STARTTLS
S: 220 Ready to start TLS
C: EHLO [192.168.1.105]
S: 250-email-smtp.amazonaws.com
S: 250-8BITMIME
S: 250-SIZE 10485760
S: 250-STARTTLS
S: 250-AUTH PLAIN LOGIN
S: 250 Ok
C: AUTH PLAIN AGhtbXVzZXIAaW52YWxpZHBhc3N3b3Jk
S: 535 Authentication Credentials Invalid
C: AUTH LOGIN aG1tdXNlcg==
S: 334 UGFzc3dvcmQ6
C: aW52YWxpZHBhc3N3b3Jk
S: 535 Authentication Credentials Invalid

Unhandled Exception:
MailKit.Security.AuthenticationException: Authentication failed.
  at MailKit.Net.Smtp.SmtpClient.Authenticate (ICredentials credentials, CancellationToken cancellationToken) [0x00000] in <filename unknown>:0 
  at MailKit.MailService.Authenticate (System.String userName, System.String password, CancellationToken cancellationToken) [0x00000] in <filename unknown>:0 
  at StartTlsHang.Program.Main () [0x00000] in <filename unknown>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: MailKit.Security.AuthenticationException: Authentication failed.
  at MailKit.Net.Smtp.SmtpClient.Authenticate (ICredentials credentials, CancellationToken cancellationToken) [0x00000] in <filename unknown>:0 
  at MailKit.MailService.Authenticate (System.String userName, System.String password, CancellationToken cancellationToken) [0x00000] in <filename unknown>:0 
  at StartTlsHang.Program.Main () [0x00000] in <filename unknown>:0 
```

The reason the following line fails is because it tries to make an ssl-wrapped connection, but the server is in plain-text mode:

```csharp
client.Connect("email-smtp.eu-west-1.amazonaws.com", 587, true); // The handshake failed due to an unexpected packet format.
```

These 2 connection calls are actually the same (starttls is enabled by default):

```csharp
//client.Connect("email-smtp.eu-west-1.amazonaws.com", 587, false); // just hangs
//client.Connect(new Uri ("smtp://email-smtp.eu-west-1.amazonaws.com:587/?starttls=true")); // just hangs
```

Hope that clarifies things for you.

Also, this bug report really belongs under [MailKit](https://github.com/jstedfast/MailKit) as that is where SMTP, POP3, and IMAP support are implemented.

**Comment by jstedfast** [comment]
Perhaps you can try using a packet sniffer to see what is going on? I have no idea what the problem could be w/o more information since I cannot reproduce on my end.

**Comment by jstedfast** [comment]
Also, if you get more information, please open an issue under [MailKit](https://github.com/jstedfast/MailKit) and not MimeKit. Thanks.

**Comment by magnumb** [comment]
I had the same problem and resolved it by setting SslProtocols=Tls12 and useSsl=false:

using (var client = new SmtpClient(new ProtocolLogger(@"C:\temp\MailKit.txt")))
{
	client.SslProtocols = System.Security.Authentication.SslProtocols.Tls12;
	client.Connect("email-smtp.us-east-1.amazonaws.com", 587, false);
	client.Authenticate(userName, password);
	client.Send(mimeMessage);
	client.Disconnect(true);
}

**Comment by jstedfast** [comment]
Just to clarify things a bit and explain why @magnumb's change made things work:

Port 587 is a clear-text port, not an SSL port.

There are 2 ways to get "SSL" with IMAP, POP3, and SMTP:

1. connect to an SSL-wrapped port (993 for IMAP, 995 for POP3, and 465 for SMTP)
2. connect to the clear-text port and toggle into SSL-mode via the `STARTTLS` command (`STLS` for POP3)

When you pass `true` as the `useSsl` argument to the `Connect` method, you are telling MailKit to treat the port as if it were an SSL-wrapped port (which port 587 is not). This will obviously fail becaue the server will be replying with clear-text responses but MailKit will be using an `SslStream` which will assume that the responses are encrypted (which they are not).

When you pass `false` as the `useSsl` argument to the `Connect` method, MailKit connects via a clear-text connection and then, if the server supports it, toggles into SSL-mode via the `STARTTLS` command.

You can also use the `Connect` variant that takes a [SecureSocketOptions](http://www.mimekit.net/docs/html/T_MailKit_Security_SecureSocketOptions.htm) argument instead of a `bool` which allows for much finer-grained control over what MailKit does.

Hope that explanation helps.
